#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Generate yearly SQL INSERT scripts with MOEX historical prices.

Usage:
  DATABASE_URL=... ./scripts/moex_history/generate_prices_sql.sh [options]

Options:
  --from-year <YYYY>   First year to generate (default: 2018)
  --to-year <YYYY>     Last year to generate (default: current year)
  --out-dir <path>     Output directory for prices_<year>.sql
  --provider <name>    Provider value for prices.provider (default: MOEX)
  --base-url <url>     MOEX ISS base URL (default: https://iss.moex.com/iss)
  --boards <csv>       Board priority list (default: TQBR,TQTF,TQIF,TQCB,TQOB)
  --help               Show this message
USAGE
}

require_bin() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "Missing required binary: $name" >&2
    exit 1
  fi
}

normalize_year() {
  local value="$1"
  if [[ ! "$value" =~ ^[0-9]{4}$ ]]; then
    echo "Invalid year: $value" >&2
    exit 1
  fi
  echo "$value"
}

fetch_ticker_year() {
  local ticker="$1"
  local market="$2"
  local year="$3"
  local output_file="$4"

  local from_date="${year}-01-01"
  local till_date="${year}-12-31"

  local board
  for board in "${BOARDS[@]}"; do
    local start=0
    while true; do
      local url="${BASE_URL}/history/engines/stock/markets/${market}/boards/${board}/securities/${ticker}.json?from=${from_date}&till=${till_date}&start=${start}&iss.meta=off&iss.only=history&history.columns=SECID,TRADEDATE,LEGALCLOSEPRICE,MARKETPRICE2,CLOSE,WAPRICE,LCLOSEPRICE,LAST"
      local response
      if ! response="$(curl -fsS --retry 2 --retry-delay 1 "$url")"; then
        echo "WARN: request failed for ticker=${ticker}, market=${market}, board=${board}, year=${year}" >&2
        break
      fi

      local parsed
      parsed="$(jq -r '
        (.history.data // [])[]
        | . as $r
        | ($r[2] // $r[3] // $r[4] // $r[5] // $r[6] // $r[7]) as $raw_price
        | ($raw_price | tostring | gsub(","; ".")) as $price
        | select(($r[1] | tostring) | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}$"))
        | select($price | test("^[0-9]+(\\.[0-9]+)?$"))
        | select(($price | tonumber) > 0)
        | [($r[0] | tostring), ($r[1] | tostring), $price] | @tsv
      ' <<<"$response")"

      if [[ -n "$parsed" ]]; then
        printf '%s\n' "$parsed" >>"$output_file"
      fi

      local page_count
      page_count="$(jq -r '(.history.data // []) | length' <<<"$response")"
      if [[ "$page_count" -lt "$PAGE_SIZE" ]]; then
        break
      fi

      start=$((start + PAGE_SIZE))
    done
  done
}

write_year_sql() {
  local year="$1"
  local rows_file="$2"
  local sql_file="$3"

  local rows_count
  rows_count="$(wc -l <"$rows_file" | tr -d '[:space:]')"

  {
    echo "-- Generated by scripts/moex_history/generate_prices_sql.sh"
    echo "-- Year: ${year}"
    echo "-- Provider: ${PROVIDER}"
    echo "-- Rows: ${rows_count}"
    echo ""

    if [[ "$rows_count" -eq 0 ]]; then
      echo "BEGIN;"
      echo "COMMIT;"
      echo "-- No MOEX history rows found for this year."
      return
    fi

    echo "BEGIN;"
    echo "WITH src (ticker, trade_date, price) AS ("
    echo "    VALUES"

    awk -F $'\t' -v total="$rows_count" '
      {
        ticker = $1
        gsub(/\047/, "\047\047", ticker)
        price = $3
        gsub(/,/, ".", price)
        suffix = (NR < total ? "," : "")
        printf "    (\047%s\047, DATE \047%s\047, %s)%s\n", ticker, $2, price, suffix
      }
    ' "$rows_file"

    cat <<SQL_TAIL
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|${PROVIDER}') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.ticker) = s.ticker
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    '${PROVIDER}',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
SQL_TAIL
  } >"$sql_file"
}

FROM_YEAR=2018
TO_YEAR="$(date +%Y)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${SCRIPT_DIR}/sql"
PROVIDER="MOEX"
BASE_URL="https://iss.moex.com/iss"
BOARDS_CSV="TQBR,TQTF,TQIF,TQCB,TQOB"
PAGE_SIZE=100

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-year)
      FROM_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --to-year)
      TO_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --provider)
      PROVIDER="${2:-}"
      shift 2
      ;;
    --base-url)
      BASE_URL="${2:-}"
      shift 2
      ;;
    --boards)
      BOARDS_CSV="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required" >&2
  exit 1
fi

if [[ ! "$PROVIDER" =~ ^[A-Za-z0-9_-]{1,50}$ ]]; then
  echo "Invalid provider. Allowed: letters, numbers, underscore, dash (max 50)." >&2
  exit 1
fi
PROVIDER="$(printf '%s' "$PROVIDER" | tr '[:lower:]' '[:upper:]')"

if (( FROM_YEAR > TO_YEAR )); then
  echo "from-year must be <= to-year" >&2
  exit 1
fi

require_bin curl
require_bin jq
require_bin psql
require_bin awk
require_bin mktemp

IFS=',' read -r -a BOARDS <<<"$BOARDS_CSV"
if [[ "${#BOARDS[@]}" -eq 0 ]]; then
  echo "Boards list is empty" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

instruments_file="$tmp_dir/instruments.tsv"

psql "$DATABASE_URL" -X -A -t -F $'\t' -v ON_ERROR_STOP=1 -c "
select distinct
       upper(trim(ticker)) as ticker,
       case
         when type = 2 then 'bonds'
         when type in (1, 3) then 'shares'
         else null
       end as market
from instruments
where ticker is not null
  and btrim(ticker) <> ''
  and type in (1, 2, 3)
order by 1;
" >"$instruments_file"

instrument_count="$(wc -l <"$instruments_file" | tr -d '[:space:]')"
if [[ "$instrument_count" -eq 0 ]]; then
  echo "No eligible instruments found in table instruments" >&2
  exit 1
fi

echo "Found ${instrument_count} instruments. Generating SQL ${FROM_YEAR}..${TO_YEAR}" >&2

for ((year = FROM_YEAR; year <= TO_YEAR; year++)); do
  raw_file="$tmp_dir/raw_${year}.tsv"
  dedup_file="$tmp_dir/dedup_${year}.tsv"
  sql_file="${OUT_DIR}/prices_${year}.sql"

  : >"$raw_file"

  while IFS=$'\t' read -r ticker market; do
    [[ -z "$ticker" || -z "$market" ]] && continue
    fetch_ticker_year "$ticker" "$market" "$year" "$raw_file"
  done <"$instruments_file"

  awk -F $'\t' 'NF >= 3 && !seen[$1 FS $2]++ { print $1 "\t" $2 "\t" $3 }' "$raw_file" >"$dedup_file"

  write_year_sql "$year" "$dedup_file" "$sql_file"

  year_rows="$(wc -l <"$dedup_file" | tr -d '[:space:]')"
  echo "Generated ${sql_file} (${year_rows} rows)" >&2
done

echo "Done." >&2
