#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Generate yearly SQL INSERT scripts with MOEX historical prices.

Usage:
  DATABASE_URL=... ./scripts/moex_history/generate_prices_sql.sh [options]

Options:
  --from-year <YYYY>   First year to generate (default: 2018)
  --to-year <YYYY>     Last year to generate (default: current year)
  --out-dir <path>     Output directory for prices_<year>.sql
  --provider <name>    Provider value for prices.provider (default: MOEX)
  --base-url <url>     MOEX ISS base URL (default: https://iss.moex.com/iss)
  --boards <csv>       Board priority list (default: TQBR,TQTF,TQIF,TQCB,TQOB,CETS,MTQR)
  --targets-file <path>
                       Explicit TSV file with request ticker, market, and
                       optional local DB ticker columns. When set, instruments
                       are loaded from this file instead of querying table
                       instruments.
  --help               Show this message
USAGE
}

require_bin() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "Missing required binary: $name" >&2
    exit 1
  fi
}

normalize_year() {
  local value="$1"
  if [[ ! "$value" =~ ^[0-9]{4}$ ]]; then
    echo "Invalid year: $value" >&2
    exit 1
  fi
  echo "$value"
}

fetch_ticker_year() {
  local request_ticker="$1"
  local market="$2"
  local db_ticker="$3"
  local year="$4"
  local output_file="$5"

  local from_date="${year}-01-01"
  local till_date="${year}-12-31"

  local boards=("${BOARDS[@]}")
  local url_path_template="history/engines/stock/markets/${market}/boards/%s/securities/${request_ticker}.json"

  if [[ "$market" == "currency" ]]; then
    boards=("CETS")
    url_path_template="history/engines/currency/markets/selt/boards/%s/securities/${request_ticker}.json"
  fi

  local board
  for board in "${boards[@]}"; do
    local start=0
    while true; do
      local path
      printf -v path "$url_path_template" "$board"
      local url="${BASE_URL}/${path}?from=${from_date}&till=${till_date}&start=${start}&iss.meta=off&iss.only=history&history.columns=SECID,TRADEDATE,LEGALCLOSEPRICE,MARKETPRICE2,CLOSE,WAPRICE,LCLOSEPRICE,LAST,CURRENCYID,FACEVALUE,FACEUNIT,ACCINT"
      local response
      if ! response="$(curl -fsS --retry 2 --retry-delay 1 "$url")"; then
        echo "WARN: request failed for request_ticker=${request_ticker}, market=${market}, board=${board}, year=${year}" >&2
        break
      fi

      local parsed
      parsed="$(jq -r '
        (.history.columns // []) as $columns
        | def col($name): ($columns | index($name));
          def val($row; $name):
            (col($name)) as $index
            | if $index == null then null else $row[$index] end;
          (.history.data // [])[]
        | . as $r
        | ([val($r; "LEGALCLOSEPRICE"), val($r; "MARKETPRICE2"), val($r; "CLOSE"), val($r; "WAPRICE"), val($r; "LCLOSEPRICE"), val($r; "LAST")]
            | map(select(. != null))
            | .[0]) as $raw_price
        | ($raw_price | tostring | gsub(","; ".")) as $price
        | ((val($r; "CURRENCYID") // "") | tostring | ascii_upcase) as $trade_currency
        | ((val($r; "FACEVALUE") // "") | tostring | gsub(","; ".")) as $face_value
        | ((val($r; "FACEUNIT") // "") | tostring | ascii_upcase) as $face_currency
        | ((val($r; "ACCINT") // "") | tostring | gsub(","; ".")) as $accrued_interest
        | ((val($r; "TRADEDATE") // "") | tostring) as $trade_date
        | select($trade_date | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}$"))
        | select($price | test("^[0-9]+(\\.[0-9]+)?$"))
        | select(($price | tonumber) > 0)
        | select(($face_value == "") or ($face_value | test("^[0-9]+(\\.[0-9]+)?$")))
        | select(($accrued_interest == "") or ($accrued_interest | test("^[0-9]+(\\.[0-9]+)?$")))
        | [$trade_date, $price, $trade_currency, $face_value, $face_currency, $accrued_interest] | @tsv
      ' <<<"$response" | awk -F $'\t' -v db_ticker="$db_ticker" 'NF >= 2 { print db_ticker "\t" $1 "\t" $2 "\t" $3 "\t" $4 "\t" $5 "\t" $6 }')"

      if [[ -n "$parsed" ]]; then
        printf '%s\n' "$parsed" >>"$output_file"
      fi

      local page_count
      page_count="$(jq -r '(.history.data // []) | length' <<<"$response")"
      if [[ "$page_count" -lt "$PAGE_SIZE" ]]; then
        break
      fi

      start=$((start + PAGE_SIZE))
    done
  done
}

write_year_sql() {
  local year="$1"
  local rows_file="$2"
  local sql_file="$3"

  local rows_count
  rows_count="$(wc -l <"$rows_file" | tr -d '[:space:]')"

  {
    echo "-- Generated by scripts/moex_history/generate_prices_sql.sh"
    echo "-- Year: ${year}"
    echo "-- Provider: ${PROVIDER}"
    echo "-- Rows: ${rows_count}"
    echo ""

    if [[ "$rows_count" -eq 0 ]]; then
      echo "BEGIN;"
      echo "COMMIT;"
      echo "-- No MOEX history rows found for this year."
      return
    fi

    echo "BEGIN;"
    echo "CREATE TEMP TABLE stg_moex_prices_src ("
    echo "    ticker text NOT NULL,"
    echo "    trade_date date NOT NULL,"
    echo "    raw_price numeric(18,8) NOT NULL,"
    echo "    trade_currency_id text NULL,"
    echo "    face_value numeric(18,8) NULL,"
    echo "    face_currency_id text NULL,"
    echo "    accrued_interest numeric(18,8) NULL"
    echo ") ON COMMIT DROP;"
    echo ""
    echo "INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)"
    echo "VALUES"

    awk -F $'\t' -v total="$rows_count" '
      function sql_text(value,    escaped) {
        if (value == "") {
          return "NULL::text"
        }
        escaped = value
        gsub(/\047/, "\047\047", escaped)
        return sprintf("\047%s\047", escaped)
      }

      function sql_numeric(value) {
        if (value == "") {
          return "NULL::numeric"
        }
        gsub(/,/, ".", value)
        return value
      }

      {
        ticker = $1
        gsub(/\047/, "\047\047", ticker)
        raw_price = $3
        gsub(/,/, ".", raw_price)
        suffix = (NR < total ? "," : "")
        printf "    (\047%s\047, DATE \047%s\047, %s, %s, %s, %s, %s)%s\n",
          ticker,
          $2,
          raw_price,
          sql_text($4),
          sql_numeric($5),
          sql_text($6),
          sql_numeric($7),
          suffix
      }
    ' "$rows_file"

    cat <<SQL_TAIL
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|${PROVIDER}') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        '${PROVIDER}',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    ${rows_count} AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO \$\$
DECLARE
    expected_rows integer := ${rows_count};
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = '${PROVIDER}';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', ${year}, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', ${year}, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', ${year}, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', ${year}, expected_rows, resolved_rows, applied_rows;
END \$\$;

COMMIT;
SQL_TAIL
  } >"$sql_file"
}

FROM_YEAR=2018
TO_YEAR="$(date +%Y)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${SCRIPT_DIR}/sql"
PROVIDER="MOEX"
BASE_URL="https://iss.moex.com/iss"
BOARDS_CSV="TQBR,TQTF,TQIF,TQCB,TQOB,CETS,MTQR"
PAGE_SIZE=100
TARGETS_FILE=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-year)
      FROM_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --to-year)
      TO_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --provider)
      PROVIDER="${2:-}"
      shift 2
      ;;
    --base-url)
      BASE_URL="${2:-}"
      shift 2
      ;;
    --boards)
      BOARDS_CSV="${2:-}"
      shift 2
      ;;
    --targets-file)
      TARGETS_FILE="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ ! "$PROVIDER" =~ ^[A-Za-z0-9_-]{1,50}$ ]]; then
  echo "Invalid provider. Allowed: letters, numbers, underscore, dash (max 50)." >&2
  exit 1
fi
PROVIDER="$(printf '%s' "$PROVIDER" | tr '[:lower:]' '[:upper:]')"

if (( FROM_YEAR > TO_YEAR )); then
  echo "from-year must be <= to-year" >&2
  exit 1
fi

require_bin curl
require_bin jq
require_bin awk
require_bin mktemp

if [[ -z "$TARGETS_FILE" ]]; then
  require_bin psql
fi

IFS=',' read -r -a BOARDS <<<"$BOARDS_CSV"
if [[ "${#BOARDS[@]}" -eq 0 ]]; then
  echo "Boards list is empty" >&2
  exit 1
fi

mkdir -p "$OUT_DIR"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

instruments_file="$tmp_dir/instruments.tsv"

if [[ -n "$TARGETS_FILE" ]]; then
  if [[ ! -f "$TARGETS_FILE" ]]; then
    echo "Targets file not found: $TARGETS_FILE" >&2
    exit 1
  fi

  awk -F $'\t' '
    NF >= 2 {
      ticker = toupper($1)
      market = tolower($2)
      db_ticker = (NF >= 3 ? toupper($3) : ticker)
      if (ticker != "" && db_ticker != "" && (market == "shares" || market == "bonds" || market == "currency")) {
        print ticker "\t" market "\t" db_ticker
      }
    }
  ' "$TARGETS_FILE" | awk -F $'\t' '!seen[$1 FS $2 FS $3]++ { print $1 "\t" $2 "\t" $3 }' >"$instruments_file"
else
  if [[ -z "${DATABASE_URL:-}" ]]; then
    echo "DATABASE_URL is required when --targets-file is not provided" >&2
    exit 1
  fi

  psql "$DATABASE_URL" -X -A -t -F $'\t' -v ON_ERROR_STOP=1 -c "
  with alias_candidates as (
      select
          ia.instrument_id,
          upper(trim(ia.alias_code)) as alias_code,
          row_number() over (partition by ia.instrument_id order by ia.alias_code) as rn
      from instrument_aliases ia
      join instruments i on i.id = ia.instrument_id
      where ia.alias_code is not null
        and btrim(ia.alias_code) <> ''
        and upper(trim(ia.alias_code)) <> upper(coalesce(i.isin, ''))
  )
  select distinct
         upper(trim(
             case
               when i.type = 4 and ac.alias_code is not null
                 then ac.alias_code
               when upper(trim(i.ticker)) ~ '^[A-Z]{2}[A-Z0-9]{10}$' and ac.alias_code is not null
                 then ac.alias_code
               else i.ticker
             end
         )) as request_ticker,
         case
           when i.type = 2 then 'bonds'
           when i.type in (1, 3) then 'shares'
           when i.type = 4 then 'currency'
           else null
         end as market,
         upper(trim(i.ticker)) as db_ticker
  from instruments i
  left join alias_candidates ac on ac.instrument_id = i.id and ac.rn = 1
  where i.ticker is not null
    and btrim(i.ticker) <> ''
    and i.type in (1, 2, 3, 4)
    and i.is_trading = true
    and upper(coalesce(i.price_source, '')) = 'MOEX'
  order by 3;
  " >"$instruments_file"
fi

instrument_count="$(wc -l <"$instruments_file" | tr -d '[:space:]')"
if [[ "$instrument_count" -eq 0 ]]; then
  echo "No eligible instruments found in table instruments" >&2
  exit 1
fi

echo "Found ${instrument_count} instruments. Generating SQL ${FROM_YEAR}..${TO_YEAR}" >&2

for ((year = FROM_YEAR; year <= TO_YEAR; year++)); do
  raw_file="$tmp_dir/raw_${year}.tsv"
  dedup_file="$tmp_dir/dedup_${year}.tsv"
  sql_file="${OUT_DIR}/prices_${year}.sql"

  : >"$raw_file"

  while IFS=$'\t' read -r request_ticker market db_ticker; do
    [[ -z "$request_ticker" || -z "$market" || -z "$db_ticker" ]] && continue
    fetch_ticker_year "$request_ticker" "$market" "$db_ticker" "$year" "$raw_file"
  done <"$instruments_file"

  awk -F $'\t' 'NF >= 3 && !seen[$1 FS $2]++ { print }' "$raw_file" >"$dedup_file"

  write_year_sql "$year" "$dedup_file" "$sql_file"

  year_rows="$(wc -l <"$dedup_file" | tr -d '[:space:]')"
  echo "Generated ${sql_file} (${year_rows} rows)" >&2
done

echo "Done." >&2
