#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Generate SQL updates that replace BBG-like ISIN values with real ISINs from official MOEX ISS.

Usage:
  DATABASE_URL=... ./scripts/moex_history/generate_moex_bbg_isin_fix_sql.sh [options]

Options:
  --out-file <path>    Output SQL file
  --limit <N>          Limit number of instruments to probe
  --sleep-ms <N>       Sleep between HTTP calls in milliseconds (default: 0)
  --help               Show this message
USAGE
}

require_bin() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "Missing required binary: $name" >&2
    exit 1
  fi
}

validate_isin() {
  local value="$1"
  [[ "$value" =~ ^[A-Z]{2}[A-Z0-9]{9}[0-9]$ ]]
}

OUT_FILE=""
LIMIT=""
SLEEP_MS=0

while [[ $# -gt 0 ]]; do
  case "$1" in
    --out-file)
      OUT_FILE="${2:-}"
      shift 2
      ;;
    --limit)
      LIMIT="${2:-}"
      shift 2
      ;;
    --sleep-ms)
      SLEEP_MS="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required" >&2
  exit 1
fi

if [[ -z "$OUT_FILE" ]]; then
  echo "--out-file is required" >&2
  exit 1
fi

require_bin psql
require_bin curl
require_bin jq

if [[ -n "$LIMIT" ]] && [[ ! "$LIMIT" =~ ^[0-9]+$ ]]; then
  echo "Invalid --limit: $LIMIT" >&2
  exit 1
fi

if [[ ! "$SLEEP_MS" =~ ^[0-9]+$ ]]; then
  echo "Invalid --sleep-ms: $SLEEP_MS" >&2
  exit 1
fi

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

tickers_file="$tmp_dir/tickers.tsv"
updates_file="$tmp_dir/updates.tsv"

limit_clause=""
if [[ -n "$LIMIT" ]]; then
  limit_clause="limit ${LIMIT}"
fi

psql "$DATABASE_URL" -X -A -F $'\t' -v ON_ERROR_STOP=1 -c "
select upper(ticker), upper(isin)
from instruments
where isin ~ '^BBG'
  and ticker is not null
  and btrim(ticker) <> ''
  and upper(ticker) !~ '^[0-9]+$'
order by ticker
${limit_clause};
" >"$tickers_file"

while IFS=$'\t' read -r ticker current_isin; do
  [[ -z "$ticker" || -z "$current_isin" ]] && continue

  if ! response="$(curl -fsS "https://iss.moex.com/iss/securities/${ticker}.json?iss.meta=off&iss.only=description")"; then
    continue
  fi

  isin="$(jq -r '
    .description as $d
    | ($d.columns | index("name")) as $name_idx
    | ($d.columns | index("value")) as $value_idx
    | ($d.data // [])[]
    | select(.[$name_idx] == "ISIN")
    | .[$value_idx] // empty
  ' <<<"$response" | tr '[:lower:]' '[:upper:]' | head -n 1)"

  if validate_isin "$isin" && [[ "$isin" != "$current_isin" ]]; then
    printf '%s\t%s\t%s\n' "$ticker" "$current_isin" "$isin" >>"$updates_file"
  fi

  if [[ "$SLEEP_MS" -gt 0 ]]; then
    perl -e "select(undef, undef, undef, ${SLEEP_MS}/1000)"
  fi
done <"$tickers_file"

rows_count=0
if [[ -f "$updates_file" ]]; then
  rows_count="$(wc -l <"$updates_file" | tr -d '[:space:]')"
fi

{
  echo "-- Generated by scripts/moex_history/generate_moex_bbg_isin_fix_sql.sh"
  echo "-- Source: official MOEX ISS description endpoint"
  echo "-- Rows: ${rows_count}"
  echo
  echo "BEGIN;"

  if [[ "$rows_count" -gt 0 ]]; then
    awk -F $'\t' '
      {
        printf "UPDATE instruments dst SET isin = \047%s\047 WHERE upper(dst.ticker) = \047%s\047 AND upper(dst.isin) = \047%s\047 AND NOT EXISTS (SELECT 1 FROM instruments other WHERE upper(other.isin) = \047%s\047 AND upper(other.ticker) <> \047%s\047);\n", $3, $1, $2, $3, $1
      }
    ' "$updates_file"
  fi

  echo "COMMIT;"
} >"$OUT_FILE"

echo "Generated ${rows_count} updates into ${OUT_FILE}" >&2
