#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Apply yearly SQL files generated by scripts/tbank_history/generate_prices_sql.sh.

Usage:
  DATABASE_URL=... ./scripts/tbank_history/apply_prices_sql.sh [options]

Options:
  --from-year <YYYY>   First year to apply (default: 2018)
  --to-year <YYYY>     Last year to apply (default: current year)
  --sql-dir <path>     Directory with prices_<year>.sql files
  --help               Show this message
USAGE
}

normalize_year() {
  local value="$1"
  if [[ ! "$value" =~ ^[0-9]{4}$ ]]; then
    echo "Invalid year: $value" >&2
    exit 1
  fi
  echo "$value"
}

FROM_YEAR=2018
TO_YEAR="$(date +%Y)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SQL_DIR="${SCRIPT_DIR}/sql"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-year)
      FROM_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --to-year)
      TO_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --sql-dir)
      SQL_DIR="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required" >&2
  exit 1
fi

if (( FROM_YEAR > TO_YEAR )); then
  echo "from-year must be <= to-year" >&2
  exit 1
fi

if ! command -v psql >/dev/null 2>&1; then
  echo "Missing required binary: psql" >&2
  exit 1
fi

for ((year = FROM_YEAR; year <= TO_YEAR; year++)); do
  shopt -s nullglob
  sql_files=("${SQL_DIR}/prices_${year}.sql" "${SQL_DIR}/prices_${year}_"*.sql)
  shopt -u nullglob

  if [[ "${#sql_files[@]}" -eq 0 ]]; then
    echo "Skip ${year}: no files found for prices_${year}*.sql in ${SQL_DIR}" >&2
    continue
  fi

  for sql_file in "${sql_files[@]}"; do
    [[ -f "$sql_file" ]] || continue
    echo "Applying ${sql_file}" >&2
    psql "$DATABASE_URL" -v ON_ERROR_STOP=1 -f "$sql_file"
  done
done

echo "Done." >&2
