#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'USAGE'
Generate yearly SQL INSERT scripts with historical prices from T-Bank Invest API.

Usage:
  DATABASE_URL=... TINVEST_TOKEN=... ./scripts/tbank_history/generate_prices_sql.sh [options]

Options:
  --from-year <YYYY>   First year to generate (default: 2018)
  --to-year <YYYY>     Last year to generate (default: current year)
  --out-dir <path>     Output directory for prices_<year>.sql
  --provider <name>    Provider value for prices.provider (default: TBANK)
  --base-url <url>     GetCandles endpoint URL
  --help               Show this message
USAGE
}

require_bin() {
  local name="$1"
  if ! command -v "$name" >/dev/null 2>&1; then
    echo "Missing required binary: $name" >&2
    exit 1
  fi
}

normalize_year() {
  local value="$1"
  if [[ ! "$value" =~ ^[0-9]{4}$ ]]; then
    echo "Invalid year: $value" >&2
    exit 1
  fi
  echo "$value"
}

fetch_figi_year() {
  local figi="$1"
  local year="$2"
  local output_file="$3"

  local from_dt="${year}-01-01T00:00:00Z"
  local to_dt="${year}-12-31T23:59:59Z"

  local payload
  payload="$(cat <<JSON
{
  "from": "${from_dt}",
  "to": "${to_dt}",
  "interval": "CANDLE_INTERVAL_DAY",
  "instrumentId": "${figi}",
  "limit": 2400,
  "candleSourceType": "CANDLE_SOURCE_EXCHANGE"
}
JSON
)"

  local response
  if ! response="$(curl -fsS --retry 2 --retry-delay 1 \
      -H "Authorization: Bearer ${TINVEST_TOKEN}" \
      -H "Content-Type: application/json" \
      -d "$payload" \
      "$BASE_URL")"; then
    echo "WARN: request failed for figi=${figi}, year=${year}" >&2
    return
  fi

  local parsed
  parsed="$(jq -r --arg figi "$figi" '
    (.candles // [])[]
    | select(.time != null and .close != null)
    | (.time | tostring) as $time
    | select($time | test("^[0-9]{4}-[0-9]{2}-[0-9]{2}"))
    | ($time[0:10]) as $date
    | ((.close.units // "0") | tonumber) as $units
    | ((.close.nano // 0) | tonumber) as $nano
    | ($units + ($nano / 1000000000)) as $price
    | select($price > 0)
    | [$figi, $date, ($price | tostring)] | @tsv
  ' <<<"$response")"

  if [[ -n "$parsed" ]]; then
    printf '%s\n' "$parsed" >>"$output_file"
  fi
}

write_year_sql() {
  local year="$1"
  local rows_file="$2"
  local sql_file="$3"

  local rows_count
  rows_count="$(wc -l <"$rows_file" | tr -d '[:space:]')"

  {
    echo "-- Generated by scripts/tbank_history/generate_prices_sql.sh"
    echo "-- Year: ${year}"
    echo "-- Provider: ${PROVIDER}"
    echo "-- Rows: ${rows_count}"
    echo ""

    if [[ "$rows_count" -eq 0 ]]; then
      echo "BEGIN;"
      echo "COMMIT;"
      echo "-- No T-Bank history rows found for this year."
      return
    fi

    echo "BEGIN;"
    echo "WITH src (figi, trade_date, price) AS ("
    echo "    VALUES"

    awk -F $'\t' -v total="$rows_count" '
      {
        figi = $1
        gsub(/\047/, "\047\047", figi)
        price = $3
        gsub(/,/, ".", price)
        suffix = (NR < total ? "," : "")
        printf "    (\047%s\047, DATE \047%s\047, %s)%s\n", figi, $2, price, suffix
      }
    ' "$rows_file"

    cat <<SQL_TAIL
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|${PROVIDER}') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.figi) = s.figi
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    '${PROVIDER}',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
SQL_TAIL
  } >"$sql_file"
}

FROM_YEAR=2018
TO_YEAR="$(date +%Y)"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
OUT_DIR="${SCRIPT_DIR}/sql"
PROVIDER="TBANK"
BASE_URL="https://invest-public-api.tbank.ru/rest/tinkoff.public.invest.api.contract.v1.MarketDataService/GetCandles"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --from-year)
      FROM_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --to-year)
      TO_YEAR="$(normalize_year "${2:-}")"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="${2:-}"
      shift 2
      ;;
    --provider)
      PROVIDER="${2:-}"
      shift 2
      ;;
    --base-url)
      BASE_URL="${2:-}"
      shift 2
      ;;
    --help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown argument: $1" >&2
      usage
      exit 1
      ;;
  esac
done

if [[ -z "${DATABASE_URL:-}" ]]; then
  echo "DATABASE_URL is required" >&2
  exit 1
fi

if [[ -z "${TINVEST_TOKEN:-}" ]]; then
  echo "TINVEST_TOKEN is required" >&2
  exit 1
fi

if [[ ! "$PROVIDER" =~ ^[A-Za-z0-9_-]{1,50}$ ]]; then
  echo "Invalid provider. Allowed: letters, numbers, underscore, dash (max 50)." >&2
  exit 1
fi
PROVIDER="$(printf '%s' "$PROVIDER" | tr '[:lower:]' '[:upper:]')"

if (( FROM_YEAR > TO_YEAR )); then
  echo "from-year must be <= to-year" >&2
  exit 1
fi

require_bin curl
require_bin jq
require_bin psql
require_bin awk
require_bin mktemp

mkdir -p "$OUT_DIR"

tmp_dir="$(mktemp -d)"
trap 'rm -rf "$tmp_dir"' EXIT

figi_file="$tmp_dir/figi.tsv"

psql "$DATABASE_URL" -X -A -t -F $'\t' -v ON_ERROR_STOP=1 -c "
select distinct upper(trim(figi))
from instruments
where figi is not null
  and btrim(figi) <> ''
  and type in (1, 2, 3)
order by 1;
" >"$figi_file"

figi_count="$(wc -l <"$figi_file" | tr -d '[:space:]')"
if [[ "$figi_count" -eq 0 ]]; then
  echo "No eligible FIGI found in table instruments" >&2
  exit 1
fi

echo "Found ${figi_count} FIGI values. Generating SQL ${FROM_YEAR}..${TO_YEAR}" >&2

for ((year = FROM_YEAR; year <= TO_YEAR; year++)); do
  raw_file="$tmp_dir/raw_${year}.tsv"
  dedup_file="$tmp_dir/dedup_${year}.tsv"
  sql_file="${OUT_DIR}/prices_${year}.sql"

  : >"$raw_file"

  while IFS=$'\t' read -r figi; do
    [[ -z "$figi" ]] && continue
    fetch_figi_year "$figi" "$year" "$raw_file"
  done <"$figi_file"

  awk -F $'\t' 'NF >= 3 && !seen[$1 FS $2]++ { print $1 "\t" $2 "\t" $3 }' "$raw_file" >"$dedup_file"

  write_year_sql "$year" "$dedup_file" "$sql_file"

  year_rows="$(wc -l <"$dedup_file" | tr -d '[:space:]')"
  echo "Generated ${sql_file} (${year_rows} rows)" >&2
done

echo "Done." >&2
