version: '3.4'

services:
  larchikdb:
    container_name: larchikdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=larchik
    restart: always
    ports:
      - "55432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  larchik.api:
    container_name: larchik.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - TokenKey=${TokenKey}
      - "ConnectionStrings__DefaultConnection=Server=larchikdb;Port=5432;UserId=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=larchik;"
    restart: always
    depends_on:
      - larchikdb
    ports:
      - "8001:80"
    volumes:
    - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  larchik.app:
    container_name: larchik.app
    environment:
      - REACT_APP_API_URL=/api/v1
    restart: always
    depends_on:
      - larchik.api
    ports:
      - "3000:3000"
    volumes:
      - ./:/larchik.app
    command: npm start
  
  larchik.proxy:
    container_name: larchik.proxy
    restart: always
    depends_on:
      - larchik.app
      - larchik.api
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  larchik.pgadmin:
    container_name: larchik.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/root/.pgadmin
    