version: '3.4'

services:
  larchik.api:
    image: ${DOCKER_REGISTRY-}larchikapi
    build:
      context: .
      dockerfile: Larchik.API/Dockerfile
  
  larchik.app:
    container_name: larchik.app_container
    build:
      dockerfile: client-app/Dockerfile
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/larchik.app
    command: npm start
