version: '3.4'

services:
  larchikdb:
    image: postgres

  larchik.api:
    image: ${DOCKER_REGISTRY-}larchikapi
    build:
      context: .
      dockerfile: Larchik.API/Dockerfile
  
  larchik.app:
    image: larchikapp
    build:
      dockerfile: client-app/Dockerfile
      context: .
  
  proxy:
    image: nginx

volumes:
  postgres_data:
