version: '3.4'

services:
  larchik.api:
    container_name: larchik.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  # larchki.app:
  #   container_name: larchik.app_container
  #   ports:
  #     - "3000:3000"
  #   volumes:
  #     - .:/client-app
  #   command: npm start
    