version: '3.4'

services:
  larchikdb:
    image: postgres
    container_name: larchikdb
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=larchik
    restart: always
    ports:
      - "5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  larchik.api:
    image: infernalred/larchikapi
    build: .
    container_name: larchik.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - TokenKey=${TokenKey}
      - "ConnectionStrings__DefaultConnection=Server=larchikdb;Port=5432;UserId=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};Database=larchik;"
      - "MarketSettings__Token=${MARKET_TOKEN}"
      - "MarketSettings__BaseAddress=${MARKET_BASE_ADDRESS}"
      - "CbrSettings__Address=http://www.cbr.ru/scripts/XML_daily.asp"
    restart: always
    depends_on:
      - larchikdb
    ports:
      - "80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  larchik.app:
    image: infernalred/larchikapp
    build: .
    container_name: larchik.app
    environment:
      - REACT_APP_API_URL=/api/v1
      - WDS_SOCKET_PORT=443
    restart: always
    depends_on:
      - larchik.api
    ports:
      - "3000"
    volumes:
      - ./:/larchik.app
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    command: npm start
  
  proxy:
    image: nginx
    container_name: larchik.proxy
    restart: always
    depends_on:
      - larchik.app
      - larchik.api
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./fullchain.pem:/etc/nginx/fullchain.pem
      - ./privkey.pem:/etc/nginx/privkey.pem
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
  
  pgadmin:
    image: dpage/pgadmin4
    container_name: larchik.pgadmin
    environment:
      - PGADMIN_DEFAULT_EMAIL=${PGADMIN_DEFAULT_EMAIL}
      - PGADMIN_DEFAULT_PASSWORD=${PGADMIN_DEFAULT_PASSWORD}
    restart: always
    depends_on:
      - nginx
    ports:
      - "5050:80"
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - pgadmin_data:/root/.pgadmin
  

volumes:
  postgres_data:
  pgadmin_data:
