-- Generated by scripts/tbank_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: TBANK
-- Rows: 49

BEGIN;
WITH src (figi, trade_date, price) AS (
    VALUES
    ('BBG000QCW561', DATE '2026-01-02', 52.7),
    ('BBG000QCW561', DATE '2026-01-05', 52.24),
    ('BBG000QCW561', DATE '2026-01-06', 52.97),
    ('BBG000QCW561', DATE '2026-01-07', 52.4),
    ('BBG000QCW561', DATE '2026-01-08', 52),
    ('BBG000QCW561', DATE '2026-01-09', 52.04),
    ('BBG000QCW561', DATE '2026-01-12', 52),
    ('BBG000QCW561', DATE '2026-01-13', 53.42),
    ('BBG000QCW561', DATE '2026-01-14', 54.08),
    ('BBG000QCW561', DATE '2026-01-15', 54.61),
    ('BBG000QCW561', DATE '2026-01-16', 54.5),
    ('BBG000QCW561', DATE '2026-01-20', 54.02),
    ('BBG000QCW561', DATE '2026-01-21', 54.1),
    ('BBG000QCW561', DATE '2026-01-22', 55.28),
    ('BBG000QCW561', DATE '2026-01-23', 54.04),
    ('BBG000QCW561', DATE '2026-01-26', 53.94),
    ('BBG000QCW561', DATE '2026-01-27', 54.11),
    ('BBG000QCW561', DATE '2026-01-28', 54.07),
    ('BBG000QCW561', DATE '2026-01-29', 55.72),
    ('BBG000QCW561', DATE '2026-01-30', 54.64),
    ('BBG000QCW561', DATE '2026-02-02', 53.38),
    ('BBG000QCW561', DATE '2026-02-03', 53.07),
    ('BBG000QCW561', DATE '2026-02-04', 52.97),
    ('BBG000QCW561', DATE '2026-02-05', 52.03),
    ('BBG000QCW561', DATE '2026-02-06', 52.62),
    ('BBG000QCW561', DATE '2026-02-09', 53.6),
    ('BBG000QCW561', DATE '2026-02-10', 54.09),
    ('BBG000QCW561', DATE '2026-02-11', 55.5),
    ('BBG000QCW561', DATE '2026-02-12', 53.26),
    ('BBG000QCW561', DATE '2026-02-13', 52.45),
    ('BBG000QCW561', DATE '2026-02-17', 52.5),
    ('BBG000QCW561', DATE '2026-02-18', 54.77),
    ('BBG000QCW561', DATE '2026-02-19', 55.59),
    ('BBG000QCW561', DATE '2026-02-20', 56.24),
    ('BBG000QCW561', DATE '2026-02-23', 55.58),
    ('BBG000QCW561', DATE '2026-02-24', 55.67),
    ('BBG000QCW561', DATE '2026-02-25', 56.39),
    ('BBG000QCW561', DATE '2026-02-26', 55.44),
    ('BBG000QCW561', DATE '2026-02-27', 55.89),
    ('BBG000QCW561', DATE '2026-03-02', 56.04),
    ('BBG000QCW561', DATE '2026-03-03', 53.06),
    ('BBG000QCW561', DATE '2026-03-04', 54.73),
    ('BBG000QCW561', DATE '2026-03-05', 53.18),
    ('BBG000QCW561', DATE '2026-03-06', 54),
    ('BBG000QCW561', DATE '2026-03-09', 53.05),
    ('BBG000QCW561', DATE '2026-03-10', 53.05),
    ('BBG000QCW561', DATE '2026-03-11', 53.28),
    ('BBG000QCW561', DATE '2026-03-12', 44.31),
    ('BBG000QCW561', DATE '2026-03-13', 49.59)
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|TBANK') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.figi) = s.figi
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'TBANK',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
