-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2025
-- Provider: MOEX
-- Rows: 47

BEGIN;
WITH src (ticker, trade_date, price) AS (
    VALUES
    ('RU000A105XF4', DATE '2025-01-03', 98.64),
    ('RU000A105XF4', DATE '2025-01-06', 98.58),
    ('RU000A105XF4', DATE '2025-01-08', 98.44),
    ('RU000A105XF4', DATE '2025-01-09', 98.49),
    ('RU000A105XF4', DATE '2025-01-10', 98.53),
    ('RU000A105XF4', DATE '2025-01-13', 98.75),
    ('RU000A105XF4', DATE '2025-01-14', 98.7),
    ('RU000A105XF4', DATE '2025-01-15', 98.67),
    ('RU000A105XF4', DATE '2025-01-16', 98.52),
    ('RU000A105XF4', DATE '2025-01-17', 98.4),
    ('RU000A105XF4', DATE '2025-01-20', 98.48),
    ('RU000A105XF4', DATE '2025-01-21', 98.4),
    ('RU000A105XF4', DATE '2025-01-22', 98.57),
    ('RU000A105XF4', DATE '2025-01-23', 98.21),
    ('RU000A105XF4', DATE '2025-01-24', 98.5),
    ('RU000A105XF4', DATE '2025-01-27', 98.65),
    ('RU000A105XF4', DATE '2025-01-28', 98.57),
    ('RU000A105XF4', DATE '2025-01-29', 98.63),
    ('RU000A105XF4', DATE '2025-01-30', 98.8),
    ('RU000A105XF4', DATE '2025-01-31', 98.88),
    ('RU000A105XF4', DATE '2025-02-03', 98.89),
    ('RU000A105XF4', DATE '2025-02-04', 98.95),
    ('RU000A105XF4', DATE '2025-02-05', 98.84),
    ('RU000A105XF4', DATE '2025-02-06', 99.03),
    ('RU000A105XF4', DATE '2025-02-07', 98.99),
    ('RU000A105XF4', DATE '2025-02-10', 99.1),
    ('RU000A105XF4', DATE '2025-02-11', 99.14),
    ('RU000A105XF4', DATE '2025-02-12', 99.29),
    ('RU000A105XF4', DATE '2025-02-13', 99.15),
    ('RU000A105XF4', DATE '2025-02-14', 99.44),
    ('RU000A105XF4', DATE '2025-02-17', 99.43),
    ('RU000A105XF4', DATE '2025-02-18', 99.5),
    ('RU000A105XF4', DATE '2025-02-19', 99.65),
    ('RU000A105XF4', DATE '2025-02-20', 99.44),
    ('RU000A105XF4', DATE '2025-02-21', 99.61),
    ('RU000A105XF4', DATE '2025-02-24', 99.38),
    ('RU000A105XF4', DATE '2025-02-25', 99.53),
    ('RU000A105XF4', DATE '2025-02-26', 99.61),
    ('RU000A105XF4', DATE '2025-02-27', 99.76),
    ('RU000A105XF4', DATE '2025-02-28', 99.71),
    ('RU000A105XF4', DATE '2025-03-03', 99.65),
    ('RU000A105XF4', DATE '2025-03-04', 99.75),
    ('RU000A105XF4', DATE '2025-03-05', 99.82),
    ('RU000A105XF4', DATE '2025-03-06', 99.9),
    ('RU000A105XF4', DATE '2025-03-07', 99.99),
    ('RU000A105XF4', DATE '2025-03-10', 99.99),
    ('RU000A105XF4', DATE '2025-03-11', 99.99)
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|MOEX') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.ticker) = s.ticker
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'MOEX',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
