-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2024
-- Provider: MOEX
-- Rows: 188

BEGIN;
WITH src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest) AS (
    VALUES
    ('RU000A100YD8', DATE '2024-01-03', 100.98, 'SUR', 3330, 'RUB', 4.11),
    ('RU000A100YD8', DATE '2024-01-04', 100.14, 'SUR', 3330, 'RUB', 5.47),
    ('RU000A100YD8', DATE '2024-01-05', 99.77, 'SUR', 3330, 'RUB', 6.84),
    ('RU000A100YD8', DATE '2024-01-08', 100.52, 'SUR', 3330, 'RUB', 10.95),
    ('RU000A100YD8', DATE '2024-01-09', 100.01, 'SUR', 3330, 'RUB', 12.32),
    ('RU000A100YD8', DATE '2024-01-10', 100.33, 'SUR', 3330, 'RUB', 13.68),
    ('RU000A100YD8', DATE '2024-01-11', 100.61, 'SUR', 3330, 'RUB', 15.05),
    ('RU000A100YD8', DATE '2024-01-12', 100.54, 'SUR', 3330, 'RUB', 16.42),
    ('RU000A100YD8', DATE '2024-01-15', 100.43, 'SUR', 3330, 'RUB', 20.53),
    ('RU000A100YD8', DATE '2024-01-16', 100.37, 'SUR', 3330, 'RUB', 21.9),
    ('RU000A100YD8', DATE '2024-01-17', 100.57, 'SUR', 3330, 'RUB', 23.26),
    ('RU000A100YD8', DATE '2024-01-18', 100.16, 'SUR', 3330, 'RUB', 24.63),
    ('RU000A100YD8', DATE '2024-01-19', 99.87, 'SUR', 3330, 'RUB', 26),
    ('RU000A100YD8', DATE '2024-01-22', 100.09, 'SUR', 3330, 'RUB', 30.11),
    ('RU000A100YD8', DATE '2024-01-23', 100.51, 'SUR', 3330, 'RUB', 31.48),
    ('RU000A100YD8', DATE '2024-01-24', 100.05, 'SUR', 3330, 'RUB', 32.84),
    ('RU000A100YD8', DATE '2024-01-25', 99.95, 'SUR', 3330, 'RUB', 34.21),
    ('RU000A100YD8', DATE '2024-01-26', 100.23, 'SUR', 3330, 'RUB', 35.58),
    ('RU000A100YD8', DATE '2024-01-29', 100.09, 'SUR', 3330, 'RUB', 39.69),
    ('RU000A100YD8', DATE '2024-01-30', 100.19, 'SUR', 3330, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-01-31', 100.02, 'SUR', 3330, 'RUB', 1.37),
    ('RU000A100YD8', DATE '2024-02-01', 99.98, 'SUR', 3330, 'RUB', 2.74),
    ('RU000A100YD8', DATE '2024-02-02', 99.98, 'SUR', 3330, 'RUB', 4.11),
    ('RU000A100YD8', DATE '2024-02-05', 99.68, 'SUR', 3330, 'RUB', 8.21),
    ('RU000A100YD8', DATE '2024-02-06', 99.87, 'SUR', 3330, 'RUB', 9.58),
    ('RU000A100YD8', DATE '2024-02-07', 99.92, 'SUR', 3330, 'RUB', 10.95),
    ('RU000A100YD8', DATE '2024-02-08', 99.56, 'SUR', 3330, 'RUB', 12.32),
    ('RU000A100YD8', DATE '2024-02-09', 99.92, 'SUR', 3330, 'RUB', 13.68),
    ('RU000A100YD8', DATE '2024-02-12', 100.42, 'SUR', 3330, 'RUB', 17.79),
    ('RU000A100YD8', DATE '2024-02-13', 99.87, 'SUR', 3330, 'RUB', 19.16),
    ('RU000A100YD8', DATE '2024-02-14', 99.99, 'SUR', 3330, 'RUB', 20.53),
    ('RU000A100YD8', DATE '2024-02-15', 100.08, 'SUR', 3330, 'RUB', 21.9),
    ('RU000A100YD8', DATE '2024-02-16', 100.08, 'SUR', 3330, 'RUB', 23.26),
    ('RU000A100YD8', DATE '2024-02-19', 99.88, 'SUR', 3330, 'RUB', 27.37),
    ('RU000A100YD8', DATE '2024-02-20', 99.98, 'SUR', 3330, 'RUB', 28.74),
    ('RU000A100YD8', DATE '2024-02-21', 100.02, 'SUR', 3330, 'RUB', 30.11),
    ('RU000A100YD8', DATE '2024-02-22', 99.97, 'SUR', 3330, 'RUB', 31.48),
    ('RU000A100YD8', DATE '2024-02-26', 100.04, 'SUR', 3330, 'RUB', 36.95),
    ('RU000A100YD8', DATE '2024-02-27', 100.01, 'SUR', 3330, 'RUB', 38.32),
    ('RU000A100YD8', DATE '2024-02-28', 99.95, 'SUR', 3330, 'RUB', 39.69),
    ('RU000A100YD8', DATE '2024-02-29', 99.92, 'SUR', 3330, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-03-01', 99.98, 'SUR', 3330, 'RUB', 1.37),
    ('RU000A100YD8', DATE '2024-03-04', 99.95, 'SUR', 3330, 'RUB', 5.47),
    ('RU000A100YD8', DATE '2024-03-05', 99.68, 'SUR', 3330, 'RUB', 6.84),
    ('RU000A100YD8', DATE '2024-03-06', 99.88, 'SUR', 3330, 'RUB', 8.21),
    ('RU000A100YD8', DATE '2024-03-07', 99.89, 'SUR', 3330, 'RUB', 9.58),
    ('RU000A100YD8', DATE '2024-03-11', 99.91, 'SUR', 3330, 'RUB', 15.05),
    ('RU000A100YD8', DATE '2024-03-12', 99.99, 'SUR', 3330, 'RUB', 16.42),
    ('RU000A100YD8', DATE '2024-03-13', 99.96, 'SUR', 3330, 'RUB', 17.79),
    ('RU000A100YD8', DATE '2024-03-14', 99.95, 'SUR', 3330, 'RUB', 19.16),
    ('RU000A100YD8', DATE '2024-03-15', 99.91, 'SUR', 3330, 'RUB', 20.53),
    ('RU000A100YD8', DATE '2024-03-18', 99.81, 'SUR', 3330, 'RUB', 24.63),
    ('RU000A100YD8', DATE '2024-03-19', 99.8, 'SUR', 3330, 'RUB', 26),
    ('RU000A100YD8', DATE '2024-03-20', 99.6, 'SUR', 3330, 'RUB', 27.37),
    ('RU000A100YD8', DATE '2024-03-21', 99.81, 'SUR', 3330, 'RUB', 28.74),
    ('RU000A100YD8', DATE '2024-03-22', 99.48, 'SUR', 3330, 'RUB', 30.11),
    ('RU000A100YD8', DATE '2024-03-25', 99.37, 'SUR', 3330, 'RUB', 34.21),
    ('RU000A100YD8', DATE '2024-03-26', 99.96, 'SUR', 3330, 'RUB', 35.58),
    ('RU000A100YD8', DATE '2024-03-27', 99.99, 'SUR', 3330, 'RUB', 36.95),
    ('RU000A100YD8', DATE '2024-03-28', 100, 'SUR', 3330, 'RUB', 38.32),
    ('RU000A100YD8', DATE '2024-03-29', 99.98, 'SUR', 3330, 'RUB', 39.69),
    ('RU000A100YD8', DATE '2024-04-01', 99.64, 'SUR', 2663, 'RUB', 2.19),
    ('RU000A100YD8', DATE '2024-04-02', 100.03, 'SUR', 2663, 'RUB', 3.28),
    ('RU000A100YD8', DATE '2024-04-03', 99.96, 'SUR', 2663, 'RUB', 4.38),
    ('RU000A100YD8', DATE '2024-04-04', 100.04, 'SUR', 2663, 'RUB', 5.47),
    ('RU000A100YD8', DATE '2024-04-05', 100.16, 'SUR', 2663, 'RUB', 6.57),
    ('RU000A100YD8', DATE '2024-04-08', 99.51, 'SUR', 2663, 'RUB', 9.85),
    ('RU000A100YD8', DATE '2024-04-09', 99.68, 'SUR', 2663, 'RUB', 10.94),
    ('RU000A100YD8', DATE '2024-04-10', 99.82, 'SUR', 2663, 'RUB', 12.04),
    ('RU000A100YD8', DATE '2024-04-11', 99.82, 'SUR', 2663, 'RUB', 13.13),
    ('RU000A100YD8', DATE '2024-04-12', 99.85, 'SUR', 2663, 'RUB', 14.23),
    ('RU000A100YD8', DATE '2024-04-15', 100, 'SUR', 2663, 'RUB', 17.51),
    ('RU000A100YD8', DATE '2024-04-16', 99.88, 'SUR', 2663, 'RUB', 18.6),
    ('RU000A100YD8', DATE '2024-04-17', 99.79, 'SUR', 2663, 'RUB', 19.7),
    ('RU000A100YD8', DATE '2024-04-18', 99.81, 'SUR', 2663, 'RUB', 20.79),
    ('RU000A100YD8', DATE '2024-04-19', 99.85, 'SUR', 2663, 'RUB', 21.89),
    ('RU000A100YD8', DATE '2024-04-22', 99.94, 'SUR', 2663, 'RUB', 25.17),
    ('RU000A100YD8', DATE '2024-04-23', 99.8, 'SUR', 2663, 'RUB', 26.27),
    ('RU000A100YD8', DATE '2024-04-24', 99.68, 'SUR', 2663, 'RUB', 27.36),
    ('RU000A100YD8', DATE '2024-04-25', 99.88, 'SUR', 2663, 'RUB', 28.45),
    ('RU000A100YD8', DATE '2024-04-26', 99.78, 'SUR', 2663, 'RUB', 29.55),
    ('RU000A100YD8', DATE '2024-04-27', 99.8, 'SUR', 2663, 'RUB', 30.64),
    ('RU000A100YD8', DATE '2024-04-29', 100.07, 'SUR', 2663, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-04-30', 99.82, 'SUR', 2663, 'RUB', 1.09),
    ('RU000A100YD8', DATE '2024-05-02', 99.79, 'SUR', 2663, 'RUB', 3.28),
    ('RU000A100YD8', DATE '2024-05-03', 99.75, 'SUR', 2663, 'RUB', 4.38),
    ('RU000A100YD8', DATE '2024-05-06', 99.69, 'SUR', 2663, 'RUB', 7.66),
    ('RU000A100YD8', DATE '2024-05-07', 99.99, 'SUR', 2663, 'RUB', 8.76),
    ('RU000A100YD8', DATE '2024-05-08', 99.71, 'SUR', 2663, 'RUB', 9.85),
    ('RU000A100YD8', DATE '2024-05-10', 99.82, 'SUR', 2663, 'RUB', 12.04),
    ('RU000A100YD8', DATE '2024-05-13', 99.76, 'SUR', 2663, 'RUB', 15.32),
    ('RU000A100YD8', DATE '2024-05-14', 99.78, 'SUR', 2663, 'RUB', 16.42),
    ('RU000A100YD8', DATE '2024-05-15', 99.9, 'SUR', 2663, 'RUB', 17.51),
    ('RU000A100YD8', DATE '2024-05-16', 99.78, 'SUR', 2663, 'RUB', 18.6),
    ('RU000A100YD8', DATE '2024-05-17', 99.66, 'SUR', 2663, 'RUB', 19.7),
    ('RU000A100YD8', DATE '2024-05-20', 99.66, 'SUR', 2663, 'RUB', 22.98),
    ('RU000A100YD8', DATE '2024-05-21', 99.88, 'SUR', 2663, 'RUB', 24.08),
    ('RU000A100YD8', DATE '2024-05-22', 100.04, 'SUR', 2663, 'RUB', 25.17),
    ('RU000A100YD8', DATE '2024-05-23', 99.63, 'SUR', 2663, 'RUB', 26.27),
    ('RU000A100YD8', DATE '2024-05-24', 99.68, 'SUR', 2663, 'RUB', 27.36),
    ('RU000A100YD8', DATE '2024-05-27', 99.6, 'SUR', 2663, 'RUB', 30.64),
    ('RU000A100YD8', DATE '2024-05-28', 99.75, 'SUR', 2663, 'RUB', 31.74),
    ('RU000A100YD8', DATE '2024-05-29', 99.66, 'SUR', 2663, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-05-30', 99.65, 'SUR', 2663, 'RUB', 1.09),
    ('RU000A100YD8', DATE '2024-05-31', 99.49, 'SUR', 2663, 'RUB', 2.19),
    ('RU000A100YD8', DATE '2024-06-03', 99.47, 'SUR', 2663, 'RUB', 5.47),
    ('RU000A100YD8', DATE '2024-06-04', 99.7, 'SUR', 2663, 'RUB', 6.57),
    ('RU000A100YD8', DATE '2024-06-05', 99.91, 'SUR', 2663, 'RUB', 7.66),
    ('RU000A100YD8', DATE '2024-06-06', 99.9, 'SUR', 2663, 'RUB', 8.76),
    ('RU000A100YD8', DATE '2024-06-07', 99.84, 'SUR', 2663, 'RUB', 9.85),
    ('RU000A100YD8', DATE '2024-06-10', 99.81, 'SUR', 2663, 'RUB', 13.13),
    ('RU000A100YD8', DATE '2024-06-11', 99.81, 'SUR', 2663, 'RUB', 14.23),
    ('RU000A100YD8', DATE '2024-06-13', 99.99, 'SUR', 2663, 'RUB', 16.42),
    ('RU000A100YD8', DATE '2024-06-14', 100.06, 'SUR', 2663, 'RUB', 17.51),
    ('RU000A100YD8', DATE '2024-06-17', 99.9, 'SUR', 2663, 'RUB', 20.79),
    ('RU000A100YD8', DATE '2024-06-18', 100, 'SUR', 2663, 'RUB', 21.89),
    ('RU000A100YD8', DATE '2024-06-19', 99.56, 'SUR', 2663, 'RUB', 22.98),
    ('RU000A100YD8', DATE '2024-06-20', 99.39, 'SUR', 2663, 'RUB', 24.08),
    ('RU000A100YD8', DATE '2024-06-21', 99.21, 'SUR', 2663, 'RUB', 25.17),
    ('RU000A100YD8', DATE '2024-06-24', 99.38, 'SUR', 2663, 'RUB', 28.45),
    ('RU000A100YD8', DATE '2024-06-25', 99.81, 'SUR', 2663, 'RUB', 29.55),
    ('RU000A100YD8', DATE '2024-06-26', 99.43, 'SUR', 2663, 'RUB', 30.64),
    ('RU000A100YD8', DATE '2024-06-27', 100, 'SUR', 2663, 'RUB', 31.74),
    ('RU000A100YD8', DATE '2024-06-28', 99.96, 'SUR', 1996, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-07-01', 99.92, 'SUR', 1996, 'RUB', 2.46),
    ('RU000A100YD8', DATE '2024-07-02', 99.99, 'SUR', 1996, 'RUB', 3.28),
    ('RU000A100YD8', DATE '2024-07-03', 99.88, 'SUR', 1996, 'RUB', 4.1),
    ('RU000A100YD8', DATE '2024-07-04', 99.42, 'SUR', 1996, 'RUB', 4.92),
    ('RU000A100YD8', DATE '2024-07-05', 99.56, 'SUR', 1996, 'RUB', 5.74),
    ('RU000A100YD8', DATE '2024-07-08', 99.56, 'SUR', 1996, 'RUB', 8.2),
    ('RU000A100YD8', DATE '2024-07-09', 99.58, 'SUR', 1996, 'RUB', 9.02),
    ('RU000A100YD8', DATE '2024-07-10', 99.36, 'SUR', 1996, 'RUB', 9.84),
    ('RU000A100YD8', DATE '2024-07-11', 99.62, 'SUR', 1996, 'RUB', 10.66),
    ('RU000A100YD8', DATE '2024-07-12', 99.51, 'SUR', 1996, 'RUB', 11.48),
    ('RU000A100YD8', DATE '2024-07-15', 99.59, 'SUR', 1996, 'RUB', 13.94),
    ('RU000A100YD8', DATE '2024-07-16', 99.98, 'SUR', 1996, 'RUB', 14.76),
    ('RU000A100YD8', DATE '2024-07-17', 99.53, 'SUR', 1996, 'RUB', 15.59),
    ('RU000A100YD8', DATE '2024-07-18', 99.62, 'SUR', 1996, 'RUB', 16.41),
    ('RU000A100YD8', DATE '2024-07-19', 99.74, 'SUR', 1996, 'RUB', 17.23),
    ('RU000A100YD8', DATE '2024-07-22', 99.96, 'SUR', 1996, 'RUB', 19.69),
    ('RU000A100YD8', DATE '2024-07-23', 99.5, 'SUR', 1996, 'RUB', 20.51),
    ('RU000A100YD8', DATE '2024-07-24', 99.64, 'SUR', 1996, 'RUB', 21.33),
    ('RU000A100YD8', DATE '2024-07-25', 99.89, 'SUR', 1996, 'RUB', 22.15),
    ('RU000A100YD8', DATE '2024-07-26', 100.09, 'SUR', 1996, 'RUB', 22.97),
    ('RU000A100YD8', DATE '2024-07-29', 99.54, 'SUR', 1996, 'RUB', 0.82),
    ('RU000A100YD8', DATE '2024-07-30', 99.51, 'SUR', 1996, 'RUB', 1.64),
    ('RU000A100YD8', DATE '2024-07-31', 100, 'SUR', 1996, 'RUB', 2.46),
    ('RU000A100YD8', DATE '2024-08-01', 99.68, 'SUR', 1996, 'RUB', 3.28),
    ('RU000A100YD8', DATE '2024-08-02', 99.69, 'SUR', 1996, 'RUB', 4.1),
    ('RU000A100YD8', DATE '2024-08-05', 99.68, 'SUR', 1996, 'RUB', 6.56),
    ('RU000A100YD8', DATE '2024-08-06', 99.7, 'SUR', 1996, 'RUB', 7.38),
    ('RU000A100YD8', DATE '2024-08-07', 99.58, 'SUR', 1996, 'RUB', 8.2),
    ('RU000A100YD8', DATE '2024-08-08', 99.95, 'SUR', 1996, 'RUB', 9.02),
    ('RU000A100YD8', DATE '2024-08-09', 99.99, 'SUR', 1996, 'RUB', 9.84),
    ('RU000A100YD8', DATE '2024-08-12', 99.76, 'SUR', 1996, 'RUB', 12.3),
    ('RU000A100YD8', DATE '2024-08-13', 99.76, 'SUR', 1996, 'RUB', 13.12),
    ('RU000A100YD8', DATE '2024-08-14', 99.75, 'SUR', 1996, 'RUB', 13.94),
    ('RU000A100YD8', DATE '2024-08-15', 99.94, 'SUR', 1996, 'RUB', 14.76),
    ('RU000A100YD8', DATE '2024-08-16', 99.71, 'SUR', 1996, 'RUB', 15.59),
    ('RU000A100YD8', DATE '2024-08-19', 99.74, 'SUR', 1996, 'RUB', 18.05),
    ('RU000A100YD8', DATE '2024-08-20', 99.77, 'SUR', 1996, 'RUB', 18.87),
    ('RU000A100YD8', DATE '2024-08-21', 99.88, 'SUR', 1996, 'RUB', 19.69),
    ('RU000A100YD8', DATE '2024-08-22', 99.78, 'SUR', 1996, 'RUB', 20.51),
    ('RU000A100YD8', DATE '2024-08-23', 99.72, 'SUR', 1996, 'RUB', 21.33),
    ('RU000A100YD8', DATE '2024-08-26', 99.84, 'SUR', 1996, 'RUB', 23.79),
    ('RU000A100YD8', DATE '2024-08-27', 99.85, 'SUR', 1996, 'RUB', 0),
    ('RU000A100YD8', DATE '2024-08-28', 99.69, 'SUR', 1996, 'RUB', 0.82),
    ('RU000A100YD8', DATE '2024-08-29', 99.64, 'SUR', 1996, 'RUB', 1.64),
    ('RU000A100YD8', DATE '2024-08-30', 99.78, 'SUR', 1996, 'RUB', 2.46),
    ('RU000A100YD8', DATE '2024-09-02', 99.37, 'SUR', 1996, 'RUB', 4.92),
    ('RU000A100YD8', DATE '2024-09-03', 99.72, 'SUR', 1996, 'RUB', 5.74),
    ('RU000A100YD8', DATE '2024-09-04', 99.74, 'SUR', 1996, 'RUB', 6.56),
    ('RU000A100YD8', DATE '2024-09-05', 99.82, 'SUR', 1996, 'RUB', 7.38),
    ('RU000A100YD8', DATE '2024-09-06', 99.52, 'SUR', 1996, 'RUB', 8.2),
    ('RU000A100YD8', DATE '2024-09-09', 99.79, 'SUR', 1996, 'RUB', 10.66),
    ('RU000A100YD8', DATE '2024-09-10', 99.62, 'SUR', 1996, 'RUB', 11.48),
    ('RU000A100YD8', DATE '2024-09-11', 99.79, 'SUR', 1996, 'RUB', 12.3),
    ('RU000A100YD8', DATE '2024-09-12', 99.56, 'SUR', 1996, 'RUB', 13.12),
    ('RU000A100YD8', DATE '2024-09-13', 99.56, 'SUR', 1996, 'RUB', 13.94),
    ('RU000A100YD8', DATE '2024-09-16', 99.87, 'SUR', 1996, 'RUB', 16.41),
    ('RU000A100YD8', DATE '2024-09-17', 99.78, 'SUR', 1996, 'RUB', 17.23),
    ('RU000A100YD8', DATE '2024-09-18', 99.65, 'SUR', 1996, 'RUB', 18.05),
    ('RU000A100YD8', DATE '2024-09-19', 99.97, 'SUR', 1996, 'RUB', 18.87),
    ('RU000A100YD8', DATE '2024-09-20', 99.9, 'SUR', 1996, 'RUB', 19.69),
    ('RU000A100YD8', DATE '2024-09-23', 99.9, 'SUR', 1996, 'RUB', 22.15),
    ('RU000A100YD8', DATE '2024-09-24', 99.55, 'SUR', 1996, 'RUB', 22.97),
    ('RU000A100YD8', DATE '2024-09-25', 99.55, 'SUR', 1996, 'RUB', 23.79),
    ('RU000A100YD8', DATE '2024-09-26', 99.55, 'SUR', 1996, 'RUB', 0)
),
resolved_base AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        i.type AS instrument_type,
        s.raw_price,
        CASE
            WHEN upper(coalesce(s.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(s.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(s.trade_currency_id)
        END AS trade_currency_id,
        s.face_value,
        CASE
            WHEN upper(coalesce(s.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(s.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(s.face_currency_id)
        END AS face_currency_id,
        coalesce(s.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|MOEX') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.ticker) = s.ticker
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'MOEX',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
