-- Targeted MOEX backfill for missing Полипласт АО П02-БО-14 prices.
-- Source: MOEX history for RU000A10ECX8, fetched on 2026-04-18.
-- Listing start on MOEX: 2026-02-25.

-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 38

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A10ECX8', DATE '2026-02-25', 102.9893, 'SUR', 100, 'USD', 0),
    ('RU000A10ECX8', DATE '2026-02-26', 100.9899, 'SUR', 100, 'USD', 2.294),
    ('RU000A10ECX8', DATE '2026-02-27', 100.5, 'SUR', 100, 'USD', 5.3985),
    ('RU000A10ECX8', DATE '2026-03-02', 99.9803, 'SUR', 100, 'USD', 13.1365),
    ('RU000A10ECX8', DATE '2026-03-03', 99.95, 'SUR', 100, 'USD', 16.2064),
    ('RU000A10ECX8', DATE '2026-03-04', 99.67, 'SUR', 100, 'USD', 18.6262),
    ('RU000A10ECX8', DATE '2026-03-05', 100.2254, 'SUR', 100, 'USD', 21.7843),
    ('RU000A10ECX8', DATE '2026-03-06', 100.2046, 'SUR', 100, 'USD', 24.2389),
    ('RU000A10ECX8', DATE '2026-03-09', 99.4798, 'SUR', 100, 'USD', 33.243),
    ('RU000A10ECX8', DATE '2026-03-10', 99.6586, 'SUR', 100, 'USD', 35.6175),
    ('RU000A10ECX8', DATE '2026-03-11', 99.7496, 'SUR', 100, 'USD', 38.5824),
    ('RU000A10ECX8', DATE '2026-03-12', 99.6611, 'SUR', 100, 'USD', 41.1154),
    ('RU000A10ECX8', DATE '2026-03-13', 99.9024, 'SUR', 100, 'USD', 44.2776),
    ('RU000A10ECX8', DATE '2026-03-16', 100, 'SUR', 100, 'USD', 52.9488),
    ('RU000A10ECX8', DATE '2026-03-17', 100.222, 'SUR', 100, 'USD', 56.7362),
    ('RU000A10ECX8', DATE '2026-03-18', 100.29, 'SUR', 100, 'USD', 59.7945),
    ('RU000A10ECX8', DATE '2026-03-19', 100.2094, 'SUR', 100, 'USD', 64.0069),
    ('RU000A10ECX8', DATE '2026-03-20', 96.3019, 'SUR', 100, 'USD', 67.8703),
    ('RU000A10ECX8', DATE '2026-03-23', 96.0271, 'SUR', 100, 'USD', 76.4384),
    ('RU000A10ECX8', DATE '2026-03-24', 95.4804, 'SUR', 100, 'USD', 76.9637),
    ('RU000A10ECX8', DATE '2026-03-25', 98.7498, 'SUR', 100, 'USD', 79.3412),
    ('RU000A10ECX8', DATE '2026-03-26', 99.0026, 'SUR', 100, 'USD', 81.5264),
    ('RU000A10ECX8', DATE '2026-03-27', 98.4617, 'SUR', 100, 'USD', 0),
    ('RU000A10ECX8', DATE '2026-03-30', 98.3947, 'SUR', 100, 'USD', 8.1144),
    ('RU000A10ECX8', DATE '2026-03-31', 98.4064, 'SUR', 100, 'USD', 11.3814),
    ('RU000A10ECX8', DATE '2026-04-01', 98.1397, 'SUR', 100, 'USD', 13.8126),
    ('RU000A10ECX8', DATE '2026-04-02', 98.045, 'SUR', 100, 'USD', 16.9309),
    ('RU000A10ECX8', DATE '2026-04-03', 98.3088, 'SUR', 100, 'USD', 19.28),
    ('RU000A10ECX8', DATE '2026-04-06', 97.8, 'SUR', 100, 'USD', 27.9053),
    ('RU000A10ECX8', DATE '2026-04-07', 98.94, 'SUR', 100, 'USD', 29.9165),
    ('RU000A10ECX8', DATE '2026-04-08', 98.9719, 'SUR', 100, 'USD', 33.0748),
    ('RU000A10ECX8', DATE '2026-04-09', 98.4001, 'SUR', 100, 'USD', 35.2369),
    ('RU000A10ECX8', DATE '2026-04-10', 98.9905, 'SUR', 100, 'USD', 38.1399),
    ('RU000A10ECX8', DATE '2026-04-13', 99.4827, 'SUR', 100, 'USD', 45.4137),
    ('RU000A10ECX8', DATE '2026-04-14', 99.8439, 'SUR', 100, 'USD', 48.0368),
    ('RU000A10ECX8', DATE '2026-04-15', 99.75, 'SUR', 100, 'USD', 50.0631),
    ('RU000A10ECX8', DATE '2026-04-16', 100.4908, 'SUR', 100, 'USD', 52.6642),
    ('RU000A10ECX8', DATE '2026-04-17', 99.3114, 'SUR', 100, 'USD', 55.5429)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    38 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 38;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2026, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2026, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2026, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2026, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
