-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2025
-- Provider: MOEX
-- Rows: 209

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A10BV55', DATE '2025-06-24', 100.5999, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2025-06-25', 100.35, 'SUR', 1000, 'USD', 16.4617),
    ('RU000A10BV55', DATE '2025-06-26', 101.19, 'SUR', 1000, 'USD', 32.0603),
    ('RU000A10BV55', DATE '2025-06-27', 101.3223, 'SUR', 1000, 'USD', 48.4913),
    ('RU000A10BV55', DATE '2025-06-30', 101.7, 'SUR', 1000, 'USD', 96.5163),
    ('RU000A10BV55', DATE '2025-07-01', 101.7888, 'SUR', 1000, 'USD', 113.0809),
    ('RU000A10BV55', DATE '2025-07-02', 102.3875, 'SUR', 1000, 'USD', 128.6057),
    ('RU000A10BV55', DATE '2025-07-03', 103.2916, 'SUR', 1000, 'USD', 145.5099),
    ('RU000A10BV55', DATE '2025-07-04', 102.4752, 'SUR', 1000, 'USD', 161.5054),
    ('RU000A10BV55', DATE '2025-07-07', 102.2, 'SUR', 1000, 'USD', 210.4905),
    ('RU000A10BV55', DATE '2025-07-08', 102.2609, 'SUR', 1000, 'USD', 226.7093),
    ('RU000A10BV55', DATE '2025-07-09', 102.8499, 'SUR', 1000, 'USD', 240.7581),
    ('RU000A10BV55', DATE '2025-07-10', 103.1295, 'SUR', 1000, 'USD', 257.1882),
    ('RU000A10BV55', DATE '2025-07-11', 103.6102, 'SUR', 1000, 'USD', 271.8811),
    ('RU000A10BV55', DATE '2025-07-14', 104, 'SUR', 1000, 'USD', 320.1094),
    ('RU000A10BV55', DATE '2025-07-15', 104.2499, 'SUR', 1000, 'USD', 338.5679),
    ('RU000A10BV55', DATE '2025-07-16', 104.05, 'SUR', 1000, 'USD', 352.372),
    ('RU000A10BV55', DATE '2025-07-17', 104.4, 'SUR', 1000, 'USD', 368.7437),
    ('RU000A10BV55', DATE '2025-07-18', 104.3902, 'SUR', 1000, 'USD', 385.455),
    ('RU000A10BV55', DATE '2025-07-21', 104.6499, 'SUR', 1000, 'USD', 434.6366),
    ('RU000A10BV55', DATE '2025-07-22', 103.4071, 'SUR', 1000, 'USD', 450.3826),
    ('RU000A10BV55', DATE '2025-07-23', 104.1496, 'SUR', 1000, 'USD', 465.4057),
    ('RU000A10BV55', DATE '2025-07-24', 104.3666, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2025-07-25', 105.2696, 'SUR', 1000, 'USD', 16.5611),
    ('RU000A10BV55', DATE '2025-07-28', 106.13, 'SUR', 1000, 'USD', 65.2332),
    ('RU000A10BV55', DATE '2025-07-29', 107.9574, 'SUR', 1000, 'USD', 81.9655),
    ('RU000A10BV55', DATE '2025-07-30', 103.5, 'SUR', 1000, 'USD', 101.1302),
    ('RU000A10BV55', DATE '2025-07-31', 102.8, 'SUR', 1000, 'USD', 117.842),
    ('RU000A10BV55', DATE '2025-08-01', 102.4, 'SUR', 1000, 'USD', 131.7187),
    ('RU000A10BV55', DATE '2025-08-04', 102.42, 'SUR', 1000, 'USD', 181.5433),
    ('RU000A10BV55', DATE '2025-08-05', 103.8, 'SUR', 1000, 'USD', 196.7938),
    ('RU000A10BV55', DATE '2025-08-06', 103.99, 'SUR', 1000, 'USD', 213.7308),
    ('RU000A10BV55', DATE '2025-08-07', 102.5989, 'SUR', 1000, 'USD', 230.9512),
    ('RU000A10BV55', DATE '2025-08-08', 103.9004, 'SUR', 1000, 'USD', 244.5049),
    ('RU000A10BV55', DATE '2025-08-11', 104, 'SUR', 1000, 'USD', 295.1845),
    ('RU000A10BV55', DATE '2025-08-12', 104.0281, 'SUR', 1000, 'USD', 310.704),
    ('RU000A10BV55', DATE '2025-08-13', 104.1, 'SUR', 1000, 'USD', 328.2715),
    ('RU000A10BV55', DATE '2025-08-14', 105, 'SUR', 1000, 'USD', 343.8858),
    ('RU000A10BV55', DATE '2025-08-15', 106.1, 'SUR', 1000, 'USD', 360.5392),
    ('RU000A10BV55', DATE '2025-08-18', 106.399, 'SUR', 1000, 'USD', 411.3151),
    ('RU000A10BV55', DATE '2025-08-19', 105.5, 'SUR', 1000, 'USD', 429.4727),
    ('RU000A10BV55', DATE '2025-08-20', 105.5, 'SUR', 1000, 'USD', 445.9236),
    ('RU000A10BV55', DATE '2025-08-21', 105.2, 'SUR', 1000, 'USD', 460.6009),
    ('RU000A10BV55', DATE '2025-08-22', 106.1566, 'SUR', 1000, 'USD', 478.3186),
    ('RU000A10BV55', DATE '2025-08-25', 105.45, 'SUR', 1000, 'USD', 33.1074),
    ('RU000A10BV55', DATE '2025-08-26', 105.3999, 'SUR', 1000, 'USD', 50.0242),
    ('RU000A10BV55', DATE '2025-08-27', 105.7, 'SUR', 1000, 'USD', 66.032),
    ('RU000A10BV55', DATE '2025-08-28', 105.8155, 'SUR', 1000, 'USD', 82.8554),
    ('RU000A10BV55', DATE '2025-08-29', 105.8999, 'SUR', 1000, 'USD', 98.7589),
    ('RU000A10BV55', DATE '2025-09-01', 106, 'SUR', 1000, 'USD', 148.6135),
    ('RU000A10BV55', DATE '2025-09-02', 105.7138, 'SUR', 1000, 'USD', 164.8735),
    ('RU000A10BV55', DATE '2025-09-03', 105, 'SUR', 1000, 'USD', 182.144),
    ('RU000A10BV55', DATE '2025-09-04', 104.72, 'SUR', 1000, 'USD', 199.6965),
    ('RU000A10BV55', DATE '2025-09-05', 104.1002, 'SUR', 1000, 'USD', 217.0649),
    ('RU000A10BV55', DATE '2025-09-08', 106.5, 'SUR', 1000, 'USD', 268.3179),
    ('RU000A10BV55', DATE '2025-09-09', 107.6, 'SUR', 1000, 'USD', 287.3656),
    ('RU000A10BV55', DATE '2025-09-10', 107.6, 'SUR', 1000, 'USD', 307.9973),
    ('RU000A10BV55', DATE '2025-09-11', 105.8272, 'SUR', 1000, 'USD', 331.1923),
    ('RU000A10BV55', DATE '2025-09-12', 103.81, 'SUR', 1000, 'USD', 352.0819),
    ('RU000A10BV55', DATE '2025-09-15', 102.4, 'SUR', 1000, 'USD', 399.1165),
    ('RU000A10BV55', DATE '2025-09-16', 104.69, 'SUR', 1000, 'USD', 409.544),
    ('RU000A10BV55', DATE '2025-09-17', 104.6886, 'SUR', 1000, 'USD', 425.7765),
    ('RU000A10BV55', DATE '2025-09-18', 104.7, 'SUR', 1000, 'USD', 443.2131),
    ('RU000A10BV55', DATE '2025-09-19', 103.6001, 'SUR', 1000, 'USD', 461.6074),
    ('RU000A10BV55', DATE '2025-09-22', 102.5, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2025-09-23', 101.5376, 'SUR', 1000, 'USD', 17.6439),
    ('RU000A10BV55', DATE '2025-09-24', 102, 'SUR', 1000, 'USD', 34.1737),
    ('RU000A10BV55', DATE '2025-09-25', 101.56, 'SUR', 1000, 'USD', 52.0747),
    ('RU000A10BV55', DATE '2025-09-26', 101.4709, 'SUR', 1000, 'USD', 68.5577),
    ('RU000A10BV55', DATE '2025-09-29', 100.2487, 'SUR', 1000, 'USD', 120.401),
    ('RU000A10BV55', DATE '2025-09-30', 100.9998, 'SUR', 1000, 'USD', 135.9029),
    ('RU000A10BV55', DATE '2025-10-01', 100.3628, 'SUR', 1000, 'USD', 152.8255),
    ('RU000A10BV55', DATE '2025-10-02', 101.5046, 'SUR', 1000, 'USD', 167.0682),
    ('RU000A10BV55', DATE '2025-10-03', 103.6996, 'SUR', 1000, 'USD', 183.0792),
    ('RU000A10BV55', DATE '2025-10-06', 103.1636, 'SUR', 1000, 'USD', 235.8631),
    ('RU000A10BV55', DATE '2025-10-07', 100.9774, 'SUR', 1000, 'USD', 255.64),
    ('RU000A10BV55', DATE '2025-10-08', 101.4997, 'SUR', 1000, 'USD', 269.5658),
    ('RU000A10BV55', DATE '2025-10-09', 101.04, 'SUR', 1000, 'USD', 284.6018),
    ('RU000A10BV55', DATE '2025-10-10', 100.7876, 'SUR', 1000, 'USD', 301.2181),
    ('RU000A10BV55', DATE '2025-10-13', 100.4001, 'SUR', 1000, 'USD', 350.7399),
    ('RU000A10BV55', DATE '2025-10-14', 101.0594, 'SUR', 1000, 'USD', 365.4637),
    ('RU000A10BV55', DATE '2025-10-15', 100.4338, 'SUR', 1000, 'USD', 378.2056),
    ('RU000A10BV55', DATE '2025-10-16', 103, 'SUR', 1000, 'USD', 388.6763),
    ('RU000A10BV55', DATE '2025-10-17', 104.4939, 'SUR', 1000, 'USD', 406.4912),
    ('RU000A10BV55', DATE '2025-10-20', 101.0951, 'SUR', 1000, 'USD', 465.6546),
    ('RU000A10BV55', DATE '2025-10-21', 101.7074, 'SUR', 1000, 'USD', 484.8949),
    ('RU000A10BV55', DATE '2025-10-22', 101.9711, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2025-10-23', 101.0854, 'SUR', 1000, 'USD', 17.1475),
    ('RU000A10BV55', DATE '2025-10-24', 99.9352, 'SUR', 1000, 'USD', 33.3203),
    ('RU000A10BV55', DATE '2025-10-27', 99.3424, 'SUR', 1000, 'USD', 83.4004),
    ('RU000A10BV55', DATE '2025-10-28', 101.35, 'SUR', 1000, 'USD', 97.1513),
    ('RU000A10BV55', DATE '2025-10-29', 100.9418, 'SUR', 1000, 'USD', 114.9371),
    ('RU000A10BV55', DATE '2025-10-30', 102.3999, 'SUR', 1000, 'USD', 130.3333),
    ('RU000A10BV55', DATE '2025-10-31', 101.5333, 'SUR', 1000, 'USD', 148.9318),
    ('RU000A10BV55', DATE '2025-11-01', 101.0592, 'SUR', 1000, 'USD', 166),
    ('RU000A10BV55', DATE '2025-11-03', 100.7501, 'SUR', 1000, 'USD', 199.7887),
    ('RU000A10BV55', DATE '2025-11-05', 102.779, 'SUR', 1000, 'USD', 232.952),
    ('RU000A10BV55', DATE '2025-11-06', 101.6789, 'SUR', 1000, 'USD', 250.0606),
    ('RU000A10BV55', DATE '2025-11-07', 101.3837, 'SUR', 1000, 'USD', 267.7287),
    ('RU000A10BV55', DATE '2025-11-10', 101.2243, 'SUR', 1000, 'USD', 316.7802),
    ('RU000A10BV55', DATE '2025-11-11', 101.0146, 'SUR', 1000, 'USD', 332.9643),
    ('RU000A10BV55', DATE '2025-11-12', 100.802, 'SUR', 1000, 'USD', 351.4588),
    ('RU000A10BV55', DATE '2025-11-13', 100.3836, 'SUR', 1000, 'USD', 367.4091),
    ('RU000A10BV55', DATE '2025-11-14', 101.3778, 'SUR', 1000, 'USD', 381.2427),
    ('RU000A10BV55', DATE '2025-11-17', 101.216, 'SUR', 1000, 'USD', 433.2214),
    ('RU000A10BV55', DATE '2025-11-18', 100.9703, 'SUR', 1000, 'USD', 450.2726),
    ('RU000A10BV55', DATE '2025-11-19', 100.9298, 'SUR', 1000, 'USD', 466.0645),
    ('RU000A10BV55', DATE '2025-11-20', 100.9996, 'SUR', 1000, 'USD', 482.431),
    ('RU000A10BV55', DATE '2025-11-21', 100.0722, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2025-11-24', 101.45, 'SUR', 1000, 'USD', 48.9953),
    ('RU000A10BV55', DATE '2025-11-25', 101.1847, 'SUR', 1000, 'USD', 64.7146),
    ('RU000A10BV55', DATE '2025-11-26', 101.2511, 'SUR', 1000, 'USD', 81.3303),
    ('RU000A10BV55', DATE '2025-11-27', 100.9999, 'SUR', 1000, 'USD', 96.6707),
    ('RU000A10BV55', DATE '2025-11-28', 101.1699, 'SUR', 1000, 'USD', 112.6804),
    ('RU000A10BV55', DATE '2025-12-01', 101.0499, 'SUR', 1000, 'USD', 160.3682),
    ('RU000A10BV55', DATE '2025-12-02', 101.4968, 'SUR', 1000, 'USD', 175.6081),
    ('RU000A10BV55', DATE '2025-12-03', 101.7, 'SUR', 1000, 'USD', 191.3339),
    ('RU000A10BV55', DATE '2025-12-04', 100.7001, 'SUR', 1000, 'USD', 208.1415),
    ('RU000A10BV55', DATE '2025-12-05', 101.9, 'SUR', 1000, 'USD', 221.6759),
    ('RU000A10BV55', DATE '2025-12-08', 102.575, 'SUR', 1000, 'USD', 265.567),
    ('RU000A10BV55', DATE '2025-12-09', 102.5, 'SUR', 1000, 'USD', 285.9112),
    ('RU000A10BV55', DATE '2025-12-10', 103.6405, 'SUR', 1000, 'USD', 299.5528),
    ('RU000A10BV55', DATE '2025-12-11', 104.8783, 'SUR', 1000, 'USD', 320.1682),
    ('RU000A10BV55', DATE '2025-12-12', 102.4001, 'SUR', 1000, 'USD', 342.7479),
    ('RU000A10BV55', DATE '2025-12-15', 101.2988, 'SUR', 1000, 'USD', 393.0669),
    ('RU000A10BV55', DATE '2025-12-16', 101.5749, 'SUR', 1000, 'USD', 408.3704),
    ('RU000A10BV55', DATE '2025-12-17', 103.5, 'SUR', 1000, 'USD', 424.1573),
    ('RU000A10BV55', DATE '2025-12-18', 102.7495, 'SUR', 1000, 'USD', 446.1129),
    ('RU000A10BV55', DATE '2025-12-19', 102.315, 'SUR', 1000, 'USD', 460.1731),
    ('RU000A10BV55', DATE '2025-12-22', 100.4597, 'SUR', 1000, 'USD', 16.9516),
    ('RU000A10BV55', DATE '2025-12-23', 101.4994, 'SUR', 1000, 'USD', 32.519),
    ('RU000A10BV55', DATE '2025-12-24', 102.8266, 'SUR', 1000, 'USD', 48.7227),
    ('RU000A10BV55', DATE '2025-12-25', 101.9499, 'SUR', 1000, 'USD', 64.3182),
    ('RU000A10BV55', DATE '2025-12-26', 102.5, 'SUR', 1000, 'USD', 80.2209),
    ('RU000A10BV55', DATE '2025-12-29', 103.9969, 'SUR', 1000, 'USD', 127.4154),
    ('RU000A10BV55', DATE '2025-12-30', 104.2007, 'SUR', 1000, 'USD', 143.2762),
    ('RU000A10CS75', DATE '2025-09-19', 99.94, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2025-09-22', 99.99, 'SUR', 1000, 'RUB', 1.58),
    ('RU000A10CS75', DATE '2025-09-23', 99.92, 'SUR', 1000, 'RUB', 2.09),
    ('RU000A10CS75', DATE '2025-09-24', 99.9, 'SUR', 1000, 'RUB', 2.6),
    ('RU000A10CS75', DATE '2025-09-25', 99.87, 'SUR', 1000, 'RUB', 3.11),
    ('RU000A10CS75', DATE '2025-09-26', 99.87, 'SUR', 1000, 'RUB', 3.62),
    ('RU000A10CS75', DATE '2025-09-29', 99.84, 'SUR', 1000, 'RUB', 5.15),
    ('RU000A10CS75', DATE '2025-09-30', 99.72, 'SUR', 1000, 'RUB', 5.66),
    ('RU000A10CS75', DATE '2025-10-01', 99.7, 'SUR', 1000, 'RUB', 6.17),
    ('RU000A10CS75', DATE '2025-10-02', 99.88, 'SUR', 1000, 'RUB', 6.68),
    ('RU000A10CS75', DATE '2025-10-03', 99.83, 'SUR', 1000, 'RUB', 7.19),
    ('RU000A10CS75', DATE '2025-10-06', 99.9, 'SUR', 1000, 'RUB', 8.72),
    ('RU000A10CS75', DATE '2025-10-07', 99.76, 'SUR', 1000, 'RUB', 9.23),
    ('RU000A10CS75', DATE '2025-10-08', 99.71, 'SUR', 1000, 'RUB', 9.74),
    ('RU000A10CS75', DATE '2025-10-09', 99.56, 'SUR', 1000, 'RUB', 10.25),
    ('RU000A10CS75', DATE '2025-10-10', 99.75, 'SUR', 1000, 'RUB', 10.76),
    ('RU000A10CS75', DATE '2025-10-13', 99.73, 'SUR', 1000, 'RUB', 12.28),
    ('RU000A10CS75', DATE '2025-10-14', 99.6, 'SUR', 1000, 'RUB', 12.79),
    ('RU000A10CS75', DATE '2025-10-15', 99.6, 'SUR', 1000, 'RUB', 13.3),
    ('RU000A10CS75', DATE '2025-10-16', 99.6, 'SUR', 1000, 'RUB', 13.81),
    ('RU000A10CS75', DATE '2025-10-17', 99.73, 'SUR', 1000, 'RUB', 14.32),
    ('RU000A10CS75', DATE '2025-10-20', 99.7, 'SUR', 1000, 'RUB', 0.51),
    ('RU000A10CS75', DATE '2025-10-21', 99.57, 'SUR', 1000, 'RUB', 1.02),
    ('RU000A10CS75', DATE '2025-10-22', 99.48, 'SUR', 1000, 'RUB', 1.53),
    ('RU000A10CS75', DATE '2025-10-23', 99.59, 'SUR', 1000, 'RUB', 2.04),
    ('RU000A10CS75', DATE '2025-10-24', 99.66, 'SUR', 1000, 'RUB', 2.55),
    ('RU000A10CS75', DATE '2025-10-27', 99.57, 'SUR', 1000, 'RUB', 4.08),
    ('RU000A10CS75', DATE '2025-10-28', 99.69, 'SUR', 1000, 'RUB', 4.59),
    ('RU000A10CS75', DATE '2025-10-29', 99.55, 'SUR', 1000, 'RUB', 5.1),
    ('RU000A10CS75', DATE '2025-10-30', 99.53, 'SUR', 1000, 'RUB', 5.61),
    ('RU000A10CS75', DATE '2025-10-31', 99.48, 'SUR', 1000, 'RUB', 6.12),
    ('RU000A10CS75', DATE '2025-11-01', 99.58, 'SUR', 1000, 'RUB', 6.62),
    ('RU000A10CS75', DATE '2025-11-03', 99.58, 'SUR', 1000, 'RUB', 7.63),
    ('RU000A10CS75', DATE '2025-11-05', 99.6, 'SUR', 1000, 'RUB', 8.62),
    ('RU000A10CS75', DATE '2025-11-06', 99.5, 'SUR', 1000, 'RUB', 9.12),
    ('RU000A10CS75', DATE '2025-11-07', 99.55, 'SUR', 1000, 'RUB', 9.61),
    ('RU000A10CS75', DATE '2025-11-10', 99.59, 'SUR', 1000, 'RUB', 11.1),
    ('RU000A10CS75', DATE '2025-11-11', 99.58, 'SUR', 1000, 'RUB', 11.6),
    ('RU000A10CS75', DATE '2025-11-12', 99.58, 'SUR', 1000, 'RUB', 12.09),
    ('RU000A10CS75', DATE '2025-11-13', 99.55, 'SUR', 1000, 'RUB', 12.59),
    ('RU000A10CS75', DATE '2025-11-14', 99.75, 'SUR', 1000, 'RUB', 13.08),
    ('RU000A10CS75', DATE '2025-11-17', 99.63, 'SUR', 1000, 'RUB', 14.57),
    ('RU000A10CS75', DATE '2025-11-18', 99.6, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2025-11-19', 99.84, 'SUR', 1000, 'RUB', 0.5),
    ('RU000A10CS75', DATE '2025-11-20', 100.08, 'SUR', 1000, 'RUB', 0.99),
    ('RU000A10CS75', DATE '2025-11-21', 99.75, 'SUR', 1000, 'RUB', 1.49),
    ('RU000A10CS75', DATE '2025-11-24', 99.82, 'SUR', 1000, 'RUB', 2.98),
    ('RU000A10CS75', DATE '2025-11-25', 99.5, 'SUR', 1000, 'RUB', 3.47),
    ('RU000A10CS75', DATE '2025-11-26', 99.64, 'SUR', 1000, 'RUB', 3.97),
    ('RU000A10CS75', DATE '2025-11-27', 99.73, 'SUR', 1000, 'RUB', 4.46),
    ('RU000A10CS75', DATE '2025-11-28', 99.72, 'SUR', 1000, 'RUB', 4.96),
    ('RU000A10CS75', DATE '2025-12-01', 99.73, 'SUR', 1000, 'RUB', 6.45),
    ('RU000A10CS75', DATE '2025-12-02', 99.56, 'SUR', 1000, 'RUB', 6.94),
    ('RU000A10CS75', DATE '2025-12-03', 99.74, 'SUR', 1000, 'RUB', 7.44),
    ('RU000A10CS75', DATE '2025-12-04', 99.74, 'SUR', 1000, 'RUB', 7.93),
    ('RU000A10CS75', DATE '2025-12-05', 99.7, 'SUR', 1000, 'RUB', 8.43),
    ('RU000A10CS75', DATE '2025-12-08', 99.68, 'SUR', 1000, 'RUB', 9.92),
    ('RU000A10CS75', DATE '2025-12-09', 99.69, 'SUR', 1000, 'RUB', 10.41),
    ('RU000A10CS75', DATE '2025-12-10', 99.72, 'SUR', 1000, 'RUB', 10.91),
    ('RU000A10CS75', DATE '2025-12-11', 99.59, 'SUR', 1000, 'RUB', 11.41),
    ('RU000A10CS75', DATE '2025-12-12', 99.72, 'SUR', 1000, 'RUB', 11.9),
    ('RU000A10CS75', DATE '2025-12-15', 99.66, 'SUR', 1000, 'RUB', 13.39),
    ('RU000A10CS75', DATE '2025-12-16', 99.52, 'SUR', 1000, 'RUB', 13.88),
    ('RU000A10CS75', DATE '2025-12-17', 99.33, 'SUR', 1000, 'RUB', 14.38),
    ('RU000A10CS75', DATE '2025-12-18', 99.57, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2025-12-19', 99.5, 'SUR', 1000, 'RUB', 0.5),
    ('RU000A10CS75', DATE '2025-12-22', 99.05, 'SUR', 1000, 'RUB', 1.98),
    ('RU000A10CS75', DATE '2025-12-23', 99, 'SUR', 1000, 'RUB', 2.48),
    ('RU000A10CS75', DATE '2025-12-24', 99, 'SUR', 1000, 'RUB', 2.98),
    ('RU000A10CS75', DATE '2025-12-25', 98.76, 'SUR', 1000, 'RUB', 3.47),
    ('RU000A10CS75', DATE '2025-12-26', 99, 'SUR', 1000, 'RUB', 3.97),
    ('RU000A10CS75', DATE '2025-12-29', 99.14, 'SUR', 1000, 'RUB', 5.44),
    ('RU000A10CS75', DATE '2025-12-30', 98.99, 'SUR', 1000, 'RUB', 5.92)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        CASE
            WHEN rb.instrument_type = 2 THEN rb.currency_id
            ELSE rb.trade_currency_id
        END AS currency_id,
        rb.trade_currency_id AS source_currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    source_currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, source_currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        source_currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        source_currency_id = EXCLUDED.source_currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    209 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 209;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2025, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2025, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2025, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2025, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
