-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2025
-- Provider: MOEX
-- Rows: 436

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A108EE1', DATE '2025-01-03', 80.748, 'SUR', 1000, 'RUB', 32.88),
    ('RU000A108EE1', DATE '2025-01-06', 80.806, 'SUR', 1000, 'RUB', 33.87),
    ('RU000A108EE1', DATE '2025-01-08', 80.81, 'SUR', 1000, 'RUB', 34.52),
    ('RU000A108EE1', DATE '2025-01-09', 79.818, 'SUR', 1000, 'RUB', 34.85),
    ('RU000A108EE1', DATE '2025-01-10', 79.19, 'SUR', 1000, 'RUB', 35.18),
    ('RU000A108EE1', DATE '2025-01-13', 79.2, 'SUR', 1000, 'RUB', 36.17),
    ('RU000A108EE1', DATE '2025-01-14', 79.099, 'SUR', 1000, 'RUB', 36.5),
    ('RU000A108EE1', DATE '2025-01-15', 78.86, 'SUR', 1000, 'RUB', 36.82),
    ('RU000A108EE1', DATE '2025-01-16', 78.697, 'SUR', 1000, 'RUB', 37.15),
    ('RU000A108EE1', DATE '2025-01-17', 78.45, 'SUR', 1000, 'RUB', 37.48),
    ('RU000A108EE1', DATE '2025-01-20', 78.709, 'SUR', 1000, 'RUB', 38.47),
    ('RU000A108EE1', DATE '2025-01-21', 78.25, 'SUR', 1000, 'RUB', 38.8),
    ('RU000A108EE1', DATE '2025-01-22', 78.198, 'SUR', 1000, 'RUB', 39.13),
    ('RU000A108EE1', DATE '2025-01-23', 77.71, 'SUR', 1000, 'RUB', 39.45),
    ('RU000A108EE1', DATE '2025-01-24', 77.689, 'SUR', 1000, 'RUB', 39.78),
    ('RU000A108EE1', DATE '2025-01-27', 77.326, 'SUR', 1000, 'RUB', 40.77),
    ('RU000A108EE1', DATE '2025-01-28', 77.5, 'SUR', 1000, 'RUB', 41.1),
    ('RU000A108EE1', DATE '2025-01-29', 77.399, 'SUR', 1000, 'RUB', 41.43),
    ('RU000A108EE1', DATE '2025-01-30', 77.536, 'SUR', 1000, 'RUB', 41.76),
    ('RU000A108EE1', DATE '2025-01-31', 77.058, 'SUR', 1000, 'RUB', 42.09),
    ('RU000A108EE1', DATE '2025-02-03', 76.74, 'SUR', 1000, 'RUB', 43.07),
    ('RU000A108EE1', DATE '2025-02-04', 76.4, 'SUR', 1000, 'RUB', 43.4),
    ('RU000A108EE1', DATE '2025-02-05', 76.868, 'SUR', 1000, 'RUB', 43.73),
    ('RU000A108EE1', DATE '2025-02-06', 77.359, 'SUR', 1000, 'RUB', 44.06),
    ('RU000A108EE1', DATE '2025-02-07', 77.879, 'SUR', 1000, 'RUB', 44.39),
    ('RU000A108EE1', DATE '2025-02-10', 77.53, 'SUR', 1000, 'RUB', 45.37),
    ('RU000A108EE1', DATE '2025-02-11', 77.4, 'SUR', 1000, 'RUB', 45.7),
    ('RU000A108EE1', DATE '2025-02-12', 77.6, 'SUR', 1000, 'RUB', 46.03),
    ('RU000A108EE1', DATE '2025-02-13', 82.3, 'SUR', 1000, 'RUB', 46.36),
    ('RU000A108EE1', DATE '2025-02-14', 80.252, 'SUR', 1000, 'RUB', 46.69),
    ('RU000A108EE1', DATE '2025-02-17', 80.217, 'SUR', 1000, 'RUB', 47.67),
    ('RU000A108EE1', DATE '2025-02-18', 80.369, 'SUR', 1000, 'RUB', 48),
    ('RU000A108EE1', DATE '2025-02-19', 80.407, 'SUR', 1000, 'RUB', 48.33),
    ('RU000A108EE1', DATE '2025-02-20', 81.001, 'SUR', 1000, 'RUB', 48.66),
    ('RU000A108EE1', DATE '2025-02-21', 80.35, 'SUR', 1000, 'RUB', 48.99),
    ('RU000A108EE1', DATE '2025-02-24', 80.362, 'SUR', 1000, 'RUB', 49.98),
    ('RU000A108EE1', DATE '2025-02-25', 80.382, 'SUR', 1000, 'RUB', 50.31),
    ('RU000A108EE1', DATE '2025-02-26', 80.627, 'SUR', 1000, 'RUB', 50.63),
    ('RU000A108EE1', DATE '2025-02-27', 80.72, 'SUR', 1000, 'RUB', 50.96),
    ('RU000A108EE1', DATE '2025-02-28', 80.835, 'SUR', 1000, 'RUB', 51.29),
    ('RU000A108EE1', DATE '2025-03-03', 80.601, 'SUR', 1000, 'RUB', 52.28),
    ('RU000A108EE1', DATE '2025-03-04', 80.881, 'SUR', 1000, 'RUB', 52.61),
    ('RU000A108EE1', DATE '2025-03-05', 81.69, 'SUR', 1000, 'RUB', 52.94),
    ('RU000A108EE1', DATE '2025-03-06', 82.95, 'SUR', 1000, 'RUB', 53.26),
    ('RU000A108EE1', DATE '2025-03-07', 83.379, 'SUR', 1000, 'RUB', 53.59),
    ('RU000A108EE1', DATE '2025-03-10', 85.18, 'SUR', 1000, 'RUB', 54.58),
    ('RU000A108EE1', DATE '2025-03-11', 84.65, 'SUR', 1000, 'RUB', 54.91),
    ('RU000A108EE1', DATE '2025-03-12', 85.649, 'SUR', 1000, 'RUB', 55.24),
    ('RU000A108EE1', DATE '2025-03-13', 85.099, 'SUR', 1000, 'RUB', 55.57),
    ('RU000A108EE1', DATE '2025-03-14', 85.956, 'SUR', 1000, 'RUB', 55.89),
    ('RU000A108EE1', DATE '2025-03-17', 86.799, 'SUR', 1000, 'RUB', 56.88),
    ('RU000A108EE1', DATE '2025-03-18', 87.25, 'SUR', 1000, 'RUB', 57.21),
    ('RU000A108EE1', DATE '2025-03-19', 87.5, 'SUR', 1000, 'RUB', 57.54),
    ('RU000A108EE1', DATE '2025-03-20', 87.1, 'SUR', 1000, 'RUB', 57.87),
    ('RU000A108EE1', DATE '2025-03-21', 86.65, 'SUR', 1000, 'RUB', 58.2),
    ('RU000A108EE1', DATE '2025-03-24', 85.501, 'SUR', 1000, 'RUB', 59.18),
    ('RU000A108EE1', DATE '2025-03-25', 85.599, 'SUR', 1000, 'RUB', 59.51),
    ('RU000A108EE1', DATE '2025-03-26', 84.9, 'SUR', 1000, 'RUB', 0),
    ('RU000A108EE1', DATE '2025-03-27', 84.609, 'SUR', 1000, 'RUB', 0.33),
    ('RU000A108EE1', DATE '2025-03-28', 84.379, 'SUR', 1000, 'RUB', 0.66),
    ('RU000A108EE1', DATE '2025-03-31', 84, 'SUR', 1000, 'RUB', 1.64),
    ('RU000A108EE1', DATE '2025-04-01', 84.033, 'SUR', 1000, 'RUB', 1.97),
    ('RU000A108EE1', DATE '2025-04-02', 83.6, 'SUR', 1000, 'RUB', 2.3),
    ('RU000A108EE1', DATE '2025-04-03', 82.799, 'SUR', 1000, 'RUB', 2.63),
    ('RU000A108EE1', DATE '2025-04-04', 82.2, 'SUR', 1000, 'RUB', 2.96),
    ('RU000A108EE1', DATE '2025-04-07', 80.599, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A108EE1', DATE '2025-04-08', 81.75, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A108EE1', DATE '2025-04-09', 79.732, 'SUR', 1000, 'RUB', 4.6),
    ('RU000A108EE1', DATE '2025-04-10', 81.399, 'SUR', 1000, 'RUB', 4.93),
    ('RU000A108EE1', DATE '2025-04-11', 82.49, 'SUR', 1000, 'RUB', 5.26),
    ('RU000A108EE1', DATE '2025-04-14', 82.337, 'SUR', 1000, 'RUB', 6.25),
    ('RU000A108EE1', DATE '2025-04-15', 81.639, 'SUR', 1000, 'RUB', 6.58),
    ('RU000A108EE1', DATE '2025-04-16', 82.4, 'SUR', 1000, 'RUB', 6.9),
    ('RU000A108EE1', DATE '2025-04-17', 82.45, 'SUR', 1000, 'RUB', 7.23),
    ('RU000A108EE1', DATE '2025-04-18', 82, 'SUR', 1000, 'RUB', 7.56),
    ('RU000A108EE1', DATE '2025-04-21', 82.745, 'SUR', 1000, 'RUB', 8.55),
    ('RU000A108EE1', DATE '2025-04-22', 82.48, 'SUR', 1000, 'RUB', 8.88),
    ('RU000A108EE1', DATE '2025-04-23', 82.57, 'SUR', 1000, 'RUB', 9.21),
    ('RU000A108EE1', DATE '2025-04-24', 82.744, 'SUR', 1000, 'RUB', 9.53),
    ('RU000A108EE1', DATE '2025-04-25', 82.949, 'SUR', 1000, 'RUB', 9.86),
    ('RU000A108EE1', DATE '2025-04-28', 82.65, 'SUR', 1000, 'RUB', 10.85),
    ('RU000A108EE1', DATE '2025-04-29', 81.899, 'SUR', 1000, 'RUB', 11.18),
    ('RU000A108EE1', DATE '2025-04-30', 81.805, 'SUR', 1000, 'RUB', 11.51),
    ('RU000A108EE1', DATE '2025-05-02', 81.388, 'SUR', 1000, 'RUB', 12.17),
    ('RU000A108EE1', DATE '2025-05-05', 80.768, 'SUR', 1000, 'RUB', 13.15),
    ('RU000A108EE1', DATE '2025-05-06', 80.94, 'SUR', 1000, 'RUB', 13.48),
    ('RU000A108EE1', DATE '2025-05-07', 81.4, 'SUR', 1000, 'RUB', 13.81),
    ('RU000A108EE1', DATE '2025-05-08', 81.6, 'SUR', 1000, 'RUB', 14.14),
    ('RU000A108EE1', DATE '2025-05-12', 81.469, 'SUR', 1000, 'RUB', 15.45),
    ('RU000A108EE1', DATE '2025-05-13', 81.025, 'SUR', 1000, 'RUB', 15.78),
    ('RU000A108EE1', DATE '2025-05-14', 81.447, 'SUR', 1000, 'RUB', 16.11),
    ('RU000A108EE1', DATE '2025-05-15', 81.104, 'SUR', 1000, 'RUB', 16.44),
    ('RU000A108EE1', DATE '2025-05-16', 81.191, 'SUR', 1000, 'RUB', 16.77),
    ('RU000A108EE1', DATE '2025-05-19', 81.25, 'SUR', 1000, 'RUB', 17.75),
    ('RU000A108EE1', DATE '2025-05-20', 80.91, 'SUR', 1000, 'RUB', 18.08),
    ('RU000A108EE1', DATE '2025-05-21', 80.964, 'SUR', 1000, 'RUB', 18.41),
    ('RU000A108EE1', DATE '2025-05-22', 80.817, 'SUR', 1000, 'RUB', 18.74),
    ('RU000A108EE1', DATE '2025-05-23', 80.85, 'SUR', 1000, 'RUB', 19.07),
    ('RU000A108EE1', DATE '2025-05-26', 80.373, 'SUR', 1000, 'RUB', 20.06),
    ('RU000A108EE1', DATE '2025-05-27', 80.444, 'SUR', 1000, 'RUB', 20.39),
    ('RU000A108EE1', DATE '2025-05-28', 81.014, 'SUR', 1000, 'RUB', 20.71),
    ('RU000A108EE1', DATE '2025-05-29', 81.67, 'SUR', 1000, 'RUB', 21.04),
    ('RU000A108EE1', DATE '2025-05-30', 82.5, 'SUR', 1000, 'RUB', 21.37),
    ('RU000A108EE1', DATE '2025-06-02', 82.75, 'SUR', 1000, 'RUB', 22.36),
    ('RU000A108EE1', DATE '2025-06-03', 83.199, 'SUR', 1000, 'RUB', 22.69),
    ('RU000A108EE1', DATE '2025-06-04', 83.773, 'SUR', 1000, 'RUB', 23.02),
    ('RU000A108EE1', DATE '2025-06-05', 84.212, 'SUR', 1000, 'RUB', 23.34),
    ('RU000A108EE1', DATE '2025-06-06', 83.3, 'SUR', 1000, 'RUB', 23.67),
    ('RU000A108EE1', DATE '2025-06-09', 83.954, 'SUR', 1000, 'RUB', 24.66),
    ('RU000A108EE1', DATE '2025-06-10', 84.446, 'SUR', 1000, 'RUB', 24.99),
    ('RU000A108EE1', DATE '2025-06-11', 84.6, 'SUR', 1000, 'RUB', 25.32),
    ('RU000A108EE1', DATE '2025-06-13', 85, 'SUR', 1000, 'RUB', 25.97),
    ('RU000A108EE1', DATE '2025-06-16', 84.488, 'SUR', 1000, 'RUB', 26.96),
    ('RU000A108EE1', DATE '2025-06-17', 84.39, 'SUR', 1000, 'RUB', 27.29),
    ('RU000A108EE1', DATE '2025-06-18', 84.639, 'SUR', 1000, 'RUB', 27.62),
    ('RU000A108EE1', DATE '2025-06-19', 85.2, 'SUR', 1000, 'RUB', 27.95),
    ('RU000A108EE1', DATE '2025-06-20', 85.449, 'SUR', 1000, 'RUB', 28.28),
    ('RU000A108EE1', DATE '2025-06-23', 85.171, 'SUR', 1000, 'RUB', 29.26),
    ('RU000A108EE1', DATE '2025-06-24', 85.144, 'SUR', 1000, 'RUB', 29.59),
    ('RU000A108EE1', DATE '2025-06-25', 85.885, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A108EE1', DATE '2025-06-26', 85.949, 'SUR', 1000, 'RUB', 30.25),
    ('RU000A108EE1', DATE '2025-06-27', 86.499, 'SUR', 1000, 'RUB', 30.58),
    ('RU000A108EE1', DATE '2025-06-30', 86.915, 'SUR', 1000, 'RUB', 31.56),
    ('RU000A108EE1', DATE '2025-07-01', 86.8, 'SUR', 1000, 'RUB', 31.89),
    ('RU000A108EE1', DATE '2025-07-02', 87.28, 'SUR', 1000, 'RUB', 32.22),
    ('RU000A108EE1', DATE '2025-07-03', 87.142, 'SUR', 1000, 'RUB', 32.55),
    ('RU000A108EE1', DATE '2025-07-04', 86.791, 'SUR', 1000, 'RUB', 32.88),
    ('RU000A108EE1', DATE '2025-07-07', 86.749, 'SUR', 1000, 'RUB', 33.87),
    ('RU000A108EE1', DATE '2025-07-08', 86.899, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A108EE1', DATE '2025-07-09', 86.2, 'SUR', 1000, 'RUB', 34.52),
    ('RU000A108EE1', DATE '2025-07-10', 86.749, 'SUR', 1000, 'RUB', 34.85),
    ('RU000A108EE1', DATE '2025-07-11', 86.696, 'SUR', 1000, 'RUB', 35.18),
    ('RU000A108EE1', DATE '2025-07-14', 86.803, 'SUR', 1000, 'RUB', 36.17),
    ('RU000A108EE1', DATE '2025-07-15', 88.434, 'SUR', 1000, 'RUB', 36.5),
    ('RU000A108EE1', DATE '2025-07-16', 88.85, 'SUR', 1000, 'RUB', 36.82),
    ('RU000A108EE1', DATE '2025-07-17', 89.149, 'SUR', 1000, 'RUB', 37.15),
    ('RU000A108EE1', DATE '2025-07-18', 89.239, 'SUR', 1000, 'RUB', 37.48),
    ('RU000A108EE1', DATE '2025-07-21', 89.354, 'SUR', 1000, 'RUB', 38.47),
    ('RU000A108EE1', DATE '2025-07-22', 89.239, 'SUR', 1000, 'RUB', 38.8),
    ('RU000A108EE1', DATE '2025-07-23', 89.33, 'SUR', 1000, 'RUB', 39.13),
    ('RU000A108EE1', DATE '2025-07-24', 89.779, 'SUR', 1000, 'RUB', 39.45),
    ('RU000A108EE1', DATE '2025-07-25', 89.989, 'SUR', 1000, 'RUB', 39.78),
    ('RU000A108EE1', DATE '2025-07-28', 89.68, 'SUR', 1000, 'RUB', 40.77),
    ('RU000A108EE1', DATE '2025-07-29', 89.696, 'SUR', 1000, 'RUB', 41.1),
    ('RU000A108EE1', DATE '2025-07-30', 89.86, 'SUR', 1000, 'RUB', 41.43),
    ('RU000A108EE1', DATE '2025-07-31', 89.67, 'SUR', 1000, 'RUB', 41.76),
    ('RU000A108EE1', DATE '2025-08-01', 89.525, 'SUR', 1000, 'RUB', 42.09),
    ('RU000A108EE1', DATE '2025-08-04', 89.441, 'SUR', 1000, 'RUB', 43.07),
    ('RU000A108EE1', DATE '2025-08-05', 89.549, 'SUR', 1000, 'RUB', 43.4),
    ('RU000A108EE1', DATE '2025-08-06', 89.398, 'SUR', 1000, 'RUB', 43.73),
    ('RU000A108EE1', DATE '2025-08-07', 90.27, 'SUR', 1000, 'RUB', 44.06),
    ('RU000A108EE1', DATE '2025-08-08', 90.79, 'SUR', 1000, 'RUB', 44.39),
    ('RU000A108EE1', DATE '2025-08-11', 91.183, 'SUR', 1000, 'RUB', 45.37),
    ('RU000A108EE1', DATE '2025-08-12', 91.09, 'SUR', 1000, 'RUB', 45.7),
    ('RU000A108EE1', DATE '2025-08-13', 91.15, 'SUR', 1000, 'RUB', 46.03),
    ('RU000A108EE1', DATE '2025-08-14', 91.25, 'SUR', 1000, 'RUB', 46.36),
    ('RU000A108EE1', DATE '2025-08-15', 91.83, 'SUR', 1000, 'RUB', 46.69),
    ('RU000A108EE1', DATE '2025-08-18', 91.98, 'SUR', 1000, 'RUB', 47.67),
    ('RU000A108EE1', DATE '2025-08-19', 92.44, 'SUR', 1000, 'RUB', 48),
    ('RU000A108EE1', DATE '2025-08-20', 91.737, 'SUR', 1000, 'RUB', 48.33),
    ('RU000A108EE1', DATE '2025-08-21', 91.297, 'SUR', 1000, 'RUB', 48.66),
    ('RU000A108EE1', DATE '2025-08-22', 91.345, 'SUR', 1000, 'RUB', 48.99),
    ('RU000A108EE1', DATE '2025-08-25', 91.1, 'SUR', 1000, 'RUB', 49.98),
    ('RU000A108EE1', DATE '2025-08-26', 90.839, 'SUR', 1000, 'RUB', 50.31),
    ('RU000A108EE1', DATE '2025-08-27', 90.91, 'SUR', 1000, 'RUB', 50.63),
    ('RU000A108EE1', DATE '2025-08-28', 90.755, 'SUR', 1000, 'RUB', 50.96),
    ('RU000A108EE1', DATE '2025-08-29', 90.9, 'SUR', 1000, 'RUB', 51.29),
    ('RU000A108EE1', DATE '2025-09-01', 90.902, 'SUR', 1000, 'RUB', 52.28),
    ('RU000A108EE1', DATE '2025-09-02', 90.82, 'SUR', 1000, 'RUB', 52.61),
    ('RU000A108EE1', DATE '2025-09-03', 91.825, 'SUR', 1000, 'RUB', 52.94),
    ('RU000A108EE1', DATE '2025-09-04', 92.199, 'SUR', 1000, 'RUB', 53.26),
    ('RU000A108EE1', DATE '2025-09-05', 92.5, 'SUR', 1000, 'RUB', 53.59),
    ('RU000A108EE1', DATE '2025-09-08', 92.495, 'SUR', 1000, 'RUB', 54.58),
    ('RU000A108EE1', DATE '2025-09-09', 91.917, 'SUR', 1000, 'RUB', 54.91),
    ('RU000A108EE1', DATE '2025-09-10', 91.75, 'SUR', 1000, 'RUB', 55.24),
    ('RU000A108EE1', DATE '2025-09-11', 91.3, 'SUR', 1000, 'RUB', 55.57),
    ('RU000A108EE1', DATE '2025-09-12', 90.2, 'SUR', 1000, 'RUB', 55.89),
    ('RU000A108EE1', DATE '2025-09-15', 89.929, 'SUR', 1000, 'RUB', 56.88),
    ('RU000A108EE1', DATE '2025-09-16', 89.36, 'SUR', 1000, 'RUB', 57.21),
    ('RU000A108EE1', DATE '2025-09-17', 89.5, 'SUR', 1000, 'RUB', 57.54),
    ('RU000A108EE1', DATE '2025-09-18', 89.104, 'SUR', 1000, 'RUB', 57.87),
    ('RU000A108EE1', DATE '2025-09-19', 87.95, 'SUR', 1000, 'RUB', 58.2),
    ('RU000A108EE1', DATE '2025-09-22', 88.1, 'SUR', 1000, 'RUB', 59.18),
    ('RU000A108EE1', DATE '2025-09-23', 88.2, 'SUR', 1000, 'RUB', 59.51),
    ('RU000A108EE1', DATE '2025-09-24', 87.59, 'SUR', 1000, 'RUB', 0),
    ('RU000A108EE1', DATE '2025-09-25', 87.188, 'SUR', 1000, 'RUB', 0.33),
    ('RU000A108EE1', DATE '2025-09-26', 86.885, 'SUR', 1000, 'RUB', 0.66),
    ('RU000A108EE1', DATE '2025-09-29', 86.425, 'SUR', 1000, 'RUB', 1.64),
    ('RU000A108EE1', DATE '2025-09-30', 86.43, 'SUR', 1000, 'RUB', 1.97),
    ('RU000A108EE1', DATE '2025-10-01', 86.549, 'SUR', 1000, 'RUB', 2.3),
    ('RU000A108EE1', DATE '2025-10-02', 86.001, 'SUR', 1000, 'RUB', 2.63),
    ('RU000A108EE1', DATE '2025-10-03', 86.349, 'SUR', 1000, 'RUB', 2.96),
    ('RU000A108EE1', DATE '2025-10-06', 86.1, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A108EE1', DATE '2025-10-07', 86.199, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A108EE1', DATE '2025-10-08', 85.327, 'SUR', 1000, 'RUB', 4.6),
    ('RU000A108EE1', DATE '2025-10-09', 85.8, 'SUR', 1000, 'RUB', 4.93),
    ('RU000A108EE1', DATE '2025-10-10', 85.398, 'SUR', 1000, 'RUB', 5.26),
    ('RU000A108EE1', DATE '2025-10-13', 85.439, 'SUR', 1000, 'RUB', 6.25),
    ('RU000A108EE1', DATE '2025-10-14', 85.24, 'SUR', 1000, 'RUB', 6.58),
    ('RU000A108EE1', DATE '2025-10-15', 85.378, 'SUR', 1000, 'RUB', 6.9),
    ('RU000A108EE1', DATE '2025-10-16', 87.049, 'SUR', 1000, 'RUB', 7.23),
    ('RU000A108EE1', DATE '2025-10-17', 87.8, 'SUR', 1000, 'RUB', 7.56),
    ('RU000A108EE1', DATE '2025-10-20', 87.649, 'SUR', 1000, 'RUB', 8.55),
    ('RU000A108EE1', DATE '2025-10-21', 87, 'SUR', 1000, 'RUB', 8.88),
    ('RU000A108EE1', DATE '2025-10-22', 87.178, 'SUR', 1000, 'RUB', 9.21),
    ('RU000A108EE1', DATE '2025-10-23', 86.46, 'SUR', 1000, 'RUB', 9.53),
    ('RU000A108EE1', DATE '2025-10-24', 86.343, 'SUR', 1000, 'RUB', 9.86),
    ('RU000A108EE1', DATE '2025-10-27', 85.445, 'SUR', 1000, 'RUB', 10.85),
    ('RU000A108EE1', DATE '2025-10-28', 86.094, 'SUR', 1000, 'RUB', 11.18),
    ('RU000A108EE1', DATE '2025-10-29', 86.7, 'SUR', 1000, 'RUB', 11.51),
    ('RU000A108EE1', DATE '2025-10-30', 87.496, 'SUR', 1000, 'RUB', 11.84),
    ('RU000A108EE1', DATE '2025-10-31', 87.3, 'SUR', 1000, 'RUB', 12.17),
    ('RU000A108EE1', DATE '2025-11-01', 87.304, 'SUR', 1000, 'RUB', 12.49),
    ('RU000A108EE1', DATE '2025-11-03', 87.647, 'SUR', 1000, 'RUB', 13.15),
    ('RU000A108EE1', DATE '2025-11-05', 87.599, 'SUR', 1000, 'RUB', 13.81),
    ('RU000A108EE1', DATE '2025-11-06', 87.539, 'SUR', 1000, 'RUB', 14.14),
    ('RU000A108EE1', DATE '2025-11-07', 87.38, 'SUR', 1000, 'RUB', 14.47),
    ('RU000A108EE1', DATE '2025-11-10', 87.994, 'SUR', 1000, 'RUB', 15.45),
    ('RU000A108EE1', DATE '2025-11-11', 88.799, 'SUR', 1000, 'RUB', 15.78),
    ('RU000A108EE1', DATE '2025-11-12', 89.048, 'SUR', 1000, 'RUB', 16.11),
    ('RU000A108EE1', DATE '2025-11-13', 89.146, 'SUR', 1000, 'RUB', 16.44),
    ('RU000A108EE1', DATE '2025-11-14', 88.812, 'SUR', 1000, 'RUB', 16.77),
    ('RU000A108EE1', DATE '2025-11-17', 88.798, 'SUR', 1000, 'RUB', 17.75),
    ('RU000A108EE1', DATE '2025-11-18', 88.72, 'SUR', 1000, 'RUB', 18.08),
    ('RU000A108EE1', DATE '2025-11-19', 89.103, 'SUR', 1000, 'RUB', 18.41),
    ('RU000A108EE1', DATE '2025-11-20', 88.87, 'SUR', 1000, 'RUB', 18.74),
    ('RU000A108EE1', DATE '2025-11-21', 89.097, 'SUR', 1000, 'RUB', 19.07),
    ('RU000A108EE1', DATE '2025-11-24', 88.848, 'SUR', 1000, 'RUB', 20.06),
    ('RU000A108EE1', DATE '2025-11-25', 88.6, 'SUR', 1000, 'RUB', 20.39),
    ('RU000A108EE1', DATE '2025-11-26', 88.194, 'SUR', 1000, 'RUB', 20.71),
    ('RU000A108EE1', DATE '2025-11-27', 88.089, 'SUR', 1000, 'RUB', 21.04),
    ('RU000A108EE1', DATE '2025-11-28', 88.45, 'SUR', 1000, 'RUB', 21.37),
    ('RU000A108EE1', DATE '2025-12-01', 88.2, 'SUR', 1000, 'RUB', 22.36),
    ('RU000A108EE1', DATE '2025-12-02', 88.22, 'SUR', 1000, 'RUB', 22.69),
    ('RU000A108EE1', DATE '2025-12-03', 88.576, 'SUR', 1000, 'RUB', 23.02),
    ('RU000A108EE1', DATE '2025-12-04', 88.795, 'SUR', 1000, 'RUB', 23.34),
    ('RU000A108EE1', DATE '2025-12-05', 88.999, 'SUR', 1000, 'RUB', 23.67),
    ('RU000A108EE1', DATE '2025-12-08', 88.949, 'SUR', 1000, 'RUB', 24.66),
    ('RU000A108EE1', DATE '2025-12-09', 88.801, 'SUR', 1000, 'RUB', 24.99),
    ('RU000A108EE1', DATE '2025-12-10', 88.851, 'SUR', 1000, 'RUB', 25.32),
    ('RU000A108EE1', DATE '2025-12-11', 89.245, 'SUR', 1000, 'RUB', 25.65),
    ('RU000A108EE1', DATE '2025-12-12', 89.387, 'SUR', 1000, 'RUB', 25.97),
    ('RU000A108EE1', DATE '2025-12-15', 89.198, 'SUR', 1000, 'RUB', 26.96),
    ('RU000A108EE1', DATE '2025-12-16', 89.178, 'SUR', 1000, 'RUB', 27.29),
    ('RU000A108EE1', DATE '2025-12-17', 89, 'SUR', 1000, 'RUB', 27.62),
    ('RU000A108EE1', DATE '2025-12-18', 89.299, 'SUR', 1000, 'RUB', 27.95),
    ('RU000A108EE1', DATE '2025-12-19', 89.24, 'SUR', 1000, 'RUB', 28.28),
    ('RU000A108EE1', DATE '2025-12-22', 88.8, 'SUR', 1000, 'RUB', 29.26),
    ('RU000A108EE1', DATE '2025-12-23', 88.447, 'SUR', 1000, 'RUB', 29.59),
    ('RU000A108EE1', DATE '2025-12-24', 88.28, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A108EE1', DATE '2025-12-25', 87.898, 'SUR', 1000, 'RUB', 30.25),
    ('RU000A108EE1', DATE '2025-12-26', 87.8, 'SUR', 1000, 'RUB', 30.58),
    ('RU000A108EE1', DATE '2025-12-29', 87.65, 'SUR', 1000, 'RUB', 31.56),
    ('RU000A108EE1', DATE '2025-12-30', 88.6, 'SUR', 1000, 'RUB', 31.89),
    ('RU000A10BVH7', DATE '2025-07-03', 86.3, 'SUR', 1000, 'RUB', 2.63),
    ('RU000A10BVH7', DATE '2025-07-04', 86.149, 'SUR', 1000, 'RUB', 2.96),
    ('RU000A10BVH7', DATE '2025-07-07', 86.299, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A10BVH7', DATE '2025-07-08', 86.2, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A10BVH7', DATE '2025-07-09', 86.03, 'SUR', 1000, 'RUB', 4.6),
    ('RU000A10BVH7', DATE '2025-07-10', 86.25, 'SUR', 1000, 'RUB', 4.93),
    ('RU000A10BVH7', DATE '2025-07-11', 86.189, 'SUR', 1000, 'RUB', 5.26),
    ('RU000A10BVH7', DATE '2025-07-14', 86.3, 'SUR', 1000, 'RUB', 6.25),
    ('RU000A10BVH7', DATE '2025-07-15', 87.842, 'SUR', 1000, 'RUB', 6.58),
    ('RU000A10BVH7', DATE '2025-07-16', 88.649, 'SUR', 1000, 'RUB', 6.9),
    ('RU000A10BVH7', DATE '2025-07-17', 89.31, 'SUR', 1000, 'RUB', 7.23),
    ('RU000A10BVH7', DATE '2025-07-18', 89.487, 'SUR', 1000, 'RUB', 7.56),
    ('RU000A10BVH7', DATE '2025-07-21', 89.5, 'SUR', 1000, 'RUB', 8.55),
    ('RU000A10BVH7', DATE '2025-07-22', 89.195, 'SUR', 1000, 'RUB', 8.88),
    ('RU000A10BVH7', DATE '2025-07-23', 89.255, 'SUR', 1000, 'RUB', 9.21),
    ('RU000A10BVH7', DATE '2025-07-24', 89.515, 'SUR', 1000, 'RUB', 9.53),
    ('RU000A10BVH7', DATE '2025-07-25', 89.927, 'SUR', 1000, 'RUB', 9.86),
    ('RU000A10BVH7', DATE '2025-07-28', 89.75, 'SUR', 1000, 'RUB', 10.85),
    ('RU000A10BVH7', DATE '2025-07-29', 89.5, 'SUR', 1000, 'RUB', 11.18),
    ('RU000A10BVH7', DATE '2025-07-30', 89.688, 'SUR', 1000, 'RUB', 11.51),
    ('RU000A10BVH7', DATE '2025-07-31', 89.648, 'SUR', 1000, 'RUB', 11.84),
    ('RU000A10BVH7', DATE '2025-08-01', 89.3, 'SUR', 1000, 'RUB', 12.17),
    ('RU000A10BVH7', DATE '2025-08-04', 89, 'SUR', 1000, 'RUB', 13.15),
    ('RU000A10BVH7', DATE '2025-08-05', 88.9, 'SUR', 1000, 'RUB', 13.48),
    ('RU000A10BVH7', DATE '2025-08-06', 89, 'SUR', 1000, 'RUB', 13.81),
    ('RU000A10BVH7', DATE '2025-08-07', 90.05, 'SUR', 1000, 'RUB', 14.14),
    ('RU000A10BVH7', DATE '2025-08-08', 90.739, 'SUR', 1000, 'RUB', 14.47),
    ('RU000A10BVH7', DATE '2025-08-11', 91.147, 'SUR', 1000, 'RUB', 15.45),
    ('RU000A10BVH7', DATE '2025-08-12', 90.994, 'SUR', 1000, 'RUB', 15.78),
    ('RU000A10BVH7', DATE '2025-08-13', 90.997, 'SUR', 1000, 'RUB', 16.11),
    ('RU000A10BVH7', DATE '2025-08-14', 91.148, 'SUR', 1000, 'RUB', 16.44),
    ('RU000A10BVH7', DATE '2025-08-15', 91.989, 'SUR', 1000, 'RUB', 16.77),
    ('RU000A10BVH7', DATE '2025-08-18', 91.75, 'SUR', 1000, 'RUB', 17.75),
    ('RU000A10BVH7', DATE '2025-08-19', 91.795, 'SUR', 1000, 'RUB', 18.08),
    ('RU000A10BVH7', DATE '2025-08-20', 91.24, 'SUR', 1000, 'RUB', 18.41),
    ('RU000A10BVH7', DATE '2025-08-21', 90.84, 'SUR', 1000, 'RUB', 18.74),
    ('RU000A10BVH7', DATE '2025-08-22', 91.095, 'SUR', 1000, 'RUB', 19.07),
    ('RU000A10BVH7', DATE '2025-08-25', 90.7, 'SUR', 1000, 'RUB', 20.06),
    ('RU000A10BVH7', DATE '2025-08-26', 90.5, 'SUR', 1000, 'RUB', 20.39),
    ('RU000A10BVH7', DATE '2025-08-27', 90.698, 'SUR', 1000, 'RUB', 20.71),
    ('RU000A10BVH7', DATE '2025-08-28', 90.352, 'SUR', 1000, 'RUB', 21.04),
    ('RU000A10BVH7', DATE '2025-08-29', 90.4, 'SUR', 1000, 'RUB', 21.37),
    ('RU000A10BVH7', DATE '2025-09-01', 90.457, 'SUR', 1000, 'RUB', 22.36),
    ('RU000A10BVH7', DATE '2025-09-02', 90.3, 'SUR', 1000, 'RUB', 22.69),
    ('RU000A10BVH7', DATE '2025-09-03', 91.15, 'SUR', 1000, 'RUB', 23.02),
    ('RU000A10BVH7', DATE '2025-09-04', 91.353, 'SUR', 1000, 'RUB', 23.34),
    ('RU000A10BVH7', DATE '2025-09-05', 91.5, 'SUR', 1000, 'RUB', 23.67),
    ('RU000A10BVH7', DATE '2025-09-08', 91.7, 'SUR', 1000, 'RUB', 24.66),
    ('RU000A10BVH7', DATE '2025-09-09', 91.2, 'SUR', 1000, 'RUB', 24.99),
    ('RU000A10BVH7', DATE '2025-09-10', 91.06, 'SUR', 1000, 'RUB', 25.32),
    ('RU000A10BVH7', DATE '2025-09-11', 90.653, 'SUR', 1000, 'RUB', 25.65),
    ('RU000A10BVH7', DATE '2025-09-12', 89.8, 'SUR', 1000, 'RUB', 25.97),
    ('RU000A10BVH7', DATE '2025-09-15', 89.641, 'SUR', 1000, 'RUB', 26.96),
    ('RU000A10BVH7', DATE '2025-09-16', 88.88, 'SUR', 1000, 'RUB', 27.29),
    ('RU000A10BVH7', DATE '2025-09-17', 88.85, 'SUR', 1000, 'RUB', 27.62),
    ('RU000A10BVH7', DATE '2025-09-18', 88.42, 'SUR', 1000, 'RUB', 27.95),
    ('RU000A10BVH7', DATE '2025-09-19', 87.5, 'SUR', 1000, 'RUB', 28.28),
    ('RU000A10BVH7', DATE '2025-09-22', 87.7, 'SUR', 1000, 'RUB', 29.26),
    ('RU000A10BVH7', DATE '2025-09-23', 87.49, 'SUR', 1000, 'RUB', 29.59),
    ('RU000A10BVH7', DATE '2025-09-24', 86.85, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A10BVH7', DATE '2025-09-25', 86.182, 'SUR', 1000, 'RUB', 30.25),
    ('RU000A10BVH7', DATE '2025-09-26', 86.151, 'SUR', 1000, 'RUB', 30.58),
    ('RU000A10BVH7', DATE '2025-09-29', 85.75, 'SUR', 1000, 'RUB', 31.56),
    ('RU000A10BVH7', DATE '2025-09-30', 85.301, 'SUR', 1000, 'RUB', 31.89),
    ('RU000A10BVH7', DATE '2025-10-01', 85.388, 'SUR', 1000, 'RUB', 32.22),
    ('RU000A10BVH7', DATE '2025-10-02', 85.11, 'SUR', 1000, 'RUB', 32.55),
    ('RU000A10BVH7', DATE '2025-10-03', 85.39, 'SUR', 1000, 'RUB', 32.88),
    ('RU000A10BVH7', DATE '2025-10-06', 85.29, 'SUR', 1000, 'RUB', 33.87),
    ('RU000A10BVH7', DATE '2025-10-07', 85.299, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A10BVH7', DATE '2025-10-08', 84.599, 'SUR', 1000, 'RUB', 34.52),
    ('RU000A10BVH7', DATE '2025-10-09', 85.05, 'SUR', 1000, 'RUB', 34.85),
    ('RU000A10BVH7', DATE '2025-10-10', 84.47, 'SUR', 1000, 'RUB', 35.18),
    ('RU000A10BVH7', DATE '2025-10-13', 84.599, 'SUR', 1000, 'RUB', 36.17),
    ('RU000A10BVH7', DATE '2025-10-14', 84.549, 'SUR', 1000, 'RUB', 36.5),
    ('RU000A10BVH7', DATE '2025-10-15', 84.6, 'SUR', 1000, 'RUB', 36.82),
    ('RU000A10BVH7', DATE '2025-10-16', 86.187, 'SUR', 1000, 'RUB', 37.15),
    ('RU000A10BVH7', DATE '2025-10-17', 87, 'SUR', 1000, 'RUB', 37.48),
    ('RU000A10BVH7', DATE '2025-10-20', 86.949, 'SUR', 1000, 'RUB', 38.47),
    ('RU000A10BVH7', DATE '2025-10-21', 86, 'SUR', 1000, 'RUB', 38.8),
    ('RU000A10BVH7', DATE '2025-10-22', 86.093, 'SUR', 1000, 'RUB', 39.13),
    ('RU000A10BVH7', DATE '2025-10-23', 85.349, 'SUR', 1000, 'RUB', 39.45),
    ('RU000A10BVH7', DATE '2025-10-24', 85.24, 'SUR', 1000, 'RUB', 39.78),
    ('RU000A10BVH7', DATE '2025-10-27', 84.63, 'SUR', 1000, 'RUB', 40.77),
    ('RU000A10BVH7', DATE '2025-10-28', 85.149, 'SUR', 1000, 'RUB', 41.1),
    ('RU000A10BVH7', DATE '2025-10-29', 86.001, 'SUR', 1000, 'RUB', 41.43),
    ('RU000A10BVH7', DATE '2025-10-30', 86.547, 'SUR', 1000, 'RUB', 41.76),
    ('RU000A10BVH7', DATE '2025-10-31', 86.093, 'SUR', 1000, 'RUB', 42.09),
    ('RU000A10BVH7', DATE '2025-11-01', 86.316, 'SUR', 1000, 'RUB', 42.41),
    ('RU000A10BVH7', DATE '2025-11-03', 86.876, 'SUR', 1000, 'RUB', 43.07),
    ('RU000A10BVH7', DATE '2025-11-05', 86.799, 'SUR', 1000, 'RUB', 43.73),
    ('RU000A10BVH7', DATE '2025-11-06', 86.645, 'SUR', 1000, 'RUB', 44.06),
    ('RU000A10BVH7', DATE '2025-11-07', 86.59, 'SUR', 1000, 'RUB', 44.39),
    ('RU000A10BVH7', DATE '2025-11-10', 86.9, 'SUR', 1000, 'RUB', 45.37),
    ('RU000A10BVH7', DATE '2025-11-11', 87.866, 'SUR', 1000, 'RUB', 45.7),
    ('RU000A10BVH7', DATE '2025-11-12', 88.2, 'SUR', 1000, 'RUB', 46.03),
    ('RU000A10BVH7', DATE '2025-11-13', 88.217, 'SUR', 1000, 'RUB', 46.36),
    ('RU000A10BVH7', DATE '2025-11-14', 88.149, 'SUR', 1000, 'RUB', 46.69),
    ('RU000A10BVH7', DATE '2025-11-17', 87.847, 'SUR', 1000, 'RUB', 47.67),
    ('RU000A10BVH7', DATE '2025-11-18', 87.59, 'SUR', 1000, 'RUB', 48),
    ('RU000A10BVH7', DATE '2025-11-19', 88.1, 'SUR', 1000, 'RUB', 48.33),
    ('RU000A10BVH7', DATE '2025-11-20', 88.04, 'SUR', 1000, 'RUB', 48.66),
    ('RU000A10BVH7', DATE '2025-11-21', 88.45, 'SUR', 1000, 'RUB', 48.99),
    ('RU000A10BVH7', DATE '2025-11-24', 88.248, 'SUR', 1000, 'RUB', 49.98),
    ('RU000A10BVH7', DATE '2025-11-25', 87.9, 'SUR', 1000, 'RUB', 50.31),
    ('RU000A10BVH7', DATE '2025-11-26', 87.604, 'SUR', 1000, 'RUB', 50.63),
    ('RU000A10BVH7', DATE '2025-11-27', 87.16, 'SUR', 1000, 'RUB', 50.96),
    ('RU000A10BVH7', DATE '2025-11-28', 87.65, 'SUR', 1000, 'RUB', 51.29),
    ('RU000A10BVH7', DATE '2025-12-01', 87.4, 'SUR', 1000, 'RUB', 52.28),
    ('RU000A10BVH7', DATE '2025-12-02', 87.5, 'SUR', 1000, 'RUB', 52.61),
    ('RU000A10BVH7', DATE '2025-12-03', 87.5, 'SUR', 1000, 'RUB', 52.94),
    ('RU000A10BVH7', DATE '2025-12-04', 87.951, 'SUR', 1000, 'RUB', 53.26),
    ('RU000A10BVH7', DATE '2025-12-05', 88.251, 'SUR', 1000, 'RUB', 53.59),
    ('RU000A10BVH7', DATE '2025-12-08', 88.024, 'SUR', 1000, 'RUB', 54.58),
    ('RU000A10BVH7', DATE '2025-12-09', 87.823, 'SUR', 1000, 'RUB', 54.91),
    ('RU000A10BVH7', DATE '2025-12-10', 87.95, 'SUR', 1000, 'RUB', 55.24),
    ('RU000A10BVH7', DATE '2025-12-11', 88.602, 'SUR', 1000, 'RUB', 55.57),
    ('RU000A10BVH7', DATE '2025-12-12', 88.882, 'SUR', 1000, 'RUB', 55.89),
    ('RU000A10BVH7', DATE '2025-12-15', 88.699, 'SUR', 1000, 'RUB', 56.88),
    ('RU000A10BVH7', DATE '2025-12-16', 88.5, 'SUR', 1000, 'RUB', 57.21),
    ('RU000A10BVH7', DATE '2025-12-17', 88.754, 'SUR', 1000, 'RUB', 57.54),
    ('RU000A10BVH7', DATE '2025-12-18', 88.664, 'SUR', 1000, 'RUB', 57.87),
    ('RU000A10BVH7', DATE '2025-12-19', 88.204, 'SUR', 1000, 'RUB', 58.2),
    ('RU000A10BVH7', DATE '2025-12-22', 87.854, 'SUR', 1000, 'RUB', 59.18),
    ('RU000A10BVH7', DATE '2025-12-23', 87.49, 'SUR', 1000, 'RUB', 59.51),
    ('RU000A10BVH7', DATE '2025-12-24', 87.324, 'SUR', 1000, 'RUB', 0),
    ('RU000A10BVH7', DATE '2025-12-25', 87.079, 'SUR', 1000, 'RUB', 0.33),
    ('RU000A10BVH7', DATE '2025-12-26', 87.28, 'SUR', 1000, 'RUB', 0.66),
    ('RU000A10BVH7', DATE '2025-12-29', 87.294, 'SUR', 1000, 'RUB', 1.64),
    ('RU000A10BVH7', DATE '2025-12-30', 87.3, 'SUR', 1000, 'RUB', 1.97),
    ('RU000A10D517', DATE '2025-11-20', 93.3, 'SUR', 1000, 'RUB', 10.33),
    ('RU000A10D517', DATE '2025-11-21', 93.827, 'SUR', 1000, 'RUB', 10.68),
    ('RU000A10D517', DATE '2025-11-24', 93.6, 'SUR', 1000, 'RUB', 11.75),
    ('RU000A10D517', DATE '2025-11-25', 93.185, 'SUR', 1000, 'RUB', 12.11),
    ('RU000A10D517', DATE '2025-11-26', 93.239, 'SUR', 1000, 'RUB', 12.47),
    ('RU000A10D517', DATE '2025-11-27', 92.998, 'SUR', 1000, 'RUB', 12.82),
    ('RU000A10D517', DATE '2025-11-28', 93.145, 'SUR', 1000, 'RUB', 13.18),
    ('RU000A10D517', DATE '2025-12-01', 93, 'SUR', 1000, 'RUB', 14.25),
    ('RU000A10D517', DATE '2025-12-02', 92.599, 'SUR', 1000, 'RUB', 14.6),
    ('RU000A10D517', DATE '2025-12-03', 92.72, 'SUR', 1000, 'RUB', 14.96),
    ('RU000A10D517', DATE '2025-12-04', 93.228, 'SUR', 1000, 'RUB', 15.31),
    ('RU000A10D517', DATE '2025-12-05', 93.58, 'SUR', 1000, 'RUB', 15.67),
    ('RU000A10D517', DATE '2025-12-08', 93.15, 'SUR', 1000, 'RUB', 16.74),
    ('RU000A10D517', DATE '2025-12-09', 93.079, 'SUR', 1000, 'RUB', 17.1),
    ('RU000A10D517', DATE '2025-12-10', 93.25, 'SUR', 1000, 'RUB', 17.45),
    ('RU000A10D517', DATE '2025-12-11', 93.93, 'SUR', 1000, 'RUB', 17.81),
    ('RU000A10D517', DATE '2025-12-12', 94.2, 'SUR', 1000, 'RUB', 18.16),
    ('RU000A10D517', DATE '2025-12-15', 93.75, 'SUR', 1000, 'RUB', 19.23),
    ('RU000A10D517', DATE '2025-12-16', 93.663, 'SUR', 1000, 'RUB', 19.59),
    ('RU000A10D517', DATE '2025-12-17', 93.59, 'SUR', 1000, 'RUB', 19.94),
    ('RU000A10D517', DATE '2025-12-18', 93.95, 'SUR', 1000, 'RUB', 20.3),
    ('RU000A10D517', DATE '2025-12-19', 93.6, 'SUR', 1000, 'RUB', 20.66),
    ('RU000A10D517', DATE '2025-12-22', 93.21, 'SUR', 1000, 'RUB', 21.73),
    ('RU000A10D517', DATE '2025-12-23', 93.099, 'SUR', 1000, 'RUB', 22.08),
    ('RU000A10D517', DATE '2025-12-24', 93.07, 'SUR', 1000, 'RUB', 22.44),
    ('RU000A10D517', DATE '2025-12-25', 92.947, 'SUR', 1000, 'RUB', 22.79),
    ('RU000A10D517', DATE '2025-12-26', 92.847, 'SUR', 1000, 'RUB', 23.15),
    ('RU000A10D517', DATE '2025-12-29', 93, 'SUR', 1000, 'RUB', 24.22),
    ('RU000A10D517', DATE '2025-12-30', 92.959, 'SUR', 1000, 'RUB', 24.57),
    ('RU000A10D533', DATE '2025-11-27', 92.65, 'SUR', 1000, 'RUB', 12.82),
    ('RU000A10D533', DATE '2025-11-28', 93.099, 'SUR', 1000, 'RUB', 13.18),
    ('RU000A10D533', DATE '2025-12-01', 93.19, 'SUR', 1000, 'RUB', 14.25),
    ('RU000A10D533', DATE '2025-12-02', 93, 'SUR', 1000, 'RUB', 14.6),
    ('RU000A10D533', DATE '2025-12-03', 93.277, 'SUR', 1000, 'RUB', 14.96),
    ('RU000A10D533', DATE '2025-12-04', 94.049, 'SUR', 1000, 'RUB', 15.31),
    ('RU000A10D533', DATE '2025-12-05', 94.55, 'SUR', 1000, 'RUB', 15.67),
    ('RU000A10D533', DATE '2025-12-08', 93.9, 'SUR', 1000, 'RUB', 16.74),
    ('RU000A10D533', DATE '2025-12-09', 93.189, 'SUR', 1000, 'RUB', 17.1),
    ('RU000A10D533', DATE '2025-12-10', 93.071, 'SUR', 1000, 'RUB', 17.45),
    ('RU000A10D533', DATE '2025-12-11', 93.7, 'SUR', 1000, 'RUB', 17.81),
    ('RU000A10D533', DATE '2025-12-12', 94.01, 'SUR', 1000, 'RUB', 18.16),
    ('RU000A10D533', DATE '2025-12-15', 93.799, 'SUR', 1000, 'RUB', 19.23),
    ('RU000A10D533', DATE '2025-12-16', 93.69, 'SUR', 1000, 'RUB', 19.59),
    ('RU000A10D533', DATE '2025-12-17', 93.8, 'SUR', 1000, 'RUB', 19.94),
    ('RU000A10D533', DATE '2025-12-18', 94.129, 'SUR', 1000, 'RUB', 20.3),
    ('RU000A10D533', DATE '2025-12-19', 93.744, 'SUR', 1000, 'RUB', 20.66),
    ('RU000A10D533', DATE '2025-12-22', 93.298, 'SUR', 1000, 'RUB', 21.73),
    ('RU000A10D533', DATE '2025-12-23', 93.197, 'SUR', 1000, 'RUB', 22.08),
    ('RU000A10D533', DATE '2025-12-24', 93.249, 'SUR', 1000, 'RUB', 22.44),
    ('RU000A10D533', DATE '2025-12-25', 93.078, 'SUR', 1000, 'RUB', 22.79),
    ('RU000A10D533', DATE '2025-12-26', 92.963, 'SUR', 1000, 'RUB', 23.15),
    ('RU000A10D533', DATE '2025-12-29', 93.077, 'SUR', 1000, 'RUB', 24.22),
    ('RU000A10D533', DATE '2025-12-30', 93.139, 'SUR', 1000, 'RUB', 24.57)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    436 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 436;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2025, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2025, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2025, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2025, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
