-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 272

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A108EE1', DATE '2026-01-05', 88.496, 'SUR', 1000, 'RUB', 33.87),
    ('RU000A108EE1', DATE '2026-01-06', 88.6, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A108EE1', DATE '2026-01-08', 88.584, 'SUR', 1000, 'RUB', 34.85),
    ('RU000A108EE1', DATE '2026-01-09', 88.578, 'SUR', 1000, 'RUB', 35.18),
    ('RU000A108EE1', DATE '2026-01-12', 87.487, 'SUR', 1000, 'RUB', 36.17),
    ('RU000A108EE1', DATE '2026-01-13', 87.2, 'SUR', 1000, 'RUB', 36.5),
    ('RU000A108EE1', DATE '2026-01-14', 87.299, 'SUR', 1000, 'RUB', 36.82),
    ('RU000A108EE1', DATE '2026-01-15', 87.18, 'SUR', 1000, 'RUB', 37.15),
    ('RU000A108EE1', DATE '2026-01-16', 87.299, 'SUR', 1000, 'RUB', 37.48),
    ('RU000A108EE1', DATE '2026-01-19', 87.24, 'SUR', 1000, 'RUB', 38.47),
    ('RU000A108EE1', DATE '2026-01-20', 87.157, 'SUR', 1000, 'RUB', 38.8),
    ('RU000A108EE1', DATE '2026-01-21', 87.13, 'SUR', 1000, 'RUB', 39.13),
    ('RU000A108EE1', DATE '2026-01-22', 87.346, 'SUR', 1000, 'RUB', 39.45),
    ('RU000A108EE1', DATE '2026-01-23', 87.297, 'SUR', 1000, 'RUB', 39.78),
    ('RU000A108EE1', DATE '2026-01-26', 86.994, 'SUR', 1000, 'RUB', 40.77),
    ('RU000A108EE1', DATE '2026-01-27', 87, 'SUR', 1000, 'RUB', 41.1),
    ('RU000A108EE1', DATE '2026-01-28', 87.01, 'SUR', 1000, 'RUB', 41.43),
    ('RU000A108EE1', DATE '2026-01-29', 87.273, 'SUR', 1000, 'RUB', 41.76),
    ('RU000A108EE1', DATE '2026-01-30', 87.5, 'SUR', 1000, 'RUB', 42.09),
    ('RU000A108EE1', DATE '2026-02-02', 87.1, 'SUR', 1000, 'RUB', 43.07),
    ('RU000A108EE1', DATE '2026-02-03', 87.159, 'SUR', 1000, 'RUB', 43.4),
    ('RU000A108EE1', DATE '2026-02-04', 87.198, 'SUR', 1000, 'RUB', 43.73),
    ('RU000A108EE1', DATE '2026-02-05', 86.996, 'SUR', 1000, 'RUB', 44.06),
    ('RU000A108EE1', DATE '2026-02-06', 86.596, 'SUR', 1000, 'RUB', 44.39),
    ('RU000A108EE1', DATE '2026-02-09', 86.3, 'SUR', 1000, 'RUB', 45.37),
    ('RU000A108EE1', DATE '2026-02-10', 86.046, 'SUR', 1000, 'RUB', 45.7),
    ('RU000A108EE1', DATE '2026-02-11', 86.419, 'SUR', 1000, 'RUB', 46.03),
    ('RU000A108EE1', DATE '2026-02-12', 87.15, 'SUR', 1000, 'RUB', 46.36),
    ('RU000A108EE1', DATE '2026-02-13', 88.198, 'SUR', 1000, 'RUB', 46.69),
    ('RU000A108EE1', DATE '2026-02-16', 88.113, 'SUR', 1000, 'RUB', 47.67),
    ('RU000A108EE1', DATE '2026-02-17', 88.314, 'SUR', 1000, 'RUB', 48),
    ('RU000A108EE1', DATE '2026-02-18', 88.7, 'SUR', 1000, 'RUB', 48.33),
    ('RU000A108EE1', DATE '2026-02-19', 88.738, 'SUR', 1000, 'RUB', 48.66),
    ('RU000A108EE1', DATE '2026-02-20', 88.4, 'SUR', 1000, 'RUB', 48.99),
    ('RU000A108EE1', DATE '2026-02-24', 88.4, 'SUR', 1000, 'RUB', 50.31),
    ('RU000A108EE1', DATE '2026-02-25', 88.249, 'SUR', 1000, 'RUB', 50.63),
    ('RU000A108EE1', DATE '2026-02-26', 88.098, 'SUR', 1000, 'RUB', 50.96),
    ('RU000A108EE1', DATE '2026-02-27', 88.141, 'SUR', 1000, 'RUB', 51.29),
    ('RU000A108EE1', DATE '2026-03-02', 88.012, 'SUR', 1000, 'RUB', 52.28),
    ('RU000A108EE1', DATE '2026-03-03', 87.905, 'SUR', 1000, 'RUB', 52.61),
    ('RU000A108EE1', DATE '2026-03-04', 87.889, 'SUR', 1000, 'RUB', 52.94),
    ('RU000A108EE1', DATE '2026-03-05', 87.95, 'SUR', 1000, 'RUB', 53.26),
    ('RU000A108EE1', DATE '2026-03-06', 87.984, 'SUR', 1000, 'RUB', 53.59),
    ('RU000A108EE1', DATE '2026-03-09', 88.17, 'SUR', 1000, 'RUB', 54.58),
    ('RU000A108EE1', DATE '2026-03-10', 87.999, 'SUR', 1000, 'RUB', 54.91),
    ('RU000A108EE1', DATE '2026-03-11', 88.149, 'SUR', 1000, 'RUB', 55.24),
    ('RU000A108EE1', DATE '2026-03-12', 88.715, 'SUR', 1000, 'RUB', 55.57),
    ('RU000A108EE1', DATE '2026-03-13', 89.499, 'SUR', 1000, 'RUB', 55.89),
    ('RU000A108EE1', DATE '2026-03-16', 89.35, 'SUR', 1000, 'RUB', 56.88),
    ('RU000A108EE1', DATE '2026-03-17', 89.1, 'SUR', 1000, 'RUB', 57.21),
    ('RU000A108EE1', DATE '2026-03-18', 89.031, 'SUR', 1000, 'RUB', 57.54),
    ('RU000A108EE1', DATE '2026-03-19', 88.995, 'SUR', 1000, 'RUB', 57.87),
    ('RU000A108EE1', DATE '2026-03-20', 88.97, 'SUR', 1000, 'RUB', 58.2),
    ('RU000A108EE1', DATE '2026-03-23', 88.746, 'SUR', 1000, 'RUB', 59.18),
    ('RU000A108EE1', DATE '2026-03-24', 88.799, 'SUR', 1000, 'RUB', 59.51),
    ('RU000A108EE1', DATE '2026-03-25', 88.85, 'SUR', 1000, 'RUB', 0),
    ('RU000A108EE1', DATE '2026-03-26', 88.614, 'SUR', 1000, 'RUB', 0.33),
    ('RU000A108EE1', DATE '2026-03-27', 88.598, 'SUR', 1000, 'RUB', 0.66),
    ('RU000A108EE1', DATE '2026-03-30', 88.57, 'SUR', 1000, 'RUB', 1.64),
    ('RU000A108EE1', DATE '2026-03-31', 88.547, 'SUR', 1000, 'RUB', 1.97),
    ('RU000A108EE1', DATE '2026-04-01', 88.531, 'SUR', 1000, 'RUB', 2.3),
    ('RU000A108EE1', DATE '2026-04-02', 88.55, 'SUR', 1000, 'RUB', 2.63),
    ('RU000A108EE1', DATE '2026-04-03', 88.42, 'SUR', 1000, 'RUB', 2.96),
    ('RU000A108EE1', DATE '2026-04-06', 88.439, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A108EE1', DATE '2026-04-07', 88.316, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A108EE1', DATE '2026-04-08', 88.33, 'SUR', 1000, 'RUB', 4.6),
    ('RU000A108EE1', DATE '2026-04-09', 88.074, 'SUR', 1000, 'RUB', 4.93),
    ('RU000A108EE1', DATE '2026-04-10', 88.391, 'SUR', 1000, 'RUB', 5.26),
    ('RU000A10BVH7', DATE '2026-01-05', 87.548, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A10BVH7', DATE '2026-01-06', 87.893, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A10BVH7', DATE '2026-01-08', 87.798, 'SUR', 1000, 'RUB', 4.93),
    ('RU000A10BVH7', DATE '2026-01-09', 87.831, 'SUR', 1000, 'RUB', 5.26),
    ('RU000A10BVH7', DATE '2026-01-12', 86.85, 'SUR', 1000, 'RUB', 6.25),
    ('RU000A10BVH7', DATE '2026-01-13', 86.54, 'SUR', 1000, 'RUB', 6.58),
    ('RU000A10BVH7', DATE '2026-01-14', 86.699, 'SUR', 1000, 'RUB', 6.9),
    ('RU000A10BVH7', DATE '2026-01-15', 86.648, 'SUR', 1000, 'RUB', 7.23),
    ('RU000A10BVH7', DATE '2026-01-16', 86.62, 'SUR', 1000, 'RUB', 7.56),
    ('RU000A10BVH7', DATE '2026-01-19', 86.601, 'SUR', 1000, 'RUB', 8.55),
    ('RU000A10BVH7', DATE '2026-01-20', 86.4, 'SUR', 1000, 'RUB', 8.88),
    ('RU000A10BVH7', DATE '2026-01-21', 86.299, 'SUR', 1000, 'RUB', 9.21),
    ('RU000A10BVH7', DATE '2026-01-22', 86.599, 'SUR', 1000, 'RUB', 9.53),
    ('RU000A10BVH7', DATE '2026-01-23', 86.503, 'SUR', 1000, 'RUB', 9.86),
    ('RU000A10BVH7', DATE '2026-01-26', 86.2, 'SUR', 1000, 'RUB', 10.85),
    ('RU000A10BVH7', DATE '2026-01-27', 86.179, 'SUR', 1000, 'RUB', 11.18),
    ('RU000A10BVH7', DATE '2026-01-28', 86.13, 'SUR', 1000, 'RUB', 11.51),
    ('RU000A10BVH7', DATE '2026-01-29', 86.419, 'SUR', 1000, 'RUB', 11.84),
    ('RU000A10BVH7', DATE '2026-01-30', 86.357, 'SUR', 1000, 'RUB', 12.17),
    ('RU000A10BVH7', DATE '2026-02-02', 86.15, 'SUR', 1000, 'RUB', 13.15),
    ('RU000A10BVH7', DATE '2026-02-03', 86.15, 'SUR', 1000, 'RUB', 13.48),
    ('RU000A10BVH7', DATE '2026-02-04', 86.18, 'SUR', 1000, 'RUB', 13.81),
    ('RU000A10BVH7', DATE '2026-02-05', 86, 'SUR', 1000, 'RUB', 14.14),
    ('RU000A10BVH7', DATE '2026-02-06', 85.6, 'SUR', 1000, 'RUB', 14.47),
    ('RU000A10BVH7', DATE '2026-02-09', 85.51, 'SUR', 1000, 'RUB', 15.45),
    ('RU000A10BVH7', DATE '2026-02-10', 85.043, 'SUR', 1000, 'RUB', 15.78),
    ('RU000A10BVH7', DATE '2026-02-11', 85.347, 'SUR', 1000, 'RUB', 16.11),
    ('RU000A10BVH7', DATE '2026-02-12', 86.199, 'SUR', 1000, 'RUB', 16.44),
    ('RU000A10BVH7', DATE '2026-02-13', 87.5, 'SUR', 1000, 'RUB', 16.77),
    ('RU000A10BVH7', DATE '2026-02-16', 87.55, 'SUR', 1000, 'RUB', 17.75),
    ('RU000A10BVH7', DATE '2026-02-17', 87.77, 'SUR', 1000, 'RUB', 18.08),
    ('RU000A10BVH7', DATE '2026-02-18', 88.144, 'SUR', 1000, 'RUB', 18.41),
    ('RU000A10BVH7', DATE '2026-02-19', 88.126, 'SUR', 1000, 'RUB', 18.74),
    ('RU000A10BVH7', DATE '2026-02-20', 87.69, 'SUR', 1000, 'RUB', 19.07),
    ('RU000A10BVH7', DATE '2026-02-24', 87.649, 'SUR', 1000, 'RUB', 20.39),
    ('RU000A10BVH7', DATE '2026-02-25', 87.5, 'SUR', 1000, 'RUB', 20.71),
    ('RU000A10BVH7', DATE '2026-02-26', 87.3, 'SUR', 1000, 'RUB', 21.04),
    ('RU000A10BVH7', DATE '2026-02-27', 87.564, 'SUR', 1000, 'RUB', 21.37),
    ('RU000A10BVH7', DATE '2026-03-02', 87.35, 'SUR', 1000, 'RUB', 22.36),
    ('RU000A10BVH7', DATE '2026-03-03', 87.2, 'SUR', 1000, 'RUB', 22.69),
    ('RU000A10BVH7', DATE '2026-03-04', 87.22, 'SUR', 1000, 'RUB', 23.02),
    ('RU000A10BVH7', DATE '2026-03-05', 87.197, 'SUR', 1000, 'RUB', 23.34),
    ('RU000A10BVH7', DATE '2026-03-06', 87.199, 'SUR', 1000, 'RUB', 23.67),
    ('RU000A10BVH7', DATE '2026-03-09', 87.301, 'SUR', 1000, 'RUB', 24.66),
    ('RU000A10BVH7', DATE '2026-03-10', 87.3, 'SUR', 1000, 'RUB', 24.99),
    ('RU000A10BVH7', DATE '2026-03-11', 87.296, 'SUR', 1000, 'RUB', 25.32),
    ('RU000A10BVH7', DATE '2026-03-12', 87.888, 'SUR', 1000, 'RUB', 25.65),
    ('RU000A10BVH7', DATE '2026-03-13', 88.396, 'SUR', 1000, 'RUB', 25.97),
    ('RU000A10BVH7', DATE '2026-03-16', 88.3, 'SUR', 1000, 'RUB', 26.96),
    ('RU000A10BVH7', DATE '2026-03-17', 87.969, 'SUR', 1000, 'RUB', 27.29),
    ('RU000A10BVH7', DATE '2026-03-18', 87.988, 'SUR', 1000, 'RUB', 27.62),
    ('RU000A10BVH7', DATE '2026-03-19', 87.965, 'SUR', 1000, 'RUB', 27.95),
    ('RU000A10BVH7', DATE '2026-03-20', 87.9, 'SUR', 1000, 'RUB', 28.28),
    ('RU000A10BVH7', DATE '2026-03-23', 87.82, 'SUR', 1000, 'RUB', 29.26),
    ('RU000A10BVH7', DATE '2026-03-24', 87.8, 'SUR', 1000, 'RUB', 29.59),
    ('RU000A10BVH7', DATE '2026-03-25', 88, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A10BVH7', DATE '2026-03-26', 87.708, 'SUR', 1000, 'RUB', 30.25),
    ('RU000A10BVH7', DATE '2026-03-27', 87.7, 'SUR', 1000, 'RUB', 30.58),
    ('RU000A10BVH7', DATE '2026-03-30', 87.82, 'SUR', 1000, 'RUB', 31.56),
    ('RU000A10BVH7', DATE '2026-03-31', 87.792, 'SUR', 1000, 'RUB', 31.89),
    ('RU000A10BVH7', DATE '2026-04-01', 87.644, 'SUR', 1000, 'RUB', 32.22),
    ('RU000A10BVH7', DATE '2026-04-02', 87.639, 'SUR', 1000, 'RUB', 32.55),
    ('RU000A10BVH7', DATE '2026-04-03', 87.411, 'SUR', 1000, 'RUB', 32.88),
    ('RU000A10BVH7', DATE '2026-04-06', 87.399, 'SUR', 1000, 'RUB', 33.87),
    ('RU000A10BVH7', DATE '2026-04-07', 87.199, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A10BVH7', DATE '2026-04-08', 87.249, 'SUR', 1000, 'RUB', 34.52),
    ('RU000A10BVH7', DATE '2026-04-09', 87.07, 'SUR', 1000, 'RUB', 34.85),
    ('RU000A10BVH7', DATE '2026-04-10', 87.538, 'SUR', 1000, 'RUB', 35.18),
    ('RU000A10D517', DATE '2026-01-05', 93.335, 'SUR', 1000, 'RUB', 26.71),
    ('RU000A10D517', DATE '2026-01-06', 93.484, 'SUR', 1000, 'RUB', 27.07),
    ('RU000A10D517', DATE '2026-01-08', 93.29, 'SUR', 1000, 'RUB', 27.78),
    ('RU000A10D517', DATE '2026-01-09', 93.24, 'SUR', 1000, 'RUB', 28.14),
    ('RU000A10D517', DATE '2026-01-12', 92.5, 'SUR', 1000, 'RUB', 29.2),
    ('RU000A10D517', DATE '2026-01-13', 91.706, 'SUR', 1000, 'RUB', 29.56),
    ('RU000A10D517', DATE '2026-01-14', 91.693, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A10D517', DATE '2026-01-15', 91.713, 'SUR', 1000, 'RUB', 30.27),
    ('RU000A10D517', DATE '2026-01-16', 91.8, 'SUR', 1000, 'RUB', 30.63),
    ('RU000A10D517', DATE '2026-01-19', 91.8, 'SUR', 1000, 'RUB', 31.7),
    ('RU000A10D517', DATE '2026-01-20', 91.863, 'SUR', 1000, 'RUB', 32.05),
    ('RU000A10D517', DATE '2026-01-21', 91.55, 'SUR', 1000, 'RUB', 32.41),
    ('RU000A10D517', DATE '2026-01-22', 91.838, 'SUR', 1000, 'RUB', 32.77),
    ('RU000A10D517', DATE '2026-01-23', 91.808, 'SUR', 1000, 'RUB', 33.12),
    ('RU000A10D517', DATE '2026-01-26', 91.49, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A10D517', DATE '2026-01-27', 91.321, 'SUR', 1000, 'RUB', 34.55),
    ('RU000A10D517', DATE '2026-01-28', 91.348, 'SUR', 1000, 'RUB', 34.9),
    ('RU000A10D517', DATE '2026-01-29', 91.6, 'SUR', 1000, 'RUB', 35.26),
    ('RU000A10D517', DATE '2026-01-30', 91.541, 'SUR', 1000, 'RUB', 35.62),
    ('RU000A10D517', DATE '2026-02-02', 91.391, 'SUR', 1000, 'RUB', 36.68),
    ('RU000A10D517', DATE '2026-02-03', 91.15, 'SUR', 1000, 'RUB', 37.04),
    ('RU000A10D517', DATE '2026-02-04', 91.189, 'SUR', 1000, 'RUB', 37.4),
    ('RU000A10D517', DATE '2026-02-05', 91.056, 'SUR', 1000, 'RUB', 37.75),
    ('RU000A10D517', DATE '2026-02-06', 90.752, 'SUR', 1000, 'RUB', 38.11),
    ('RU000A10D517', DATE '2026-02-09', 90.698, 'SUR', 1000, 'RUB', 39.18),
    ('RU000A10D517', DATE '2026-02-10', 90.27, 'SUR', 1000, 'RUB', 39.53),
    ('RU000A10D517', DATE '2026-02-11', 90.64, 'SUR', 1000, 'RUB', 39.89),
    ('RU000A10D517', DATE '2026-02-12', 91.35, 'SUR', 1000, 'RUB', 40.25),
    ('RU000A10D517', DATE '2026-02-13', 92.689, 'SUR', 1000, 'RUB', 40.6),
    ('RU000A10D517', DATE '2026-02-16', 92.6, 'SUR', 1000, 'RUB', 41.67),
    ('RU000A10D517', DATE '2026-02-17', 93.071, 'SUR', 1000, 'RUB', 42.03),
    ('RU000A10D517', DATE '2026-02-18', 93.294, 'SUR', 1000, 'RUB', 42.38),
    ('RU000A10D517', DATE '2026-02-19', 93.24, 'SUR', 1000, 'RUB', 42.74),
    ('RU000A10D517', DATE '2026-02-20', 92.9, 'SUR', 1000, 'RUB', 43.09),
    ('RU000A10D517', DATE '2026-02-24', 92.737, 'SUR', 1000, 'RUB', 44.52),
    ('RU000A10D517', DATE '2026-02-25', 92.697, 'SUR', 1000, 'RUB', 44.88),
    ('RU000A10D517', DATE '2026-02-26', 92.488, 'SUR', 1000, 'RUB', 45.23),
    ('RU000A10D517', DATE '2026-02-27', 92.697, 'SUR', 1000, 'RUB', 45.59),
    ('RU000A10D517', DATE '2026-03-02', 92.6, 'SUR', 1000, 'RUB', 46.66),
    ('RU000A10D517', DATE '2026-03-03', 92.58, 'SUR', 1000, 'RUB', 47.01),
    ('RU000A10D517', DATE '2026-03-04', 92.48, 'SUR', 1000, 'RUB', 47.37),
    ('RU000A10D517', DATE '2026-03-05', 92.469, 'SUR', 1000, 'RUB', 47.72),
    ('RU000A10D517', DATE '2026-03-06', 92.379, 'SUR', 1000, 'RUB', 48.08),
    ('RU000A10D517', DATE '2026-03-09', 92.607, 'SUR', 1000, 'RUB', 49.15),
    ('RU000A10D517', DATE '2026-03-10', 92.58, 'SUR', 1000, 'RUB', 49.51),
    ('RU000A10D517', DATE '2026-03-11', 92.499, 'SUR', 1000, 'RUB', 49.86),
    ('RU000A10D517', DATE '2026-03-12', 93.05, 'SUR', 1000, 'RUB', 50.22),
    ('RU000A10D517', DATE '2026-03-13', 93.6, 'SUR', 1000, 'RUB', 50.57),
    ('RU000A10D517', DATE '2026-03-16', 93.73, 'SUR', 1000, 'RUB', 51.64),
    ('RU000A10D517', DATE '2026-03-17', 93.392, 'SUR', 1000, 'RUB', 52),
    ('RU000A10D517', DATE '2026-03-18', 93.497, 'SUR', 1000, 'RUB', 52.35),
    ('RU000A10D517', DATE '2026-03-19', 93.297, 'SUR', 1000, 'RUB', 52.71),
    ('RU000A10D517', DATE '2026-03-20', 93.4, 'SUR', 1000, 'RUB', 53.07),
    ('RU000A10D517', DATE '2026-03-23', 93.239, 'SUR', 1000, 'RUB', 54.14),
    ('RU000A10D517', DATE '2026-03-24', 93.233, 'SUR', 1000, 'RUB', 54.49),
    ('RU000A10D517', DATE '2026-03-25', 93.438, 'SUR', 1000, 'RUB', 54.85),
    ('RU000A10D517', DATE '2026-03-26', 93.32, 'SUR', 1000, 'RUB', 55.2),
    ('RU000A10D517', DATE '2026-03-27', 93.1, 'SUR', 1000, 'RUB', 55.56),
    ('RU000A10D517', DATE '2026-03-30', 92.945, 'SUR', 1000, 'RUB', 56.63),
    ('RU000A10D517', DATE '2026-03-31', 92.91, 'SUR', 1000, 'RUB', 56.98),
    ('RU000A10D517', DATE '2026-04-01', 92.823, 'SUR', 1000, 'RUB', 57.34),
    ('RU000A10D517', DATE '2026-04-02', 92.85, 'SUR', 1000, 'RUB', 57.7),
    ('RU000A10D517', DATE '2026-04-03', 92.683, 'SUR', 1000, 'RUB', 58.05),
    ('RU000A10D517', DATE '2026-04-06', 92.649, 'SUR', 1000, 'RUB', 59.12),
    ('RU000A10D517', DATE '2026-04-07', 92.544, 'SUR', 1000, 'RUB', 59.48),
    ('RU000A10D517', DATE '2026-04-08', 92.55, 'SUR', 1000, 'RUB', 59.83),
    ('RU000A10D517', DATE '2026-04-09', 92.35, 'SUR', 1000, 'RUB', 60.19),
    ('RU000A10D517', DATE '2026-04-10', 92.784, 'SUR', 1000, 'RUB', 60.55),
    ('RU000A10D533', DATE '2026-01-05', 93.549, 'SUR', 1000, 'RUB', 26.71),
    ('RU000A10D533', DATE '2026-01-06', 93.748, 'SUR', 1000, 'RUB', 27.07),
    ('RU000A10D533', DATE '2026-01-08', 93.57, 'SUR', 1000, 'RUB', 27.78),
    ('RU000A10D533', DATE '2026-01-09', 93.45, 'SUR', 1000, 'RUB', 28.14),
    ('RU000A10D533', DATE '2026-01-12', 92.647, 'SUR', 1000, 'RUB', 29.2),
    ('RU000A10D533', DATE '2026-01-13', 92.085, 'SUR', 1000, 'RUB', 29.56),
    ('RU000A10D533', DATE '2026-01-14', 91.968, 'SUR', 1000, 'RUB', 29.92),
    ('RU000A10D533', DATE '2026-01-15', 91.748, 'SUR', 1000, 'RUB', 30.27),
    ('RU000A10D533', DATE '2026-01-16', 91.7, 'SUR', 1000, 'RUB', 30.63),
    ('RU000A10D533', DATE '2026-01-19', 91.649, 'SUR', 1000, 'RUB', 31.7),
    ('RU000A10D533', DATE '2026-01-20', 91.744, 'SUR', 1000, 'RUB', 32.05),
    ('RU000A10D533', DATE '2026-01-21', 91.414, 'SUR', 1000, 'RUB', 32.41),
    ('RU000A10D533', DATE '2026-01-22', 91.55, 'SUR', 1000, 'RUB', 32.77),
    ('RU000A10D533', DATE '2026-01-23', 91.51, 'SUR', 1000, 'RUB', 33.12),
    ('RU000A10D533', DATE '2026-01-26', 91.329, 'SUR', 1000, 'RUB', 34.19),
    ('RU000A10D533', DATE '2026-01-27', 91, 'SUR', 1000, 'RUB', 34.55),
    ('RU000A10D533', DATE '2026-01-28', 90.94, 'SUR', 1000, 'RUB', 34.9),
    ('RU000A10D533', DATE '2026-01-29', 91.199, 'SUR', 1000, 'RUB', 35.26),
    ('RU000A10D533', DATE '2026-01-30', 91.19, 'SUR', 1000, 'RUB', 35.62),
    ('RU000A10D533', DATE '2026-02-02', 91.1, 'SUR', 1000, 'RUB', 36.68),
    ('RU000A10D533', DATE '2026-02-03', 91, 'SUR', 1000, 'RUB', 37.04),
    ('RU000A10D533', DATE '2026-02-04', 91.14, 'SUR', 1000, 'RUB', 37.4),
    ('RU000A10D533', DATE '2026-02-05', 90.801, 'SUR', 1000, 'RUB', 37.75),
    ('RU000A10D533', DATE '2026-02-06', 90.55, 'SUR', 1000, 'RUB', 38.11),
    ('RU000A10D533', DATE '2026-02-09', 90.4, 'SUR', 1000, 'RUB', 39.18),
    ('RU000A10D533', DATE '2026-02-10', 90, 'SUR', 1000, 'RUB', 39.53),
    ('RU000A10D533', DATE '2026-02-11', 90.36, 'SUR', 1000, 'RUB', 39.89),
    ('RU000A10D533', DATE '2026-02-12', 91.057, 'SUR', 1000, 'RUB', 40.25),
    ('RU000A10D533', DATE '2026-02-13', 92.42, 'SUR', 1000, 'RUB', 40.6),
    ('RU000A10D533', DATE '2026-02-16', 92.3, 'SUR', 1000, 'RUB', 41.67),
    ('RU000A10D533', DATE '2026-02-17', 92.52, 'SUR', 1000, 'RUB', 42.03),
    ('RU000A10D533', DATE '2026-02-18', 92.8, 'SUR', 1000, 'RUB', 42.38),
    ('RU000A10D533', DATE '2026-02-19', 92.788, 'SUR', 1000, 'RUB', 42.74),
    ('RU000A10D533', DATE '2026-02-20', 92.549, 'SUR', 1000, 'RUB', 43.09),
    ('RU000A10D533', DATE '2026-02-24', 92.549, 'SUR', 1000, 'RUB', 44.52),
    ('RU000A10D533', DATE '2026-02-25', 92.44, 'SUR', 1000, 'RUB', 44.88),
    ('RU000A10D533', DATE '2026-02-26', 92.15, 'SUR', 1000, 'RUB', 45.23),
    ('RU000A10D533', DATE '2026-02-27', 92.495, 'SUR', 1000, 'RUB', 45.59),
    ('RU000A10D533', DATE '2026-03-02', 92.3, 'SUR', 1000, 'RUB', 46.66),
    ('RU000A10D533', DATE '2026-03-03', 92.199, 'SUR', 1000, 'RUB', 47.01),
    ('RU000A10D533', DATE '2026-03-04', 92.13, 'SUR', 1000, 'RUB', 47.37),
    ('RU000A10D533', DATE '2026-03-05', 91.998, 'SUR', 1000, 'RUB', 47.72),
    ('RU000A10D533', DATE '2026-03-06', 92.011, 'SUR', 1000, 'RUB', 48.08),
    ('RU000A10D533', DATE '2026-03-09', 92.245, 'SUR', 1000, 'RUB', 49.15),
    ('RU000A10D533', DATE '2026-03-10', 91.91, 'SUR', 1000, 'RUB', 49.51),
    ('RU000A10D533', DATE '2026-03-11', 91.88, 'SUR', 1000, 'RUB', 49.86),
    ('RU000A10D533', DATE '2026-03-12', 92.563, 'SUR', 1000, 'RUB', 50.22),
    ('RU000A10D533', DATE '2026-03-13', 93.199, 'SUR', 1000, 'RUB', 50.57),
    ('RU000A10D533', DATE '2026-03-16', 93.3, 'SUR', 1000, 'RUB', 51.64),
    ('RU000A10D533', DATE '2026-03-17', 92.98, 'SUR', 1000, 'RUB', 52),
    ('RU000A10D533', DATE '2026-03-18', 92.999, 'SUR', 1000, 'RUB', 52.35),
    ('RU000A10D533', DATE '2026-03-19', 92.94, 'SUR', 1000, 'RUB', 52.71),
    ('RU000A10D533', DATE '2026-03-20', 93, 'SUR', 1000, 'RUB', 53.07),
    ('RU000A10D533', DATE '2026-03-23', 92.9, 'SUR', 1000, 'RUB', 54.14),
    ('RU000A10D533', DATE '2026-03-24', 92.8, 'SUR', 1000, 'RUB', 54.49),
    ('RU000A10D533', DATE '2026-03-25', 93, 'SUR', 1000, 'RUB', 54.85),
    ('RU000A10D533', DATE '2026-03-26', 92.741, 'SUR', 1000, 'RUB', 55.2),
    ('RU000A10D533', DATE '2026-03-27', 92.639, 'SUR', 1000, 'RUB', 55.56),
    ('RU000A10D533', DATE '2026-03-30', 92.686, 'SUR', 1000, 'RUB', 56.63),
    ('RU000A10D533', DATE '2026-03-31', 92.651, 'SUR', 1000, 'RUB', 56.98),
    ('RU000A10D533', DATE '2026-04-01', 92.65, 'SUR', 1000, 'RUB', 57.34),
    ('RU000A10D533', DATE '2026-04-02', 92.6, 'SUR', 1000, 'RUB', 57.7),
    ('RU000A10D533', DATE '2026-04-03', 92.3, 'SUR', 1000, 'RUB', 58.05),
    ('RU000A10D533', DATE '2026-04-06', 92.296, 'SUR', 1000, 'RUB', 59.12),
    ('RU000A10D533', DATE '2026-04-07', 92, 'SUR', 1000, 'RUB', 59.48),
    ('RU000A10D533', DATE '2026-04-08', 91.949, 'SUR', 1000, 'RUB', 59.83),
    ('RU000A10D533', DATE '2026-04-09', 91.848, 'SUR', 1000, 'RUB', 60.19),
    ('RU000A10D533', DATE '2026-04-10', 92.33, 'SUR', 1000, 'RUB', 60.55)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    272 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 272;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2026, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2026, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2026, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2026, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
