-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 421

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A10BV55', DATE '2026-01-05', 104.505, 'SUR', 1000, 'USD', 240.9382),
    ('RU000A10BV55', DATE '2026-01-06', 103.7593, 'SUR', 1000, 'USD', 257.3658),
    ('RU000A10BV55', DATE '2026-01-08', 104.3482, 'SUR', 1000, 'USD', 289.4388),
    ('RU000A10BV55', DATE '2026-01-09', 103.8163, 'SUR', 1000, 'USD', 305.0841),
    ('RU000A10BV55', DATE '2026-01-12', 104.4985, 'SUR', 1000, 'USD', 353.5847),
    ('RU000A10BV55', DATE '2026-01-13', 102.7375, 'SUR', 1000, 'USD', 372.6828),
    ('RU000A10BV55', DATE '2026-01-14', 102.3473, 'SUR', 1000, 'USD', 388.7438),
    ('RU000A10BV55', DATE '2026-01-15', 101.7014, 'SUR', 1000, 'USD', 403.8555),
    ('RU000A10BV55', DATE '2026-01-16', 101.9905, 'SUR', 1000, 'USD', 419.3395),
    ('RU000A10BV55', DATE '2026-01-19', 102.592, 'SUR', 1000, 'USD', 463.8859),
    ('RU000A10BV55', DATE '2026-01-20', 102.953, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2026-01-21', 101.6401, 'SUR', 1000, 'USD', 16.3432),
    ('RU000A10BV55', DATE '2026-01-22', 102.0355, 'SUR', 1000, 'USD', 31.7815),
    ('RU000A10BV55', DATE '2026-01-23', 103.3, 'SUR', 1000, 'USD', 47.1437),
    ('RU000A10BV55', DATE '2026-01-26', 103.7318, 'SUR', 1000, 'USD', 93.3873),
    ('RU000A10BV55', DATE '2026-01-27', 103.5905, 'SUR', 1000, 'USD', 109.4545),
    ('RU000A10BV55', DATE '2026-01-28', 102.9997, 'SUR', 1000, 'USD', 125.5451),
    ('RU000A10BV55', DATE '2026-01-29', 102.6999, 'SUR', 1000, 'USD', 141.0925),
    ('RU000A10BV55', DATE '2026-01-30', 102.8295, 'SUR', 1000, 'USD', 155.8515),
    ('RU000A10BV55', DATE '2026-02-02', 104.68, 'SUR', 1000, 'USD', 202.2063),
    ('RU000A10BV55', DATE '2026-02-03', 102.6487, 'SUR', 1000, 'USD', 221.8242),
    ('RU000A10BV55', DATE '2026-02-04', 101.6443, 'SUR', 1000, 'USD', 237.1036),
    ('RU000A10BV55', DATE '2026-02-05', 101.54, 'SUR', 1000, 'USD', 253.0346),
    ('RU000A10BV55', DATE '2026-02-06', 101.8318, 'SUR', 1000, 'USD', 267.1675),
    ('RU000A10BV55', DATE '2026-02-09', 101.1919, 'SUR', 1000, 'USD', 316.6919),
    ('RU000A10BV55', DATE '2026-02-10', 100.27, 'SUR', 1000, 'USD', 335.4489),
    ('RU000A10BV55', DATE '2026-02-11', 100.6497, 'SUR', 1000, 'USD', 348.9851),
    ('RU000A10BV55', DATE '2026-02-12', 101, 'SUR', 1000, 'USD', 366.4085),
    ('RU000A10BV55', DATE '2026-02-13', 100.2319, 'SUR', 1000, 'USD', 380.5368),
    ('RU000A10BV55', DATE '2026-02-16', 100.5, 'SUR', 1000, 'USD', 428.4289),
    ('RU000A10BV55', DATE '2026-02-17', 100.6876, 'SUR', 1000, 'USD', 440.5656),
    ('RU000A10BV55', DATE '2026-02-18', 100.6305, 'SUR', 1000, 'USD', 457.3638),
    ('RU000A10BV55', DATE '2026-02-19', 101.2499, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2026-02-20', 100.6126, 'SUR', 1000, 'USD', 16.0945),
    ('RU000A10BV55', DATE '2026-02-24', 100.2993, 'SUR', 1000, 'USD', 79.0545),
    ('RU000A10BV55', DATE '2026-02-25', 102.1975, 'SUR', 1000, 'USD', 94.2601),
    ('RU000A10BV55', DATE '2026-02-26', 101.8996, 'SUR', 1000, 'USD', 110.1136),
    ('RU000A10BV55', DATE '2026-02-27', 101.1418, 'SUR', 1000, 'USD', 126.4798),
    ('RU000A10BV55', DATE '2026-03-02', 101.5868, 'SUR', 1000, 'USD', 174.6383),
    ('RU000A10BV55', DATE '2026-03-03', 101.601, 'SUR', 1000, 'USD', 190.6183),
    ('RU000A10BV55', DATE '2026-03-04', 101.6667, 'SUR', 1000, 'USD', 207.2168),
    ('RU000A10BV55', DATE '2026-03-05', 102.9441, 'SUR', 1000, 'USD', 224.0666),
    ('RU000A10BV55', DATE '2026-03-06', 102.7395, 'SUR', 1000, 'USD', 240.8252),
    ('RU000A10BV55', DATE '2026-03-09', 101.96, 'SUR', 1000, 'USD', 292.855),
    ('RU000A10BV55', DATE '2026-03-10', 102.2954, 'SUR', 1000, 'USD', 308.685),
    ('RU000A10BV55', DATE '2026-03-11', 102.2523, 'SUR', 1000, 'USD', 323.6198),
    ('RU000A10BV55', DATE '2026-03-12', 102, 'SUR', 1000, 'USD', 341.5738),
    ('RU000A10BV55', DATE '2026-03-13', 102.1, 'SUR', 1000, 'USD', 357.3833),
    ('RU000A10BV55', DATE '2026-03-16', 102.2996, 'SUR', 1000, 'USD', 412.3586),
    ('RU000A10BV55', DATE '2026-03-17', 101.6, 'SUR', 1000, 'USD', 432.8161),
    ('RU000A10BV55', DATE '2026-03-18', 102.2064, 'SUR', 1000, 'USD', 454.6022),
    ('RU000A10BV55', DATE '2026-03-19', 101.3845, 'SUR', 1000, 'USD', 477.9739),
    ('RU000A10BV55', DATE '2026-03-20', 98.0969, 'SUR', 1000, 'USD', 505.6339),
    ('RU000A10BV55', DATE '2026-03-23', 97.7, 'SUR', 1000, 'USD', 34.4393),
    ('RU000A10BV55', DATE '2026-03-24', 98.0812, 'SUR', 1000, 'USD', 50.7633),
    ('RU000A10BV55', DATE '2026-03-25', 99.68, 'SUR', 1000, 'USD', 66.3875),
    ('RU000A10BV55', DATE '2026-03-26', 100.017, 'SUR', 1000, 'USD', 83.1408),
    ('RU000A10BV55', DATE '2026-03-27', 98.1511, 'SUR', 1000, 'USD', 101.0216),
    ('RU000A10BV55', DATE '2026-03-30', 99.1956, 'SUR', 1000, 'USD', 150.117),
    ('RU000A10BV55', DATE '2026-03-31', 98.79, 'SUR', 1000, 'USD', 166.6558),
    ('RU000A10BV55', DATE '2026-04-01', 98.1459, 'SUR', 1000, 'USD', 183.6259),
    ('RU000A10BV55', DATE '2026-04-02', 98.6136, 'SUR', 1000, 'USD', 199.1398),
    ('RU000A10BV55', DATE '2026-04-03', 98.5801, 'SUR', 1000, 'USD', 214.4896),
    ('RU000A10BV55', DATE '2026-04-06', 98.2247, 'SUR', 1000, 'USD', 262.3094),
    ('RU000A10BV55', DATE '2026-04-07', 98.5997, 'SUR', 1000, 'USD', 274.7597),
    ('RU000A10BV55', DATE '2026-04-08', 98.7497, 'SUR', 1000, 'USD', 291.3735),
    ('RU000A10BV55', DATE '2026-04-09', 98.6117, 'SUR', 1000, 'USD', 305.3868),
    ('RU000A10BV55', DATE '2026-04-10', 99.2982, 'SUR', 1000, 'USD', 319.9084),
    ('RU000A10BV55', DATE '2026-04-13', 98.5972, 'SUR', 1000, 'USD', 364.0795),
    ('RU000A10BV55', DATE '2026-04-14', 98.25, 'SUR', 1000, 'USD', 375.9071),
    ('RU000A10BV55', DATE '2026-04-15', 99.4474, 'SUR', 1000, 'USD', 389.8854),
    ('RU000A10BV55', DATE '2026-04-16', 100.9, 'SUR', 1000, 'USD', 401.7528),
    ('RU000A10BV55', DATE '2026-04-17', 100.0318, 'SUR', 1000, 'USD', 422.2779),
    ('RU000A10BV55', DATE '2026-04-20', 99.8919, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2026-04-21', 100.0708, 'SUR', 1000, 'USD', 15.7998),
    ('RU000A10BV55', DATE '2026-04-22', 100.4998, 'SUR', 1000, 'USD', 30.5818),
    ('RU000A10BV55', DATE '2026-04-23', 101.0328, 'SUR', 1000, 'USD', 46.4997),
    ('RU000A10BV55', DATE '2026-04-24', 101.344, 'SUR', 1000, 'USD', 61.3646),
    ('RU000A10BV55', DATE '2026-04-27', 99.7, 'SUR', 1000, 'USD', 108.7593),
    ('RU000A10BV55', DATE '2026-04-28', 101.1762, 'SUR', 1000, 'USD', 122.6853),
    ('RU000A10BV55', DATE '2026-04-29', 101.3225, 'SUR', 1000, 'USD', 138.1852),
    ('RU000A10BV55', DATE '2026-04-30', 102.0535, 'SUR', 1000, 'USD', 153.5052),
    ('RU000A10BV55', DATE '2026-05-04', 102.3702, 'SUR', 1000, 'USD', 215.428),
    ('RU000A10BV55', DATE '2026-05-05', 101.9948, 'SUR', 1000, 'USD', 232.3515),
    ('RU000A10BV55', DATE '2026-05-06', 101.0899, 'SUR', 1000, 'USD', 247.8844),
    ('RU000A10BV55', DATE '2026-05-07', 101, 'SUR', 1000, 'USD', 262.5339),
    ('RU000A10BV55', DATE '2026-05-08', 101.1999, 'SUR', 1000, 'USD', 276.0973),
    ('RU000A10BV55', DATE '2026-05-11', 101.1282, 'SUR', 1000, 'USD', 320.96),
    ('RU000A10BV55', DATE '2026-05-12', 100.532, 'SUR', 1000, 'USD', 335.8193),
    ('RU000A10BV55', DATE '2026-05-13', 101.1, 'SUR', 1000, 'USD', 349.0163),
    ('RU000A10BV55', DATE '2026-05-14', 101.3064, 'SUR', 1000, 'USD', 361.5761),
    ('RU000A10BV55', DATE '2026-05-15', 101.2802, 'SUR', 1000, 'USD', 375.9319),
    ('RU000A10BV55', DATE '2026-05-18', 99.996, 'SUR', 1000, 'USD', 420.4831),
    ('RU000A10BV55', DATE '2026-05-19', 98.9657, 'SUR', 1000, 'USD', 431.2042),
    ('RU000A10BV55', DATE '2026-05-20', 101.6534, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2026-05-21', 102, 'SUR', 1000, 'USD', 14.8997),
    ('RU000A10BV55', DATE '2026-05-22', 102.5501, 'SUR', 1000, 'USD', 29.024),
    ('RU000A10BV55', DATE '2026-05-25', 102.858, 'SUR', 1000, 'USD', 73.3453),
    ('RU000A10BV55', DATE '2026-05-26', 101.8497, 'SUR', 1000, 'USD', 88.0016),
    ('RU000A10BV55', DATE '2026-05-27', 101.496, 'SUR', 1000, 'USD', 103.2019),
    ('RU000A10BV55', DATE '2026-05-28', 102.2324, 'SUR', 1000, 'USD', 116.278),
    ('RU000A10BV55', DATE '2026-05-29', 101.9002, 'SUR', 1000, 'USD', 132.0373),
    ('RU000A10BV55', DATE '2026-06-01', 103.1356, 'SUR', 1000, 'USD', 175.4253),
    ('RU000A10BV55', DATE '2026-06-02', 103.9999, 'SUR', 1000, 'USD', 191.047),
    ('RU000A10BV55', DATE '2026-06-03', 103.5, 'SUR', 1000, 'USD', 208.9719),
    ('RU000A10BV55', DATE '2026-06-04', 102.4784, 'SUR', 1000, 'USD', 225.8983),
    ('RU000A10BV55', DATE '2026-06-05', 101.8, 'SUR', 1000, 'USD', 244.4325),
    ('RU000A10BV55', DATE '2026-06-08', 101.2133, 'SUR', 1000, 'USD', 286.5287),
    ('RU000A10BV55', DATE '2026-06-09', 100.6633, 'SUR', 1000, 'USD', 301.1167),
    ('RU000A10BV55', DATE '2026-06-10', 102.6587, 'SUR', 1000, 'USD', 309.8814),
    ('RU000A10BV55', DATE '2026-06-11', 102.4756, 'SUR', 1000, 'USD', 324.4872),
    ('RU000A10BV55', DATE '2026-06-15', 102.0748, 'SUR', 1000, 'USD', 383.9871),
    ('RU000A10BV55', DATE '2026-06-16', 102.2989, 'SUR', 1000, 'USD', 402.1047),
    ('RU000A10BV55', DATE '2026-06-17', 102.9994, 'SUR', 1000, 'USD', 414.7981),
    ('RU000A10BV55', DATE '2026-06-18', 101.9069, 'SUR', 1000, 'USD', 433.5775),
    ('RU000A10BV55', DATE '2026-06-19', 101.3528, 'SUR', 1000, 'USD', 0),
    ('RU000A10BV55', DATE '2026-06-22', 102.3498, 'SUR', 1000, 'USD', 45.5322),
    ('RU000A10BV55', DATE '2026-06-23', 100.8589, 'SUR', 1000, 'USD', 60.4873),
    ('RU000A10BV55', DATE '2026-06-24', 100.4, 'SUR', 1000, 'USD', 76.8586),
    ('RU000A10BV55', DATE '2026-06-25', 102.1637, 'SUR', 1000, 'USD', 91.9718),
    ('RU000A10BV55', DATE '2026-06-26', 103.0747, 'SUR', 1000, 'USD', 108.914),
    ('RU000A10BV55', DATE '2026-06-29', 100.11, 'SUR', 1000, 'USD', 157.9753),
    ('RU000A10BV55', DATE '2026-06-30', 101.795, 'SUR', 1000, 'USD', 175.7238),
    ('RU000A10BV55', DATE '2026-07-01', 100.5999, 'SUR', 1000, 'USD', 193.3259),
    ('RU000A10BV55', DATE '2026-07-02', 100.4998, 'SUR', 1000, 'USD', 208.9681),
    ('RU000A10BV55', DATE '2026-07-03', 99.35, 'SUR', 1000, 'USD', 224.4364),
    ('RU000A10BV55', DATE '2026-07-06', 97.9606, 'SUR', 1000, 'USD', 269.5201),
    ('RU000A10BV55', DATE '2026-07-07', 97.1, 'SUR', 1000, 'USD', 288.4872),
    ('RU000A10BV55', DATE '2026-07-08', 98.206, 'SUR', 1000, 'USD', 296.8906),
    ('RU000A10BV55', DATE '2026-07-09', 98.5977, 'SUR', 1000, 'USD', 314.0147),
    ('RU000A10BV55', DATE '2026-07-10', 99.9925, 'SUR', 1000, 'USD', 328.0176),
    ('RU000A10BV55', DATE '2026-07-13', 99.06, 'SUR', 1000, 'USD', 377.957),
    ('RU000A10BV55', DATE '2026-07-14', 99.7999, 'SUR', 1000, 'USD', 393.8335),
    ('RU000A10BV55', DATE '2026-07-15', 98.7251, 'SUR', 1000, 'USD', 413.803),
    ('RU000A10BV55', DATE '2026-07-16', 98.6996, 'SUR', 1000, 'USD', 432.6602),
    ('RU000A10BV55', DATE '2026-07-17', 95.6623, 'SUR', 1000, 'USD', 450.3291),
    ('RU000A10BV55', DATE '2026-07-20', 95.7619, 'SUR', 1000, 'USD', 16.4637),
    ('RU000A10BV55', DATE '2026-07-21', 97.9259, 'SUR', 1000, 'USD', 32.1095),
    ('RU000A10BV55', DATE '2026-07-22', 96.9985, 'SUR', 1000, 'USD', 48.7035),
    ('RU000A10BV55', DATE '2026-07-23', 97.4998, 'SUR', 1000, 'USD', 64.35),
    ('RU000A10BV55', DATE '2026-07-24', 97.305, 'SUR', 1000, 'USD', 80.757),
    ('RU000A10BV55', DATE '2026-07-27', 98.1026, 'SUR', 1000, 'USD', 127.9705),
    ('RU000A10BV55', DATE '2026-07-28', 99.182, 'SUR', 1000, 'USD', 144.3318),
    ('RU000A10BV55', DATE '2026-07-29', 99.5568, 'SUR', 1000, 'USD', 161.3309),
    ('RU000A10BV55', DATE '2026-07-30', 98.2415, 'SUR', 1000, 'USD', 179.3468),
    ('RU000A10BV55', DATE '2026-07-31', 97.6913, 'SUR', 1000, 'USD', 197.2475),
    ('RU000A10BV55', DATE '2026-08-03', 99.5797, 'SUR', 1000, 'USD', 244.7482),
    ('RU000A10BV55', DATE '2026-08-04', 99.2602, 'SUR', 1000, 'USD', 263.426),
    ('RU000A10BV55', DATE '2026-08-05', 98.1284, 'SUR', 1000, 'USD', 283.1406),
    ('RU000A10BV55', DATE '2026-08-06', 99.5117, 'SUR', 1000, 'USD', 299.4384),
    ('RU000A10BV55', DATE '2026-08-07', 99.32, 'SUR', 1000, 'USD', 317.49),
    ('RU000A10FMQ8', DATE '2026-07-10', 98.75, 'SUR', 1000, 'RUB', 0),
    ('RU000A10FMQ8', DATE '2026-07-13', 98.84, 'SUR', 1000, 'RUB', 1.6),
    ('RU000A10FMQ8', DATE '2026-07-14', 98.9, 'SUR', 1000, 'RUB', 2.14),
    ('RU000A10FMQ8', DATE '2026-07-15', 98.73, 'SUR', 1000, 'RUB', 2.67),
    ('RU000A10FMQ8', DATE '2026-07-16', 98.06, 'SUR', 1000, 'RUB', 3.21),
    ('RU000A10FMQ8', DATE '2026-07-17', 98.19, 'SUR', 1000, 'RUB', 3.74),
    ('RU000A10FMQ8', DATE '2026-07-20', 97.96, 'SUR', 1000, 'RUB', 5.34),
    ('RU000A10FMQ8', DATE '2026-07-21', 98.35, 'SUR', 1000, 'RUB', 5.88),
    ('RU000A10FMQ8', DATE '2026-07-22', 98.78, 'SUR', 1000, 'RUB', 6.41),
    ('RU000A10FMQ8', DATE '2026-07-23', 98.75, 'SUR', 1000, 'RUB', 6.95),
    ('RU000A10FMQ8', DATE '2026-07-24', 99.25, 'SUR', 1000, 'RUB', 7.48),
    ('RU000A10FMQ8', DATE '2026-07-27', 99.39, 'SUR', 1000, 'RUB', 9.08),
    ('RU000A10FMQ8', DATE '2026-07-28', 99.64, 'SUR', 1000, 'RUB', 9.62),
    ('RU000A10FMQ8', DATE '2026-07-29', 99.74, 'SUR', 1000, 'RUB', 10.15),
    ('RU000A10FMQ8', DATE '2026-07-30', 99.74, 'SUR', 1000, 'RUB', 10.68),
    ('RU000A10FMQ8', DATE '2026-07-31', 99.75, 'SUR', 1000, 'RUB', 11.22),
    ('RU000A10FMQ8', DATE '2026-08-03', 99.68, 'SUR', 1000, 'RUB', 12.82),
    ('RU000A10FMQ8', DATE '2026-08-04', 99.89, 'SUR', 1000, 'RUB', 13.36),
    ('RU000A10FMQ8', DATE '2026-08-05', 100.14, 'SUR', 1000, 'RUB', 13.89),
    ('RU000A10FMQ8', DATE '2026-08-06', 100.02, 'SUR', 1000, 'RUB', 14.42),
    ('RU000A10FMQ8', DATE '2026-08-07', 100, 'SUR', 1000, 'RUB', 14.96),
    ('RU000A10FJS0', DATE '2026-07-03', 100.15, 'SUR', 1000, 'RUB', 0),
    ('RU000A10FJS0', DATE '2026-07-06', 100.23, 'SUR', 1000, 'RUB', 1.17),
    ('RU000A10FJS0', DATE '2026-07-07', 100, 'SUR', 1000, 'RUB', 1.56),
    ('RU000A10FJS0', DATE '2026-07-08', 99.8, 'SUR', 1000, 'RUB', 1.95),
    ('RU000A10FJS0', DATE '2026-07-09', 99.58, 'SUR', 1000, 'RUB', 2.33),
    ('RU000A10FJS0', DATE '2026-07-10', 99.1, 'SUR', 1000, 'RUB', 2.72),
    ('RU000A10FJS0', DATE '2026-07-13', 99.48, 'SUR', 1000, 'RUB', 3.89),
    ('RU000A10FJS0', DATE '2026-07-14', 99.59, 'SUR', 1000, 'RUB', 4.28),
    ('RU000A10FJS0', DATE '2026-07-15', 99.66, 'SUR', 1000, 'RUB', 4.67),
    ('RU000A10FJS0', DATE '2026-07-16', 99.49, 'SUR', 1000, 'RUB', 5.06),
    ('RU000A10FJS0', DATE '2026-07-17', 99.89, 'SUR', 1000, 'RUB', 5.45),
    ('RU000A10FJS0', DATE '2026-07-20', 99.77, 'SUR', 1000, 'RUB', 6.61),
    ('RU000A10FJS0', DATE '2026-07-21', 99.82, 'SUR', 1000, 'RUB', 7),
    ('RU000A10FJS0', DATE '2026-07-22', 99.8, 'SUR', 1000, 'RUB', 7.39),
    ('RU000A10FJS0', DATE '2026-07-23', 99.88, 'SUR', 1000, 'RUB', 7.78),
    ('RU000A10FJS0', DATE '2026-07-24', 99.95, 'SUR', 1000, 'RUB', 8.17),
    ('RU000A10FJS0', DATE '2026-07-27', 100.25, 'SUR', 1000, 'RUB', 9.34),
    ('RU000A10FJS0', DATE '2026-07-28', 100.12, 'SUR', 1000, 'RUB', 9.73),
    ('RU000A10FJS0', DATE '2026-07-29', 100.2, 'SUR', 1000, 'RUB', 10.12),
    ('RU000A10FJS0', DATE '2026-07-30', 100.04, 'SUR', 1000, 'RUB', 10.5),
    ('RU000A10FJS0', DATE '2026-07-31', 100.24, 'SUR', 1000, 'RUB', 10.89),
    ('RU000A10FJS0', DATE '2026-08-03', 99.99, 'SUR', 1000, 'RUB', 0.39),
    ('RU000A10FJS0', DATE '2026-08-04', 99.74, 'SUR', 1000, 'RUB', 0.78),
    ('RU000A10FJS0', DATE '2026-08-05', 99.68, 'SUR', 1000, 'RUB', 1.17),
    ('RU000A10FJS0', DATE '2026-08-06', 99.6, 'SUR', 1000, 'RUB', 1.56),
    ('RU000A10FJS0', DATE '2026-08-07', 99.59, 'SUR', 1000, 'RUB', 1.95),
    ('RU000A10FNA0', DATE '2026-07-14', 100.46, 'SUR', 1000, 'CNY', 0),
    ('RU000A10FNA0', DATE '2026-07-15', 99.849, 'SUR', 1000, 'CNY', 2.3893),
    ('RU000A10FNA0', DATE '2026-07-16', 99.75, 'SUR', 1000, 'CNY', 4.7206),
    ('RU000A10FNA0', DATE '2026-07-17', 99.8718, 'SUR', 1000, 'CNY', 7.1386),
    ('RU000A10FNA0', DATE '2026-07-20', 99.53, 'SUR', 1000, 'CNY', 14.219),
    ('RU000A10FNA0', DATE '2026-07-21', 99.6016, 'SUR', 1000, 'CNY', 16.6605),
    ('RU000A10FNA0', DATE '2026-07-22', 99.6395, 'SUR', 1000, 'CNY', 19.0389),
    ('RU000A10FNA0', DATE '2026-07-23', 99.7431, 'SUR', 1000, 'CNY', 21.4197),
    ('RU000A10FNA0', DATE '2026-07-24', 99.5143, 'SUR', 1000, 'CNY', 23.7443),
    ('RU000A10FNA0', DATE '2026-07-27', 99.7959, 'SUR', 1000, 'CNY', 30.7117),
    ('RU000A10FNA0', DATE '2026-07-28', 100.435, 'SUR', 1000, 'CNY', 33.1828),
    ('RU000A10FNA0', DATE '2026-07-29', 99.45, 'SUR', 1000, 'CNY', 35.7006),
    ('RU000A10FNA0', DATE '2026-07-30', 99.99, 'SUR', 1000, 'CNY', 38.5637),
    ('RU000A10FNA0', DATE '2026-07-31', 99.9188, 'SUR', 1000, 'CNY', 41.2497),
    ('RU000A10FNA0', DATE '2026-08-03', 100.35, 'SUR', 1000, 'CNY', 48.3722),
    ('RU000A10FNA0', DATE '2026-08-04', 99.9992, 'SUR', 1000, 'CNY', 51.1237),
    ('RU000A10FNA0', DATE '2026-08-05', 100.8999, 'SUR', 1000, 'CNY', 54.094),
    ('RU000A10FNA0', DATE '2026-08-06', 99.8001, 'SUR', 1000, 'CNY', 56.6105),
    ('RU000A10FNA0', DATE '2026-08-07', 99.9892, 'SUR', 1000, 'CNY', 59.474),
    ('RU000A10FNB8', DATE '2026-07-14', 100.1601, 'SUR', 1000, 'USD', 0),
    ('RU000A10FNB8', DATE '2026-07-15', 99.99, 'SUR', 1000, 'USD', 17.0481),
    ('RU000A10FNB8', DATE '2026-07-16', 99.1781, 'SUR', 1000, 'USD', 34.301),
    ('RU000A10FNB8', DATE '2026-07-17', 98.4003, 'SUR', 1000, 'USD', 51.6899),
    ('RU000A10FNB8', DATE '2026-07-20', 99.4799, 'SUR', 1000, 'USD', 103.4863),
    ('RU000A10FNB8', DATE '2026-07-21', 99.8, 'SUR', 1000, 'USD', 119.8233),
    ('RU000A10FNB8', DATE '2026-07-22', 99.7899, 'SUR', 1000, 'USD', 137.4695),
    ('RU000A10FNB8', DATE '2026-07-23', 99.8987, 'SUR', 1000, 'USD', 154.5969),
    ('RU000A10FNB8', DATE '2026-07-24', 98.6992, 'SUR', 1000, 'USD', 171.7067),
    ('RU000A10FNB8', DATE '2026-07-27', 99.9767, 'SUR', 1000, 'USD', 222.3878),
    ('RU000A10FNB8', DATE '2026-07-28', 100.9, 'SUR', 1000, 'USD', 239.5128),
    ('RU000A10FNB8', DATE '2026-07-29', 100.8374, 'SUR', 1000, 'USD', 258.9164),
    ('RU000A10FNB8', DATE '2026-07-30', 100.1712, 'SUR', 1000, 'USD', 278.5431),
    ('RU000A10FNB8', DATE '2026-07-31', 99.7, 'SUR', 1000, 'USD', 297.8677),
    ('RU000A10FNB8', DATE '2026-08-03', 100.9731, 'SUR', 1000, 'USD', 348.051),
    ('RU000A10FNB8', DATE '2026-08-04', 100.603, 'SUR', 1000, 'USD', 368.316),
    ('RU000A10FNB8', DATE '2026-08-05', 99.8637, 'SUR', 1000, 'USD', 391.0423),
    ('RU000A10FNB8', DATE '2026-08-06', 100.859, 'SUR', 1000, 'USD', 407.8837),
    ('RU000A10FNB8', DATE '2026-08-07', 101.4521, 'SUR', 1000, 'USD', 428.2045),
    ('RU000A10FMY2', DATE '2026-07-13', 99.59, 'SUR', 1000, 'RUB', 0),
    ('RU000A10FMY2', DATE '2026-07-14', 99.96, 'SUR', 1000, 'RUB', 0.44),
    ('RU000A10FMY2', DATE '2026-07-15', 99.95, 'SUR', 1000, 'RUB', 0.88),
    ('RU000A10FMY2', DATE '2026-07-16', 99.87, 'SUR', 1000, 'RUB', 1.32),
    ('RU000A10FMY2', DATE '2026-07-17', 99.86, 'SUR', 1000, 'RUB', 1.75),
    ('RU000A10FMY2', DATE '2026-07-20', 99.84, 'SUR', 1000, 'RUB', 3.07),
    ('RU000A10FMY2', DATE '2026-07-21', 99.88, 'SUR', 1000, 'RUB', 3.51),
    ('RU000A10FMY2', DATE '2026-07-22', 99.97, 'SUR', 1000, 'RUB', 3.95),
    ('RU000A10FMY2', DATE '2026-07-23', 99.94, 'SUR', 1000, 'RUB', 4.38),
    ('RU000A10FMY2', DATE '2026-07-24', 100.9, 'SUR', 1000, 'RUB', 4.82),
    ('RU000A10FMY2', DATE '2026-07-27', 100.7, 'SUR', 1000, 'RUB', 6.14),
    ('RU000A10FMY2', DATE '2026-07-28', 100.65, 'SUR', 1000, 'RUB', 6.58),
    ('RU000A10FMY2', DATE '2026-07-29', 100.68, 'SUR', 1000, 'RUB', 7.01),
    ('RU000A10FMY2', DATE '2026-07-30', 100.68, 'SUR', 1000, 'RUB', 7.45),
    ('RU000A10FMY2', DATE '2026-07-31', 101.07, 'SUR', 1000, 'RUB', 7.89),
    ('RU000A10FMY2', DATE '2026-08-03', 101.4, 'SUR', 1000, 'RUB', 9.21),
    ('RU000A10FMY2', DATE '2026-08-04', 101.75, 'SUR', 1000, 'RUB', 9.64),
    ('RU000A10FMY2', DATE '2026-08-05', 101.84, 'SUR', 1000, 'RUB', 10.08),
    ('RU000A10FMY2', DATE '2026-08-06', 101.95, 'SUR', 1000, 'RUB', 10.52),
    ('RU000A10FMY2', DATE '2026-08-07', 101.85, 'SUR', 1000, 'RUB', 10.96),
    ('RU000A10FGH9', DATE '2026-07-21', 99.99, 'SUR', 1000, 'RUB', 0),
    ('RU000A10FGH9', DATE '2026-07-22', 99.96, 'SUR', 1000, 'RUB', 0.47),
    ('RU000A10FGH9', DATE '2026-07-23', 100.1, 'SUR', 1000, 'RUB', 0.93),
    ('RU000A10FGH9', DATE '2026-07-24', 100.33, 'SUR', 1000, 'RUB', 1.4),
    ('RU000A10FGH9', DATE '2026-07-27', 101.3, 'SUR', 1000, 'RUB', 2.79),
    ('RU000A10FGH9', DATE '2026-07-28', 100.84, 'SUR', 1000, 'RUB', 3.26),
    ('RU000A10FGH9', DATE '2026-07-29', 101.34, 'SUR', 1000, 'RUB', 3.73),
    ('RU000A10FGH9', DATE '2026-07-30', 101.29, 'SUR', 1000, 'RUB', 4.19),
    ('RU000A10FGH9', DATE '2026-07-31', 101.08, 'SUR', 1000, 'RUB', 4.66),
    ('RU000A10FGH9', DATE '2026-08-03', 100.95, 'SUR', 1000, 'RUB', 6.05),
    ('RU000A10FGH9', DATE '2026-08-04', 100.96, 'SUR', 1000, 'RUB', 6.52),
    ('RU000A10FGH9', DATE '2026-08-05', 101.41, 'SUR', 1000, 'RUB', 6.99),
    ('RU000A10FGH9', DATE '2026-08-06', 101.03, 'SUR', 1000, 'RUB', 7.45),
    ('RU000A10FGH9', DATE '2026-08-07', 101.38, 'SUR', 1000, 'RUB', 7.92),
    ('RU000A10CS75', DATE '2026-01-05', 99.45, 'SUR', 1000, 'RUB', 8.82),
    ('RU000A10CS75', DATE '2026-01-06', 99.41, 'SUR', 1000, 'RUB', 9.3),
    ('RU000A10CS75', DATE '2026-01-08', 99.36, 'SUR', 1000, 'RUB', 10.26),
    ('RU000A10CS75', DATE '2026-01-09', 99.39, 'SUR', 1000, 'RUB', 10.75),
    ('RU000A10CS75', DATE '2026-01-12', 98.64, 'SUR', 1000, 'RUB', 12.19),
    ('RU000A10CS75', DATE '2026-01-13', 99.25, 'SUR', 1000, 'RUB', 12.67),
    ('RU000A10CS75', DATE '2026-01-14', 99.2, 'SUR', 1000, 'RUB', 13.16),
    ('RU000A10CS75', DATE '2026-01-15', 99.37, 'SUR', 1000, 'RUB', 13.64),
    ('RU000A10CS75', DATE '2026-01-16', 99.33, 'SUR', 1000, 'RUB', 14.12),
    ('RU000A10CS75', DATE '2026-01-19', 99.33, 'SUR', 1000, 'RUB', 0.96),
    ('RU000A10CS75', DATE '2026-01-20', 99.14, 'SUR', 1000, 'RUB', 1.45),
    ('RU000A10CS75', DATE '2026-01-21', 99.28, 'SUR', 1000, 'RUB', 1.93),
    ('RU000A10CS75', DATE '2026-01-22', 99.11, 'SUR', 1000, 'RUB', 2.41),
    ('RU000A10CS75', DATE '2026-01-23', 99.05, 'SUR', 1000, 'RUB', 2.89),
    ('RU000A10CS75', DATE '2026-01-26', 99.17, 'SUR', 1000, 'RUB', 4.34),
    ('RU000A10CS75', DATE '2026-01-27', 99.23, 'SUR', 1000, 'RUB', 4.82),
    ('RU000A10CS75', DATE '2026-01-28', 99.35, 'SUR', 1000, 'RUB', 5.3),
    ('RU000A10CS75', DATE '2026-01-29', 99.29, 'SUR', 1000, 'RUB', 5.79),
    ('RU000A10CS75', DATE '2026-01-30', 99.29, 'SUR', 1000, 'RUB', 6.27),
    ('RU000A10CS75', DATE '2026-02-02', 99.17, 'SUR', 1000, 'RUB', 7.72),
    ('RU000A10CS75', DATE '2026-02-03', 99.21, 'SUR', 1000, 'RUB', 8.2),
    ('RU000A10CS75', DATE '2026-02-04', 99.24, 'SUR', 1000, 'RUB', 8.68),
    ('RU000A10CS75', DATE '2026-02-05', 99.28, 'SUR', 1000, 'RUB', 9.16),
    ('RU000A10CS75', DATE '2026-02-06', 99.28, 'SUR', 1000, 'RUB', 9.64),
    ('RU000A10CS75', DATE '2026-02-09', 99.07, 'SUR', 1000, 'RUB', 11.09),
    ('RU000A10CS75', DATE '2026-02-10', 99.3, 'SUR', 1000, 'RUB', 11.57),
    ('RU000A10CS75', DATE '2026-02-11', 99.23, 'SUR', 1000, 'RUB', 12.05),
    ('RU000A10CS75', DATE '2026-02-12', 99.38, 'SUR', 1000, 'RUB', 12.54),
    ('RU000A10CS75', DATE '2026-02-13', 99.42, 'SUR', 1000, 'RUB', 13.02),
    ('RU000A10CS75', DATE '2026-02-16', 99.44, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2026-02-17', 99.36, 'SUR', 1000, 'RUB', 0.48),
    ('RU000A10CS75', DATE '2026-02-18', 99.38, 'SUR', 1000, 'RUB', 0.96),
    ('RU000A10CS75', DATE '2026-02-19', 99.22, 'SUR', 1000, 'RUB', 1.45),
    ('RU000A10CS75', DATE '2026-02-20', 99.16, 'SUR', 1000, 'RUB', 1.93),
    ('RU000A10CS75', DATE '2026-02-24', 99.29, 'SUR', 1000, 'RUB', 3.83),
    ('RU000A10CS75', DATE '2026-02-25', 99.17, 'SUR', 1000, 'RUB', 4.3),
    ('RU000A10CS75', DATE '2026-02-26', 99.21, 'SUR', 1000, 'RUB', 4.77),
    ('RU000A10CS75', DATE '2026-02-27', 99.29, 'SUR', 1000, 'RUB', 5.24),
    ('RU000A10CS75', DATE '2026-03-02', 99.13, 'SUR', 1000, 'RUB', 6.64),
    ('RU000A10CS75', DATE '2026-03-03', 99.29, 'SUR', 1000, 'RUB', 7.11),
    ('RU000A10CS75', DATE '2026-03-04', 99.28, 'SUR', 1000, 'RUB', 7.58),
    ('RU000A10CS75', DATE '2026-03-05', 99.22, 'SUR', 1000, 'RUB', 8.05),
    ('RU000A10CS75', DATE '2026-03-06', 99.28, 'SUR', 1000, 'RUB', 8.52),
    ('RU000A10CS75', DATE '2026-03-09', 99.3, 'SUR', 1000, 'RUB', 9.92),
    ('RU000A10CS75', DATE '2026-03-10', 99.35, 'SUR', 1000, 'RUB', 10.39),
    ('RU000A10CS75', DATE '2026-03-11', 99.33, 'SUR', 1000, 'RUB', 10.86),
    ('RU000A10CS75', DATE '2026-03-12', 99.28, 'SUR', 1000, 'RUB', 11.33),
    ('RU000A10CS75', DATE '2026-03-13', 99.33, 'SUR', 1000, 'RUB', 11.79),
    ('RU000A10CS75', DATE '2026-03-16', 99.34, 'SUR', 1000, 'RUB', 13.2),
    ('RU000A10CS75', DATE '2026-03-17', 99.31, 'SUR', 1000, 'RUB', 13.67),
    ('RU000A10CS75', DATE '2026-03-18', 99.29, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2026-03-19', 99.09, 'SUR', 1000, 'RUB', 0.47),
    ('RU000A10CS75', DATE '2026-03-20', 99.18, 'SUR', 1000, 'RUB', 0.94),
    ('RU000A10CS75', DATE '2026-03-23', 99.02, 'SUR', 1000, 'RUB', 2.34),
    ('RU000A10CS75', DATE '2026-03-24', 99.16, 'SUR', 1000, 'RUB', 2.81),
    ('RU000A10CS75', DATE '2026-03-25', 99.14, 'SUR', 1000, 'RUB', 3.28),
    ('RU000A10CS75', DATE '2026-03-26', 99.13, 'SUR', 1000, 'RUB', 3.75),
    ('RU000A10CS75', DATE '2026-03-27', 99.1, 'SUR', 1000, 'RUB', 4.22),
    ('RU000A10CS75', DATE '2026-03-30', 99.1, 'SUR', 1000, 'RUB', 5.61),
    ('RU000A10CS75', DATE '2026-03-31', 99.19, 'SUR', 1000, 'RUB', 6.06),
    ('RU000A10CS75', DATE '2026-04-01', 99.2, 'SUR', 1000, 'RUB', 6.52),
    ('RU000A10CS75', DATE '2026-04-02', 99.1, 'SUR', 1000, 'RUB', 6.97),
    ('RU000A10CS75', DATE '2026-04-03', 99.16, 'SUR', 1000, 'RUB', 7.43),
    ('RU000A10CS75', DATE '2026-04-06', 99.22, 'SUR', 1000, 'RUB', 8.79),
    ('RU000A10CS75', DATE '2026-04-07', 99.17, 'SUR', 1000, 'RUB', 9.25),
    ('RU000A10CS75', DATE '2026-04-08', 99.09, 'SUR', 1000, 'RUB', 9.7),
    ('RU000A10CS75', DATE '2026-04-09', 99.31, 'SUR', 1000, 'RUB', 10.16),
    ('RU000A10CS75', DATE '2026-04-10', 99.18, 'SUR', 1000, 'RUB', 10.61),
    ('RU000A10CS75', DATE '2026-04-13', 99.18, 'SUR', 1000, 'RUB', 11.98),
    ('RU000A10CS75', DATE '2026-04-14', 99.23, 'SUR', 1000, 'RUB', 12.43),
    ('RU000A10CS75', DATE '2026-04-15', 99.2, 'SUR', 1000, 'RUB', 12.88),
    ('RU000A10CS75', DATE '2026-04-16', 99.32, 'SUR', 1000, 'RUB', 13.34),
    ('RU000A10CS75', DATE '2026-04-17', 99.36, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2026-04-20', 99.4, 'SUR', 1000, 'RUB', 1.36),
    ('RU000A10CS75', DATE '2026-04-21', 99.3, 'SUR', 1000, 'RUB', 1.82),
    ('RU000A10CS75', DATE '2026-04-22', 99.35, 'SUR', 1000, 'RUB', 2.27),
    ('RU000A10CS75', DATE '2026-04-23', 99.39, 'SUR', 1000, 'RUB', 2.73),
    ('RU000A10CS75', DATE '2026-04-24', 99.39, 'SUR', 1000, 'RUB', 3.18),
    ('RU000A10CS75', DATE '2026-04-27', 99.39, 'SUR', 1000, 'RUB', 4.55),
    ('RU000A10CS75', DATE '2026-04-28', 99.34, 'SUR', 1000, 'RUB', 5),
    ('RU000A10CS75', DATE '2026-04-29', 99.37, 'SUR', 1000, 'RUB', 5.46),
    ('RU000A10CS75', DATE '2026-04-30', 99.24, 'SUR', 1000, 'RUB', 5.91),
    ('RU000A10CS75', DATE '2026-05-04', 99.36, 'SUR', 1000, 'RUB', 7.72),
    ('RU000A10CS75', DATE '2026-05-05', 99.39, 'SUR', 1000, 'RUB', 8.16),
    ('RU000A10CS75', DATE '2026-05-06', 99.32, 'SUR', 1000, 'RUB', 8.6),
    ('RU000A10CS75', DATE '2026-05-07', 99.37, 'SUR', 1000, 'RUB', 9.04),
    ('RU000A10CS75', DATE '2026-05-08', 99.4, 'SUR', 1000, 'RUB', 9.48),
    ('RU000A10CS75', DATE '2026-05-11', 99.38, 'SUR', 1000, 'RUB', 10.81),
    ('RU000A10CS75', DATE '2026-05-12', 99.39, 'SUR', 1000, 'RUB', 11.25),
    ('RU000A10CS75', DATE '2026-05-13', 99.2, 'SUR', 1000, 'RUB', 11.69),
    ('RU000A10CS75', DATE '2026-05-14', 99.37, 'SUR', 1000, 'RUB', 12.13),
    ('RU000A10CS75', DATE '2026-05-15', 99.45, 'SUR', 1000, 'RUB', 12.57),
    ('RU000A10CS75', DATE '2026-05-18', 99.17, 'SUR', 1000, 'RUB', 0.44),
    ('RU000A10CS75', DATE '2026-05-19', 99.2, 'SUR', 1000, 'RUB', 0.88),
    ('RU000A10CS75', DATE '2026-05-20', 99.49, 'SUR', 1000, 'RUB', 1.32),
    ('RU000A10CS75', DATE '2026-05-21', 99.46, 'SUR', 1000, 'RUB', 1.76),
    ('RU000A10CS75', DATE '2026-05-22', 99.59, 'SUR', 1000, 'RUB', 2.21),
    ('RU000A10CS75', DATE '2026-05-25', 99.4, 'SUR', 1000, 'RUB', 3.53),
    ('RU000A10CS75', DATE '2026-05-26', 99.48, 'SUR', 1000, 'RUB', 3.97),
    ('RU000A10CS75', DATE '2026-05-27', 99.46, 'SUR', 1000, 'RUB', 4.41),
    ('RU000A10CS75', DATE '2026-05-28', 99.4, 'SUR', 1000, 'RUB', 4.85),
    ('RU000A10CS75', DATE '2026-05-29', 99.43, 'SUR', 1000, 'RUB', 5.29),
    ('RU000A10CS75', DATE '2026-06-01', 99.37, 'SUR', 1000, 'RUB', 6.62),
    ('RU000A10CS75', DATE '2026-06-02', 99.5, 'SUR', 1000, 'RUB', 7.06),
    ('RU000A10CS75', DATE '2026-06-03', 99.62, 'SUR', 1000, 'RUB', 7.5),
    ('RU000A10CS75', DATE '2026-06-04', 99.64, 'SUR', 1000, 'RUB', 7.94),
    ('RU000A10CS75', DATE '2026-06-05', 99.95, 'SUR', 1000, 'RUB', 8.38),
    ('RU000A10CS75', DATE '2026-06-08', 99.82, 'SUR', 1000, 'RUB', 9.7),
    ('RU000A10CS75', DATE '2026-06-09', 99.34, 'SUR', 1000, 'RUB', 10.15),
    ('RU000A10CS75', DATE '2026-06-10', 99.57, 'SUR', 1000, 'RUB', 10.59),
    ('RU000A10CS75', DATE '2026-06-11', 99.99, 'SUR', 1000, 'RUB', 11.03),
    ('RU000A10CS75', DATE '2026-06-15', 99.98, 'SUR', 1000, 'RUB', 12.79),
    ('RU000A10CS75', DATE '2026-06-16', 99.45, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2026-06-17', 99.5, 'SUR', 1000, 'RUB', 0.44),
    ('RU000A10CS75', DATE '2026-06-18', 99.4, 'SUR', 1000, 'RUB', 0.88),
    ('RU000A10CS75', DATE '2026-06-19', 99.74, 'SUR', 1000, 'RUB', 1.32),
    ('RU000A10CS75', DATE '2026-06-22', 99.58, 'SUR', 1000, 'RUB', 2.65),
    ('RU000A10CS75', DATE '2026-06-23', 99.75, 'SUR', 1000, 'RUB', 3.09),
    ('RU000A10CS75', DATE '2026-06-24', 99.66, 'SUR', 1000, 'RUB', 3.53),
    ('RU000A10CS75', DATE '2026-06-25', 99.47, 'SUR', 1000, 'RUB', 3.97),
    ('RU000A10CS75', DATE '2026-06-26', 99.31, 'SUR', 1000, 'RUB', 4.41),
    ('RU000A10CS75', DATE '2026-06-29', 99.4, 'SUR', 1000, 'RUB', 5.73),
    ('RU000A10CS75', DATE '2026-06-30', 99.65, 'SUR', 1000, 'RUB', 6.16),
    ('RU000A10CS75', DATE '2026-07-01', 99.54, 'SUR', 1000, 'RUB', 6.6),
    ('RU000A10CS75', DATE '2026-07-02', 99.53, 'SUR', 1000, 'RUB', 7.03),
    ('RU000A10CS75', DATE '2026-07-03', 99.62, 'SUR', 1000, 'RUB', 7.46),
    ('RU000A10CS75', DATE '2026-07-06', 99.51, 'SUR', 1000, 'RUB', 8.77),
    ('RU000A10CS75', DATE '2026-07-07', 98.9, 'SUR', 1000, 'RUB', 9.2),
    ('RU000A10CS75', DATE '2026-07-08', 99.12, 'SUR', 1000, 'RUB', 9.64),
    ('RU000A10CS75', DATE '2026-07-09', 99.39, 'SUR', 1000, 'RUB', 10.07),
    ('RU000A10CS75', DATE '2026-07-10', 99.3, 'SUR', 1000, 'RUB', 10.5),
    ('RU000A10CS75', DATE '2026-07-13', 99.4, 'SUR', 1000, 'RUB', 11.81),
    ('RU000A10CS75', DATE '2026-07-14', 99.33, 'SUR', 1000, 'RUB', 12.24),
    ('RU000A10CS75', DATE '2026-07-15', 99.68, 'SUR', 1000, 'RUB', 12.68),
    ('RU000A10CS75', DATE '2026-07-16', 99.36, 'SUR', 1000, 'RUB', 0),
    ('RU000A10CS75', DATE '2026-07-17', 99.34, 'SUR', 1000, 'RUB', 0.43),
    ('RU000A10CS75', DATE '2026-07-20', 99.2, 'SUR', 1000, 'RUB', 1.74),
    ('RU000A10CS75', DATE '2026-07-21', 99.34, 'SUR', 1000, 'RUB', 2.17),
    ('RU000A10CS75', DATE '2026-07-22', 99.3, 'SUR', 1000, 'RUB', 2.61),
    ('RU000A10CS75', DATE '2026-07-23', 99.35, 'SUR', 1000, 'RUB', 3.04),
    ('RU000A10CS75', DATE '2026-07-24', 99.91, 'SUR', 1000, 'RUB', 3.47),
    ('RU000A10CS75', DATE '2026-07-27', 99.98, 'SUR', 1000, 'RUB', 4.78),
    ('RU000A10CS75', DATE '2026-07-28', 99.87, 'SUR', 1000, 'RUB', 5.21),
    ('RU000A10CS75', DATE '2026-07-29', 99.92, 'SUR', 1000, 'RUB', 5.65),
    ('RU000A10CS75', DATE '2026-07-30', 100, 'SUR', 1000, 'RUB', 6.08),
    ('RU000A10CS75', DATE '2026-07-31', 100, 'SUR', 1000, 'RUB', 6.51),
    ('RU000A10CS75', DATE '2026-08-03', 99.92, 'SUR', 1000, 'RUB', 7.81),
    ('RU000A10CS75', DATE '2026-08-04', 99.98, 'SUR', 1000, 'RUB', 8.24),
    ('RU000A10CS75', DATE '2026-08-05', 99.99, 'SUR', 1000, 'RUB', 8.66),
    ('RU000A10CS75', DATE '2026-08-06', 100, 'SUR', 1000, 'RUB', 9.09),
    ('RU000A10CS75', DATE '2026-08-07', 99.9, 'SUR', 1000, 'RUB', 9.52)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        CASE
            WHEN rb.instrument_type = 2 THEN rb.currency_id
            ELSE rb.trade_currency_id
        END AS currency_id,
        rb.trade_currency_id AS source_currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    source_currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, source_currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        source_currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        source_currency_id = EXCLUDED.source_currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    421 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 421;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2026, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2026, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2026, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2026, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
