-- Targeted MOEX price backfill for RU000A10F850 and RU000A10FA72.
-- Source: MOEX ISS TQCB history, fetched on 2026-06-11.
-- Includes completed trading days through 2026-06-10.
-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 19

BEGIN;
CREATE TEMP TABLE stg_moex_prices_src (
    ticker text NOT NULL,
    trade_date date NOT NULL,
    raw_price numeric(18,8) NOT NULL,
    trade_currency_id text NULL,
    face_value numeric(18,8) NULL,
    face_currency_id text NULL,
    accrued_interest numeric(18,8) NULL
) ON COMMIT DROP;

INSERT INTO stg_moex_prices_src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest)
VALUES
    ('RU000A10F850', DATE '2026-05-26', 99.62, 'SUR', 1000, 'RUB', 0),
    ('RU000A10F850', DATE '2026-05-27', 99.05, 'SUR', 1000, 'RUB', 0.53),
    ('RU000A10F850', DATE '2026-05-28', 99, 'SUR', 1000, 'RUB', 1.07),
    ('RU000A10F850', DATE '2026-05-29', 98.97, 'SUR', 1000, 'RUB', 1.6),
    ('RU000A10F850', DATE '2026-06-01', 98.76, 'SUR', 1000, 'RUB', 3.21),
    ('RU000A10F850', DATE '2026-06-02', 98.99, 'SUR', 1000, 'RUB', 3.74),
    ('RU000A10F850', DATE '2026-06-03', 99, 'SUR', 1000, 'RUB', 4.27),
    ('RU000A10F850', DATE '2026-06-04', 99.07, 'SUR', 1000, 'RUB', 4.81),
    ('RU000A10F850', DATE '2026-06-05', 99, 'SUR', 1000, 'RUB', 5.34),
    ('RU000A10F850', DATE '2026-06-08', 99.16, 'SUR', 1000, 'RUB', 6.95),
    ('RU000A10F850', DATE '2026-06-09', 99.09, 'SUR', 1000, 'RUB', 7.48),
    ('RU000A10F850', DATE '2026-06-10', 99.11, 'SUR', 1000, 'RUB', 8.01),
    ('RU000A10FA72', DATE '2026-06-02', 100.29, 'SUR', 1000, 'RUB', 0),
    ('RU000A10FA72', DATE '2026-06-03', 100.49, 'SUR', 1000, 'RUB', 0.48),
    ('RU000A10FA72', DATE '2026-06-04', 100.37, 'SUR', 1000, 'RUB', 0.96),
    ('RU000A10FA72', DATE '2026-06-05', 100.09, 'SUR', 1000, 'RUB', 1.44),
    ('RU000A10FA72', DATE '2026-06-08', 99.98, 'SUR', 1000, 'RUB', 2.88),
    ('RU000A10FA72', DATE '2026-06-09', 99.96, 'SUR', 1000, 'RUB', 3.36),
    ('RU000A10FA72', DATE '2026-06-10', 100.05, 'SUR', 1000, 'RUB', 3.84)
;

CREATE TEMP TABLE stg_moex_prices_resolved ON COMMIT DROP AS
WITH resolved_base AS (
    SELECT
        i.id AS instrument_id,
        src.trade_date,
        i.type AS instrument_type,
        src.raw_price,
        CASE
            WHEN upper(coalesce(src.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.trade_currency_id)
        END AS trade_currency_id,
        src.face_value,
        CASE
            WHEN upper(coalesce(src.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(src.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(src.face_currency_id)
        END AS face_currency_id,
        coalesce(src.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || src.trade_date::text || '|MOEX') AS hash_key
    FROM stg_moex_prices_src src
    JOIN LATERAL (
        SELECT instrument.*
        FROM instruments instrument
        WHERE upper(coalesce(instrument.ticker, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.isin, '')) = upper(src.ticker)
           OR upper(coalesce(instrument.figi, '')) = upper(src.ticker)
           OR EXISTS (
               SELECT 1
               FROM instrument_aliases ia
               WHERE ia.instrument_id = instrument.id
                 AND upper(ia.normalized_alias_code) = upper(src.ticker)
           )
        ORDER BY
            CASE WHEN upper(coalesce(instrument.ticker, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.isin, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            CASE WHEN upper(coalesce(instrument.figi, '')) = upper(src.ticker) THEN 0 ELSE 1 END,
            instrument.created_at
        LIMIT 1
    ) i ON TRUE
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        CASE
            WHEN rb.instrument_type = 2 THEN rb.currency_id
            ELSE rb.trade_currency_id
        END AS currency_id,
        rb.trade_currency_id AS source_currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
SELECT
    instrument_id,
    trade_date,
    price,
    currency_id,
    source_currency_id,
    hash_key
FROM resolved;

WITH upserted AS (
    INSERT INTO prices (id, instrument_id, date, value, currency_id, source_currency_id, provider, created_at, updated_at)
    SELECT
        (
            substr(hash_key, 1, 8) || '-' ||
            substr(hash_key, 9, 4) || '-' ||
            substr(hash_key, 13, 4) || '-' ||
            substr(hash_key, 17, 4) || '-' ||
            substr(hash_key, 21, 12)
        )::uuid,
        instrument_id,
        (trade_date::timestamp AT TIME ZONE 'UTC'),
        price,
        currency_id,
        source_currency_id,
        'MOEX',
        now(),
        now()
    FROM stg_moex_prices_resolved
    ON CONFLICT (instrument_id, date, provider)
    DO UPDATE
    SET value = EXCLUDED.value,
        currency_id = EXCLUDED.currency_id,
        source_currency_id = EXCLUDED.source_currency_id,
        updated_at = now()
    RETURNING instrument_id
)
SELECT
    19 AS expected_rows,
    (SELECT count(*) FROM stg_moex_prices_resolved) AS resolved_rows,
    count(*) AS applied_rows
FROM upserted;

DO $$
DECLARE
    expected_rows integer := 19;
    source_rows integer;
    resolved_rows integer;
    applied_rows integer;
BEGIN
    SELECT count(*) INTO source_rows FROM stg_moex_prices_src;
    SELECT count(*) INTO resolved_rows FROM stg_moex_prices_resolved;
    SELECT count(*)
    INTO applied_rows
    FROM prices p
    JOIN stg_moex_prices_resolved r
      ON r.instrument_id = p.instrument_id
     AND p.date = (r.trade_date::timestamp AT TIME ZONE 'UTC')
     AND upper(p.provider) = 'MOEX';

    IF source_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % source rows, got % in staging.', 2026, expected_rows, source_rows;
    END IF;

    IF resolved_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % resolved rows, got %.', 2026, expected_rows, resolved_rows;
    END IF;

    IF applied_rows <> expected_rows THEN
        RAISE EXCEPTION 'MOEX % validation failed: expected % applied rows, got %.', 2026, expected_rows, applied_rows;
    END IF;

    RAISE NOTICE 'MOEX % validation passed: expected %, resolved %, applied %.', 2026, expected_rows, resolved_rows, applied_rows;
END $$;

COMMIT;
