-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 48

BEGIN;
WITH src (ticker, trade_date, raw_price, trade_currency_id, face_value, face_currency_id, accrued_interest) AS (
    VALUES
    ('RU000A103BR0', DATE '2026-01-05', 63.151, 'SUR', 1000, 'RUB', 27.8),
    ('RU000A103BR0', DATE '2026-01-06', 63.237, 'SUR', 1000, 'RUB', 28),
    ('RU000A103BR0', DATE '2026-01-08', 63.395, 'SUR', 1000, 'RUB', 28.38),
    ('RU000A103BR0', DATE '2026-01-09', 63.349, 'SUR', 1000, 'RUB', 28.57),
    ('RU000A103BR0', DATE '2026-01-12', 62.392, 'SUR', 1000, 'RUB', 29.15),
    ('RU000A103BR0', DATE '2026-01-13', 62.143, 'SUR', 1000, 'RUB', 29.34),
    ('RU000A103BR0', DATE '2026-01-14', 62.329, 'SUR', 1000, 'RUB', 29.53),
    ('RU000A103BR0', DATE '2026-01-15', 62.3, 'SUR', 1000, 'RUB', 29.72),
    ('RU000A103BR0', DATE '2026-01-16', 62.4, 'SUR', 1000, 'RUB', 29.91),
    ('RU000A103BR0', DATE '2026-01-19', 62.39, 'SUR', 1000, 'RUB', 30.49),
    ('RU000A103BR0', DATE '2026-01-20', 62.392, 'SUR', 1000, 'RUB', 30.68),
    ('RU000A103BR0', DATE '2026-01-21', 62.379, 'SUR', 1000, 'RUB', 30.87),
    ('RU000A103BR0', DATE '2026-01-22', 62.424, 'SUR', 1000, 'RUB', 31.06),
    ('RU000A103BR0', DATE '2026-01-23', 62.22, 'SUR', 1000, 'RUB', 31.26),
    ('RU000A103BR0', DATE '2026-01-26', 61.997, 'SUR', 1000, 'RUB', 31.83),
    ('RU000A103BR0', DATE '2026-01-27', 61.86, 'SUR', 1000, 'RUB', 32.02),
    ('RU000A103BR0', DATE '2026-01-28', 61.896, 'SUR', 1000, 'RUB', 32.22),
    ('RU000A103BR0', DATE '2026-01-29', 62.09, 'SUR', 1000, 'RUB', 32.41),
    ('RU000A103BR0', DATE '2026-01-30', 62.132, 'SUR', 1000, 'RUB', 32.6),
    ('RU000A103BR0', DATE '2026-02-02', 62.02, 'SUR', 1000, 'RUB', 33.17),
    ('RU000A103BR0', DATE '2026-02-03', 62.071, 'SUR', 1000, 'RUB', 33.37),
    ('RU000A103BR0', DATE '2026-02-04', 62.08, 'SUR', 1000, 'RUB', 33.56),
    ('RU000A103BR0', DATE '2026-02-05', 61.926, 'SUR', 1000, 'RUB', 33.75),
    ('RU000A103BR0', DATE '2026-02-06', 61.653, 'SUR', 1000, 'RUB', 33.94),
    ('RU000A103BR0', DATE '2026-02-09', 61.58, 'SUR', 1000, 'RUB', 34.52),
    ('RU000A103BR0', DATE '2026-02-10', 61.409, 'SUR', 1000, 'RUB', 34.71),
    ('RU000A103BR0', DATE '2026-02-11', 61.577, 'SUR', 1000, 'RUB', 0),
    ('RU000A103BR0', DATE '2026-02-12', 62.06, 'SUR', 1000, 'RUB', 0.19),
    ('RU000A103BR0', DATE '2026-02-13', 62.929, 'SUR', 1000, 'RUB', 0.38),
    ('RU000A103BR0', DATE '2026-02-16', 62.799, 'SUR', 1000, 'RUB', 0.96),
    ('RU000A103BR0', DATE '2026-02-17', 62.9, 'SUR', 1000, 'RUB', 1.15),
    ('RU000A103BR0', DATE '2026-02-18', 63.106, 'SUR', 1000, 'RUB', 1.34),
    ('RU000A103BR0', DATE '2026-02-19', 63.034, 'SUR', 1000, 'RUB', 1.53),
    ('RU000A103BR0', DATE '2026-02-20', 62.915, 'SUR', 1000, 'RUB', 1.73),
    ('RU000A103BR0', DATE '2026-02-24', 62.809, 'SUR', 1000, 'RUB', 2.49),
    ('RU000A103BR0', DATE '2026-02-25', 62.796, 'SUR', 1000, 'RUB', 2.68),
    ('RU000A103BR0', DATE '2026-02-26', 62.652, 'SUR', 1000, 'RUB', 2.88),
    ('RU000A103BR0', DATE '2026-02-27', 62.801, 'SUR', 1000, 'RUB', 3.07),
    ('RU000A103BR0', DATE '2026-03-02', 62.624, 'SUR', 1000, 'RUB', 3.64),
    ('RU000A103BR0', DATE '2026-03-03', 62.615, 'SUR', 1000, 'RUB', 3.84),
    ('RU000A103BR0', DATE '2026-03-04', 62.41, 'SUR', 1000, 'RUB', 4.03),
    ('RU000A103BR0', DATE '2026-03-05', 62.358, 'SUR', 1000, 'RUB', 4.22),
    ('RU000A103BR0', DATE '2026-03-06', 62.41, 'SUR', 1000, 'RUB', 4.41),
    ('RU000A103BR0', DATE '2026-03-09', 62.885, 'SUR', 1000, 'RUB', 4.99),
    ('RU000A103BR0', DATE '2026-03-10', 62.624, 'SUR', 1000, 'RUB', 5.18),
    ('RU000A103BR0', DATE '2026-03-11', 62.487, 'SUR', 1000, 'RUB', 5.37),
    ('RU000A103BR0', DATE '2026-03-12', 63.201, 'SUR', 1000, 'RUB', 5.56),
    ('RU000A103BR0', DATE '2026-03-13', 63.44, 'SUR', 1000, 'RUB', 5.75)
),
resolved_base AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        i.type AS instrument_type,
        s.raw_price,
        CASE
            WHEN upper(coalesce(s.trade_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(s.trade_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(s.trade_currency_id)
        END AS trade_currency_id,
        s.face_value,
        CASE
            WHEN upper(coalesce(s.face_currency_id, '')) IN ('SUR', 'RUR') THEN 'RUB'
            WHEN nullif(upper(coalesce(s.face_currency_id, '')), '') IS NULL THEN i.currency_id
            ELSE upper(s.face_currency_id)
        END AS face_currency_id,
        coalesce(s.accrued_interest, 0) AS accrued_interest,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|MOEX') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.ticker) = s.ticker
),
resolved AS (
    SELECT
        rb.instrument_id,
        rb.trade_date,
        CASE
            WHEN rb.instrument_type = 2 AND coalesce(rb.face_value, 0) > 0 THEN (
                CASE
                    WHEN rb.face_currency_id = rb.currency_id THEN (rb.raw_price / 100.0) * rb.face_value
                    WHEN clean_direct.rate IS NOT NULL THEN ((rb.raw_price / 100.0) * rb.face_value) * clean_direct.rate
                    WHEN clean_inverse.rate IS NOT NULL AND clean_inverse.rate <> 0 THEN ((rb.raw_price / 100.0) * rb.face_value) / clean_inverse.rate
                    ELSE (rb.raw_price / 100.0) * rb.face_value
                END
                +
                CASE
                    WHEN rb.accrued_interest = 0 THEN 0
                    WHEN rb.trade_currency_id = rb.currency_id THEN rb.accrued_interest
                    WHEN accrued_direct.rate IS NOT NULL THEN rb.accrued_interest * accrued_direct.rate
                    WHEN accrued_inverse.rate IS NOT NULL AND accrued_inverse.rate <> 0 THEN rb.accrued_interest / accrued_inverse.rate
                    ELSE rb.accrued_interest
                END
            )::numeric(18,4)
            ELSE rb.raw_price::numeric(18,4)
        END AS price,
        rb.currency_id,
        rb.hash_key
    FROM resolved_base rb
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.face_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.face_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS clean_inverse ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.trade_currency_id
          AND fx.quote_currency_id = rb.currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_direct ON true
    LEFT JOIN LATERAL (
        SELECT fx.rate
        FROM fx_rates fx
        WHERE fx.base_currency_id = rb.currency_id
          AND fx.quote_currency_id = rb.trade_currency_id
          AND fx.date::date <= rb.trade_date
        ORDER BY fx.date DESC, fx.created_at DESC
        LIMIT 1
    ) AS accrued_inverse ON true
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'MOEX',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
