// <auto-generated />
using System;
using Larchik.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Larchik.Persistence.Migrations
{
    [DbContext(typeof(LarchikContext))]
    [Migration("20260311182900_IncreaseOperationPricePrecision")]
    partial class IncreaseOperationPricePrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Larchik.Persistence.Entities.AppUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7e89d7d2-21e2-40ce-bef2-58c3b9408abb"),
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "c53a3830-3f86-4505-bcdb-1d2d2f87c006",
                            Email = "admin@test.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@TEST.COM",
                            NormalizedUserName = "ADMIN",
                            PasswordHash = "AQAAAAIAAYagAAAAELetNQlOXe6IFms9D+H9cktwcVgon6E7yho5xMfUV8vbI8lfSldk14mcajcwvxJeBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "f3359b6674a7407793f4e0371c477b60",
                            TwoFactorEnabled = false,
                            UserName = "admin"
                        });
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Broker", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_brokers");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_brokers_code");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_brokers_name");

                    b.ToTable("brokers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("0d30ef6c-f09f-44da-8bf0-a20001c4c001"),
                            Code = "sber",
                            Country = "Россия",
                            Name = "СберБанк"
                        },
                        new
                        {
                            Id = new Guid("4ee304a8-6f0a-490f-bfa5-58f6f958b002"),
                            Code = "vtb",
                            Country = "Россия",
                            Name = "ВТБ"
                        },
                        new
                        {
                            Id = new Guid("f6f784ea-b520-4bc5-8a32-9a17f1637003"),
                            Code = "tbank",
                            Country = "Россия",
                            Name = "Т-Банк"
                        },
                        new
                        {
                            Id = new Guid("f444bdaf-bcb7-41fa-b22d-5a2fd7d5e004"),
                            Code = "alfabank",
                            Country = "Россия",
                            Name = "Альфа-Банк"
                        },
                        new
                        {
                            Id = new Guid("47096031-0778-4a7e-8552-57a7f6b4d005"),
                            Code = "gazprombank",
                            Country = "Россия",
                            Name = "Газпромбанк"
                        },
                        new
                        {
                            Id = new Guid("4f3178f2-218d-4802-8e38-68af3a972006"),
                            Code = "rshb",
                            Country = "Россия",
                            Name = "Россельхозбанк"
                        },
                        new
                        {
                            Id = new Guid("802c7a07-532b-4c22-a8ac-05f984052007"),
                            Code = "psb",
                            Country = "Россия",
                            Name = "Промсвязьбанк"
                        },
                        new
                        {
                            Id = new Guid("65db9cc2-5f8f-4a53-a37a-6abcf217d008"),
                            Code = "sovcombank",
                            Country = "Россия",
                            Name = "Совкомбанк"
                        },
                        new
                        {
                            Id = new Guid("1634010e-bf7a-4e0c-89c8-643cde8d6009"),
                            Code = "raiffeisen",
                            Country = "Россия",
                            Name = "Райффайзенбанк"
                        },
                        new
                        {
                            Id = new Guid("8f3f0f71-ec6f-4f16-960b-a8440deeb010"),
                            Code = "bcs",
                            Country = "Россия",
                            Name = "БКС Мир инвестиций"
                        },
                        new
                        {
                            Id = new Guid("d040def8-f06d-4602-b350-5c30d9f06011"),
                            Code = "finam",
                            Country = "Россия",
                            Name = "ФИНАМ"
                        },
                        new
                        {
                            Id = new Guid("20237c6b-3956-4228-ab4e-a4f4c7f1c012"),
                            Code = "aton",
                            Country = "Россия",
                            Name = "АТОН"
                        },
                        new
                        {
                            Id = new Guid("2f6dd2e6-c1bf-4eec-b024-f7570ab70013"),
                            Code = "kitfinance",
                            Country = "Россия",
                            Name = "КИТ Финанс Брокер"
                        },
                        new
                        {
                            Id = new Guid("ebff8036-ab31-4e47-ae04-59071f66b014"),
                            Code = "cifra",
                            Country = "Россия",
                            Name = "Цифра брокер"
                        },
                        new
                        {
                            Id = new Guid("2f54daf8-1f36-4428-9580-28c3fe307015"),
                            Code = "akbars",
                            Country = "Россия",
                            Name = "Ак Барс Банк"
                        },
                        new
                        {
                            Id = new Guid("1a9e3959-acf8-4936-a90d-90cb9ce98016"),
                            Code = "uralsib",
                            Country = "Россия",
                            Name = "Банк Уралсиб"
                        },
                        new
                        {
                            Id = new Guid("dc8f9da6-5d31-4dd8-a314-6fa3774e3017"),
                            Code = "mtsbank",
                            Country = "Россия",
                            Name = "МТС Банк"
                        },
                        new
                        {
                            Id = new Guid("677f0251-0b17-48c5-b14b-37f490ec2018"),
                            Code = "bspb",
                            Country = "Россия",
                            Name = "Банк Санкт-Петербург"
                        },
                        new
                        {
                            Id = new Guid("935c6579-7695-43bf-8d8c-d6268bc7f019"),
                            Code = "mkb",
                            Country = "Россия",
                            Name = "МКБ"
                        },
                        new
                        {
                            Id = new Guid("348c1aa0-5480-4fa1-a719-b36eb88dd020"),
                            Code = "investpalata",
                            Country = "Россия",
                            Name = "Инвестиционная палата"
                        });
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.CashBalance", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cash_balances");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_cash_balances_currency_id");

                    b.HasIndex("PortfolioId", "CurrencyId")
                        .IsUnique()
                        .HasDatabaseName("ix_cash_balances_portfolio_id_currency_id");

                    b.ToTable("cash_balances", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_categories");

                    b.ToTable("categories", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Валюта"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Финансы и банки"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Телекоммуникации"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Информационные технологии"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Энергетика"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Потребительские товары"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Недвижимость"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Валюта"
                        },
                        new
                        {
                            Id = 9,
                            Name = "Электроэнергетика"
                        },
                        new
                        {
                            Id = 10,
                            Name = "Сырьевая промышленность"
                        });
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Currency", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("id");

                    b.HasKey("Id")
                        .HasName("pk_currencies");

                    b.ToTable("currencies", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "RUB"
                        },
                        new
                        {
                            Id = "USD"
                        },
                        new
                        {
                            Id = "EUR"
                        });
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.FxRate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BaseCurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("base_currency_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<string>("QuoteCurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("quote_currency_id");

                    b.Property<decimal>("Rate")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("rate");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("source");

                    b.HasKey("Id")
                        .HasName("pk_fx_rates");

                    b.HasIndex("QuoteCurrencyId")
                        .HasDatabaseName("ix_fx_rates_quote_currency_id");

                    b.HasIndex("BaseCurrencyId", "QuoteCurrencyId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_fx_rates_base_currency_id_quote_currency_id_date");

                    b.ToTable("fx_rates", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Instrument", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer")
                        .HasColumnName("category_id");

                    b.Property<string>("Country")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("country");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("created_by");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<string>("Exchange")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("exchange");

                    b.Property<string>("Figi")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("figi");

                    b.Property<string>("Isin")
                        .IsRequired()
                        .HasMaxLength(12)
                        .HasColumnType("character varying(12)")
                        .HasColumnName("isin");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<decimal?>("Price")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("price");

                    b.Property<string>("Ticker")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("ticker");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_instruments");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_instruments_category_id");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_instruments_currency_id");

                    b.HasIndex("Figi")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_figi");

                    b.HasIndex("Isin")
                        .IsUnique()
                        .HasDatabaseName("ix_instruments_isin");

                    b.HasIndex("Ticker")
                        .HasDatabaseName("ix_instruments_ticker");

                    b.ToTable("instruments", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.JobDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("job_type");

                    b.Property<DateTime?>("LastRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_run_at");

                    b.Property<int>("LockTimeoutMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("lock_timeout_minutes");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<DateTime>("NextRunAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_run_at");

                    b.Property<int>("RetryDelayMinutes")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(15)
                        .HasColumnName("retry_delay_minutes");

                    b.Property<int>("ScheduleType")
                        .HasColumnType("integer")
                        .HasColumnName("schedule_type");

                    b.Property<string>("ScheduleValue")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("schedule_value");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_definitions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_job_definitions_name");

                    b.HasIndex("IsEnabled", "NextRunAt")
                        .HasDatabaseName("ix_job_definitions_is_enabled_next_run_at");

                    b.ToTable("job_definitions", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.JobRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Attempt")
                        .HasColumnType("integer")
                        .HasColumnName("attempt");

                    b.Property<DateTime>("AvailableAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("available_at");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DedupKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("dedup_key");

                    b.Property<Guid>("JobDefinitionId")
                        .HasColumnType("uuid")
                        .HasColumnName("job_definition_id");

                    b.Property<string>("LastError")
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)")
                        .HasColumnName("last_error");

                    b.Property<string>("LockedBy")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("locked_by");

                    b.Property<DateTime?>("LockedUntilAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("locked_until_at");

                    b.Property<int>("MaxAttempts")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(5)
                        .HasColumnName("max_attempts");

                    b.Property<string>("PayloadJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload_json");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_job_runs");

                    b.HasIndex("DedupKey")
                        .IsUnique()
                        .HasDatabaseName("ix_job_runs_dedup_key");

                    b.HasIndex("LockedUntilAt")
                        .HasDatabaseName("ix_job_runs_locked_until_at");

                    b.HasIndex("JobDefinitionId", "CreatedAt")
                        .HasDatabaseName("ix_job_runs_job_definition_id_created_at");

                    b.HasIndex("Status", "AvailableAt")
                        .HasDatabaseName("ix_job_runs_status_available_at");

                    b.ToTable("job_runs", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Lot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Cost")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<int>("Method")
                        .HasColumnType("integer")
                        .HasColumnName("method");

                    b.Property<DateTime>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RemainingQuantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("remaining_quantity");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_lots");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_lots_currency_id");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_lots_instrument_id");

                    b.HasIndex("PortfolioId", "InstrumentId", "Method")
                        .HasDatabaseName("ix_lots_portfolio_id_instrument_id_method");

                    b.ToTable("lots", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Operation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("fee");

                    b.Property<Guid?>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("note");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Price")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("price");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<DateTime?>("SettlementDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("settlement_date");

                    b.Property<DateTime>("TradeDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("trade_date");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_operations");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_operations_currency_id");

                    b.HasIndex("InstrumentId", "TradeDate")
                        .HasDatabaseName("ix_operations_instrument_id_trade_date");

                    b.HasIndex("PortfolioId", "TradeDate")
                        .HasDatabaseName("ix_operations_portfolio_id_trade_date");

                    b.ToTable("operations", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Portfolio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BrokerId")
                        .HasColumnType("uuid")
                        .HasColumnName("broker_id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<string>("ReportingCurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("reporting_currency_id");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolios");

                    b.HasIndex("BrokerId")
                        .HasDatabaseName("ix_portfolios_broker_id");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_portfolios_user_id");

                    b.ToTable("portfolios", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.PortfolioSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CashBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cash_base");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<decimal>("NavBase")
                        .HasPrecision(20, 4)
                        .HasColumnType("numeric(20,4)")
                        .HasColumnName("nav_base");

                    b.Property<decimal>("PnlDayBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pnl_day_base");

                    b.Property<decimal>("PnlMonthBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pnl_month_base");

                    b.Property<decimal>("PnlYearBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("pnl_year_base");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.HasKey("Id")
                        .HasName("pk_portfolio_snapshots");

                    b.HasIndex("PortfolioId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_portfolio_snapshots_portfolio_id_date");

                    b.ToTable("portfolio_snapshots", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.PositionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("CostBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("cost_base");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<decimal>("MarketValueBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("market_value_base");

                    b.Property<Guid>("PortfolioId")
                        .HasColumnType("uuid")
                        .HasColumnName("portfolio_id");

                    b.Property<decimal>("Quantity")
                        .HasPrecision(18, 6)
                        .HasColumnType("numeric(18,6)")
                        .HasColumnName("quantity");

                    b.Property<decimal>("RealizedBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("realized_base");

                    b.Property<decimal>("UnrealizedBase")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("unrealized_base");

                    b.HasKey("Id")
                        .HasName("pk_position_snapshots");

                    b.HasIndex("InstrumentId")
                        .HasDatabaseName("ix_position_snapshots_instrument_id");

                    b.HasIndex("PortfolioId", "InstrumentId", "Date")
                        .IsUnique()
                        .HasDatabaseName("ix_position_snapshots_portfolio_id_instrument_id_date");

                    b.ToTable("position_snapshots", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Price", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CurrencyId")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency_id");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("date");

                    b.Property<Guid>("InstrumentId")
                        .HasColumnType("uuid")
                        .HasColumnName("instrument_id");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("provider");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<decimal>("Value")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_prices");

                    b.HasIndex("CurrencyId")
                        .HasDatabaseName("ix_prices_currency_id");

                    b.HasIndex("InstrumentId", "Date", "Provider")
                        .IsUnique()
                        .HasDatabaseName("ix_prices_instrument_id_date_provider");

                    b.ToTable("prices", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("e5165cd8-4c41-4cc2-8aad-47b879f9da38"),
                            ConcurrencyStamp = "d0ac7814-1576-4ea7-9614-234f86ff37b1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = new Guid("7e89d7d2-21e2-40ce-bef2-58c3b9408abb"),
                            RoleId = new Guid("e5165cd8-4c41-4cc2-8aad-47b879f9da38")
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.CashBalance", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_balances_currencies_currency_id");

                    b.HasOne("Larchik.Persistence.Entities.Portfolio", "Portfolio")
                        .WithMany("CashBalances")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cash_balances_portfolios_portfolio_id");

                    b.Navigation("Currency");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.FxRate", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Currency", "BaseCurrency")
                        .WithMany()
                        .HasForeignKey("BaseCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fx_rates_currencies_base_currency_id");

                    b.HasOne("Larchik.Persistence.Entities.Currency", "QuoteCurrency")
                        .WithMany()
                        .HasForeignKey("QuoteCurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_fx_rates_currencies_quote_currency_id");

                    b.Navigation("BaseCurrency");

                    b.Navigation("QuoteCurrency");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Instrument", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_categories_category_id");

                    b.HasOne("Larchik.Persistence.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_instruments_currencies_currency_id");

                    b.Navigation("Category");

                    b.Navigation("Currency");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.JobRun", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.JobDefinition", "JobDefinition")
                        .WithMany("Runs")
                        .HasForeignKey("JobDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_job_runs_job_definitions_job_definition_id");

                    b.Navigation("JobDefinition");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Lot", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lots_currencies_currency_id");

                    b.HasOne("Larchik.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lots_instruments_instrument_id");

                    b.HasOne("Larchik.Persistence.Entities.Portfolio", "Portfolio")
                        .WithMany()
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lots_portfolios_portfolio_id");

                    b.Navigation("Currency");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Operation", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operations_currencies_currency_id");

                    b.HasOne("Larchik.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .HasConstraintName("fk_operations_instruments_instrument_id");

                    b.HasOne("Larchik.Persistence.Entities.Portfolio", "Portfolio")
                        .WithMany("Operations")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_operations_portfolios_portfolio_id");

                    b.Navigation("Currency");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Portfolio", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Broker", "Broker")
                        .WithMany("Portfolios")
                        .HasForeignKey("BrokerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_brokers_broker_id");

                    b.HasOne("Larchik.Persistence.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolios_users_user_id");

                    b.Navigation("Broker");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.PortfolioSnapshot", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Portfolio", "Portfolio")
                        .WithMany("PortfolioSnapshots")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_portfolio_snapshots_portfolios_portfolio_id");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.PositionSnapshot", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_snapshots_instruments_instrument_id");

                    b.HasOne("Larchik.Persistence.Entities.Portfolio", "Portfolio")
                        .WithMany("PositionSnapshots")
                        .HasForeignKey("PortfolioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_position_snapshots_portfolios_portfolio_id");

                    b.Navigation("Instrument");

                    b.Navigation("Portfolio");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Price", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.Currency", "Currency")
                        .WithMany()
                        .HasForeignKey("CurrencyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_currencies_currency_id");

                    b.HasOne("Larchik.Persistence.Entities.Instrument", "Instrument")
                        .WithMany()
                        .HasForeignKey("InstrumentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_prices_instruments_instrument_id");

                    b.Navigation("Currency");

                    b.Navigation("Instrument");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("Larchik.Persistence.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Larchik.Persistence.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Broker", b =>
                {
                    b.Navigation("Portfolios");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.JobDefinition", b =>
                {
                    b.Navigation("Runs");
                });

            modelBuilder.Entity("Larchik.Persistence.Entities.Portfolio", b =>
                {
                    b.Navigation("CashBalances");

                    b.Navigation("Operations");

                    b.Navigation("PortfolioSnapshots");

                    b.Navigation("PositionSnapshots");
                });
#pragma warning restore 612, 618
        }
    }
}
