-- Generated by scripts/moex_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: MOEX
-- Rows: 86

BEGIN;
WITH src (ticker, trade_date, price) AS (
    VALUES
    ('RU000A10AS02', DATE '2026-01-05', 104.7),
    ('RU000A10AS02', DATE '2026-01-06', 105.34),
    ('RU000A10AS02', DATE '2026-01-08', 106.04),
    ('RU000A10AS02', DATE '2026-01-09', 105.95),
    ('RU000A10AS02', DATE '2026-01-12', 105),
    ('RU000A10AS02', DATE '2026-01-13', 105.25),
    ('RU000A10AS02', DATE '2026-01-14', 105.78),
    ('RU000A10AS02', DATE '2026-01-15', 105.2),
    ('RU000A10AS02', DATE '2026-01-16', 105.83),
    ('RU000A10AS02', DATE '2026-01-19', 105.89),
    ('RU000A10AS02', DATE '2026-01-20', 105.79),
    ('RU000A10AS02', DATE '2026-01-21', 106.28),
    ('RU000A10AS02', DATE '2026-01-22', 106.47),
    ('RU000A10AS02', DATE '2026-01-23', 107.12),
    ('RU000A10AS02', DATE '2026-01-26', 106.26),
    ('RU000A10AS02', DATE '2026-01-27', 106.3),
    ('RU000A10AS02', DATE '2026-01-28', 106.15),
    ('RU000A10AS02', DATE '2026-01-29', 105.83),
    ('RU000A10AS02', DATE '2026-01-30', 106.58),
    ('RU000A10AS02', DATE '2026-02-02', 105.89),
    ('RU000A10AS02', DATE '2026-02-03', 104.99),
    ('RU000A10AS02', DATE '2026-02-04', 105.44),
    ('RU000A10AS02', DATE '2026-02-05', 104.71),
    ('RU000A10AS02', DATE '2026-02-06', 104.39),
    ('RU000A10AS02', DATE '2026-02-09', 103.83),
    ('RU000A10AS02', DATE '2026-02-10', 103.86),
    ('RU000A10AS02', DATE '2026-02-11', 103.24),
    ('RU000A10AS02', DATE '2026-02-12', 103.8),
    ('RU000A10AS02', DATE '2026-02-13', 105.7),
    ('RU000A10AS02', DATE '2026-02-16', 105.19),
    ('RU000A10AS02', DATE '2026-02-17', 105.06),
    ('RU000A10AS02', DATE '2026-02-18', 105.38),
    ('RU000A10AS02', DATE '2026-02-19', 104.46),
    ('RU000A10AS02', DATE '2026-02-20', 105.28),
    ('RU000A10AS02', DATE '2026-02-24', 104.83),
    ('RU000A10AS02', DATE '2026-02-25', 105.2),
    ('RU000A10AS02', DATE '2026-02-26', 105.42),
    ('RU000A10AS02', DATE '2026-02-27', 106.22),
    ('RU000A10AS02', DATE '2026-03-02', 106.78),
    ('RU000A10AS02', DATE '2026-03-03', 107.58),
    ('RU000A10AS02', DATE '2026-03-04', 107.19),
    ('RU000A10AS02', DATE '2026-03-05', 106.26),
    ('RU000A10AS02', DATE '2026-03-06', 106.86),
    ('RU000A10AV15', DATE '2026-01-05', 106.17),
    ('RU000A10AV15', DATE '2026-01-06', 106.23),
    ('RU000A10AV15', DATE '2026-01-08', 106.7),
    ('RU000A10AV15', DATE '2026-01-09', 106.75),
    ('RU000A10AV15', DATE '2026-01-12', 106.03),
    ('RU000A10AV15', DATE '2026-01-13', 106.1),
    ('RU000A10AV15', DATE '2026-01-14', 105.99),
    ('RU000A10AV15', DATE '2026-01-15', 105.44),
    ('RU000A10AV15', DATE '2026-01-16', 105.55),
    ('RU000A10AV15', DATE '2026-01-19', 105.52),
    ('RU000A10AV15', DATE '2026-01-20', 105.75),
    ('RU000A10AV15', DATE '2026-01-21', 105.53),
    ('RU000A10AV15', DATE '2026-01-22', 105.45),
    ('RU000A10AV15', DATE '2026-01-23', 105.34),
    ('RU000A10AV15', DATE '2026-01-26', 104.24),
    ('RU000A10AV15', DATE '2026-01-27', 104.95),
    ('RU000A10AV15', DATE '2026-01-28', 104.25),
    ('RU000A10AV15', DATE '2026-01-29', 103.81),
    ('RU000A10AV15', DATE '2026-01-30', 104.38),
    ('RU000A10AV15', DATE '2026-02-02', 105.03),
    ('RU000A10AV15', DATE '2026-02-03', 105.14),
    ('RU000A10AV15', DATE '2026-02-04', 105.11),
    ('RU000A10AV15', DATE '2026-02-05', 104.98),
    ('RU000A10AV15', DATE '2026-02-06', 104.5),
    ('RU000A10AV15', DATE '2026-02-09', 104.38),
    ('RU000A10AV15', DATE '2026-02-10', 104),
    ('RU000A10AV15', DATE '2026-02-11', 103.64),
    ('RU000A10AV15', DATE '2026-02-12', 103.9),
    ('RU000A10AV15', DATE '2026-02-13', 104.02),
    ('RU000A10AV15', DATE '2026-02-16', 104.01),
    ('RU000A10AV15', DATE '2026-02-17', 104.31),
    ('RU000A10AV15', DATE '2026-02-18', 103.56),
    ('RU000A10AV15', DATE '2026-02-19', 103.52),
    ('RU000A10AV15', DATE '2026-02-20', 103.78),
    ('RU000A10AV15', DATE '2026-02-24', 104.17),
    ('RU000A10AV15', DATE '2026-02-25', 103.62),
    ('RU000A10AV15', DATE '2026-02-26', 103.73),
    ('RU000A10AV15', DATE '2026-02-27', 104.29),
    ('RU000A10AV15', DATE '2026-03-02', 103.2),
    ('RU000A10AV15', DATE '2026-03-03', 103.29),
    ('RU000A10AV15', DATE '2026-03-04', 103.88),
    ('RU000A10AV15', DATE '2026-03-05', 103.88),
    ('RU000A10AV15', DATE '2026-03-06', 103.83)
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|MOEX') AS hash_key
    FROM src s
    JOIN instruments i ON upper(i.ticker) = s.ticker
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'MOEX',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
