-- Generated by scripts/tbank_history/generate_prices_sql.sh
-- Year: 2026
-- Provider: TBANK
-- Rows: 96

BEGIN;
WITH src (db_code, trade_date, price) AS (
    VALUES
    ('USDRUB_TOM', DATE '2026-01-05', 78.2267),
    ('USDRUB_TOM', DATE '2026-01-06', 78.2267),
    ('USDRUB_TOM', DATE '2026-01-08', 78.2267),
    ('USDRUB_TOM', DATE '2026-01-09', 78.2267),
    ('USDRUB_TOM', DATE '2026-01-12', 78.7913),
    ('USDRUB_TOM', DATE '2026-01-13', 78.8527),
    ('USDRUB_TOM', DATE '2026-01-14', 78.5711),
    ('USDRUB_TOM', DATE '2026-01-15', 78.528),
    ('USDRUB_TOM', DATE '2026-01-16', 77.8332),
    ('USDRUB_TOM', DATE '2026-01-19', 77.7586),
    ('USDRUB_TOM', DATE '2026-01-20', 77.8247),
    ('USDRUB_TOM', DATE '2026-01-21', 77.5159),
    ('USDRUB_TOM', DATE '2026-01-22', 76.0382),
    ('USDRUB_TOM', DATE '2026-01-23', 75.9246),
    ('USDRUB_TOM', DATE '2026-01-26', 76.0101),
    ('USDRUB_TOM', DATE '2026-01-27', 76.5519),
    ('USDRUB_TOM', DATE '2026-01-28', 76.2662),
    ('USDRUB_TOM', DATE '2026-01-29', 76.0251),
    ('USDRUB_TOM', DATE '2026-01-30', 75.7327),
    ('USDRUB_TOM', DATE '2026-02-02', 77.0223),
    ('USDRUB_TOM', DATE '2026-02-03', 76.9817),
    ('USDRUB_TOM', DATE '2026-02-04', 76.9102),
    ('USDRUB_TOM', DATE '2026-02-05', 76.5523),
    ('USDRUB_TOM', DATE '2026-02-06', 77.054),
    ('USDRUB_TOM', DATE '2026-02-09', 77.6502),
    ('USDRUB_TOM', DATE '2026-02-10', 77.2091),
    ('USDRUB_TOM', DATE '2026-02-11', 77.4648),
    ('USDRUB_TOM', DATE '2026-02-12', 77.188),
    ('USDRUB_TOM', DATE '2026-02-13', 77.1944),
    ('USDRUB_TOM', DATE '2026-02-16', 76.3),
    ('USDRUB_TOM', DATE '2026-02-17', 75.64),
    ('USDRUB_TOM', DATE '2026-02-18', 76.1524),
    ('USDRUB_TOM', DATE '2026-02-19', 75.54),
    ('USDRUB_TOM', DATE '2026-02-20', 76.05),
    ('USDRUB_TOM', DATE '2026-02-24', 76.6342),
    ('USDRUB_TOM', DATE '2026-02-25', 77.13),
    ('USDRUB_TOM', DATE '2026-02-26', 77.1218),
    ('USDRUB_TOM', DATE '2026-02-27', 77.2736),
    ('USDRUB_TOM', DATE '2026-03-02', 77.1734),
    ('USDRUB_TOM', DATE '2026-03-03', 77.6093),
    ('USDRUB_TOM', DATE '2026-03-04', 77.6325),
    ('USDRUB_TOM', DATE '2026-03-05', 78.89),
    ('USDRUB_TOM', DATE '2026-03-06', 78.6),
    ('USDRUB_TOM', DATE '2026-03-09', 79.15),
    ('USDRUB_TOM', DATE '2026-03-10', 78.86),
    ('USDRUB_TOM', DATE '2026-03-11', 79.068),
    ('USDRUB_TOM', DATE '2026-03-12', 79.0671),
    ('USDRUB_TOM', DATE '2026-03-13', 80.2254),
    ('EURRUB_TOM', DATE '2026-01-05', 92.0938),
    ('EURRUB_TOM', DATE '2026-01-06', 92.0938),
    ('EURRUB_TOM', DATE '2026-01-08', 92.0938),
    ('EURRUB_TOM', DATE '2026-01-09', 92.0938),
    ('EURRUB_TOM', DATE '2026-01-12', 91.9668),
    ('EURRUB_TOM', DATE '2026-01-13', 92.3973),
    ('EURRUB_TOM', DATE '2026-01-14', 92.1964),
    ('EURRUB_TOM', DATE '2026-01-15', 91.8123),
    ('EURRUB_TOM', DATE '2026-01-16', 90.53659999999999),
    ('EURRUB_TOM', DATE '2026-01-19', 90.1611),
    ('EURRUB_TOM', DATE '2026-01-20', 91.1954),
    ('EURRUB_TOM', DATE '2026-01-21', 90.7211),
    ('EURRUB_TOM', DATE '2026-01-22', 88.7898),
    ('EURRUB_TOM', DATE '2026-01-23', 89.0589),
    ('EURRUB_TOM', DATE '2026-01-26', 90.2877),
    ('EURRUB_TOM', DATE '2026-01-27', 90.9329),
    ('EURRUB_TOM', DATE '2026-01-28', 91.2988),
    ('EURRUB_TOM', DATE '2026-01-29', 90.9751),
    ('EURRUB_TOM', DATE '2026-01-30', 90.468),
    ('EURRUB_TOM', DATE '2026-02-02', 91.247),
    ('EURRUB_TOM', DATE '2026-02-03', 90.7178),
    ('EURRUB_TOM', DATE '2026-02-04', 91.1138),
    ('EURRUB_TOM', DATE '2026-02-05', 90.2881),
    ('EURRUB_TOM', DATE '2026-02-06', 91.0451),
    ('EURRUB_TOM', DATE '2026-02-09', 92.0136),
    ('EURRUB_TOM', DATE '2026-02-10', 91.9429),
    ('EURRUB_TOM', DATE '2026-02-11', 92.475),
    ('EURRUB_TOM', DATE '2026-02-12', 91.7113),
    ('EURRUB_TOM', DATE '2026-02-13', 91.5575),
    ('EURRUB_TOM', DATE '2026-02-16', 91.0368),
    ('EURRUB_TOM', DATE '2026-02-17', 90.8658),
    ('EURRUB_TOM', DATE '2026-02-18', 90.2683),
    ('EURRUB_TOM', DATE '2026-02-19', 90.1669),
    ('EURRUB_TOM', DATE '2026-02-20', 90.2833),
    ('EURRUB_TOM', DATE '2026-02-24', 90.5821),
    ('EURRUB_TOM', DATE '2026-02-25', 90.3211),
    ('EURRUB_TOM', DATE '2026-02-26', 91.0281),
    ('EURRUB_TOM', DATE '2026-02-27', 91.2965),
    ('EURRUB_TOM', DATE '2026-03-02', 90.7307),
    ('EURRUB_TOM', DATE '2026-03-03', 90.3098),
    ('EURRUB_TOM', DATE '2026-03-04', 90.7458),
    ('EURRUB_TOM', DATE '2026-03-05', 90.7926),
    ('EURRUB_TOM', DATE '2026-03-06', 91.8391),
    ('EURRUB_TOM', DATE '2026-03-09', 91.8391),
    ('EURRUB_TOM', DATE '2026-03-10', 91.8979),
    ('EURRUB_TOM', DATE '2026-03-11', 91.9378),
    ('EURRUB_TOM', DATE '2026-03-12', 91.3893),
    ('EURRUB_TOM', DATE '2026-03-13', 91.9847)
),
resolved AS (
    SELECT
        i.id AS instrument_id,
        s.trade_date,
        s.price::numeric(18,4) AS price,
        i.currency_id,
        md5(i.id::text || '|' || s.trade_date::text || '|TBANK') AS hash_key
    FROM src s
    JOIN instruments i
      ON upper(coalesce(i.figi, '')) = s.db_code
      OR upper(i.ticker) = s.db_code
)
INSERT INTO prices (id, instrument_id, date, value, currency_id, provider, created_at, updated_at)
SELECT
    (
        substr(hash_key, 1, 8) || '-' ||
        substr(hash_key, 9, 4) || '-' ||
        substr(hash_key, 13, 4) || '-' ||
        substr(hash_key, 17, 4) || '-' ||
        substr(hash_key, 21, 12)
    )::uuid,
    instrument_id,
    (trade_date::timestamp AT TIME ZONE 'UTC'),
    price,
    currency_id,
    'TBANK',
    now(),
    now()
FROM resolved
ON CONFLICT (instrument_id, date, provider)
DO UPDATE
SET value = EXCLUDED.value,
    currency_id = EXCLUDED.currency_id,
    updated_at = now();

COMMIT;
