name: Larchik-workflow

on:
  push:
    branches:
      - main

jobs:

  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Build the Docker image
          run: |
            docker-compose -f docker-compose.yml -f docker-compose.override.yml build
        - name: Push images
          run: |
            docker tag larchikapi:latest infernalred/larchikapi:latest
            docker push infernalred/larchikapi:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
         sudo docker pull ${{ secrets.DOCKER_FRONT_REPO }}
         sudo docker-compose stop
         sudo docker-compose rm larchik.react
         sudo docker-compose up -d