name: Larchik-workflow

on:
  push:
    branches:
      - main

jobs:

  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: Push to Docker Hub
          run: docker-compose -f docker-compose.yml -f docker-compose.override.yml up -d

  deploy:
    name: Build
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: whoami