name: Larchik-workflow

on:
  push:
    branches:
      - main

jobs:

  build_and_push_to_docker_hub:
      name: Push Docker image to Docker Hub
      runs-on: ubuntu-latest
      steps:
        - name: Check out the repo
          uses: actions/checkout@v2
        - name: Login to DockerHub
          uses: docker/login-action@v2
          with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
        - name: Push API to Docker Hub
          uses: docker/build-push-action@v3
          with:
            context: .
            file: Larchik.API/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_API_REPO }}:latest
        - name: Push APP to Docker Hub
          uses: docker/build-push-action@v3
          with:
            context: .
            file: client-app/Dockerfile
            push: true
            tags: ${{ secrets.DOCKER_FRONT_REPO }}:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_push_to_docker_hub
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USER }}
        password: ${{ secrets.SSH_PASSWORD }}
        port: ${{ secrets.SSH_PORT }}
        script: |
         rm -f .env
         touch .env
         echo TokenKey=${{ secrets.TOKENKEY }} >> .env
         echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
         echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
         sudo docker-compose -f ./docker-compose_prod.yml stop
         sudo docker-compose -f ./docker-compose_prod.yml rm larchik.api
         sudo docker-compose -f ./docker-compose_prod.yml rm larchik.app
         sudo docker-compose -f ./docker-compose_prod.yml up -d